### ISSUE TITLE
pip install csvkit because of openpyxl

### ISSUE THREAD

**Issue by pombredanne** [wireservice/csvkit#1002]
Openpyxl latest version has a bug https://bitbucket.org/openpyxl/openpyxl/issues/1126/cant-create-a-wheel and therefore csvkit does not install atm

**Comment by pombredanne** [comment]
My bad... this is not a blocker: https://bitbucket.org/openpyxl/openpyxl/issues/1126/cant-create-a-wheel#comment-48993560

**Comment by jpmckinney** [comment]
Seems to have been fixed upstream.
