### ISSUE TITLE
concat with NULL values

### ISSUE THREAD

**Issue by pinsardfr** [wireservice/csvkit#1003]
This following command work fine :

```
echo '"02","001"' | csvsql --no-header-row --no-inference --query 'SELECT a||b FROM stdin'
giving
a||b
02001
```

_Originally posted by @jpmckinney in https://github.com/wireservice/csvkit/issues/930#issuecomment-370254283_
but this one does not give me the expected result ("001")

```
echo '"","001"' | csvsql --no-header-row --no-inference --query 'SELECT a||b FROM stdin'
a||b
""
```

**Comment by jpmckinney** [comment]
That's because of how SQL works. You need to `COALESCE` values that might be null, e.g.:

```
echo '"","001"' | csvsql --no-header-row --no-inference --query 'SELECT COALESCE(a, "") || b FROM stdin'
```
