### ISSUE TITLE
fails to convert xls to csv that has latin-1 encoding

### ISSUE THREAD

**Issue by archits** [wireservice/csvkit#1005]
in2csv fails to properly convert xls file if it has an apaostrophe character in one of the rows. It converts all the rows upto the row containing apaostrophe character and drops everything after it.

It throws the following error:
'latin-1' codec can't encode character '\u2019' in posotion 115: ordinal not in range(256)

**Comment by chrstphrchvz** [comment]
U+2019 `’` is a ["curly"/"smart"/typographical right apostrophe](https://www.fileformat.info/info/unicode/char/2019/index.htm), not an ordinary/"dumb"/straight apostrophe `'`. Certain programs like word processors and platforms such as macOS and iOS tend to insert these automatically for the user.

If you intend to keep apostrophes in the output, one approach might be to run the input through [Unidecode](https://pypi.org/project/Unidecode/); I'm not sure if there's anything in csvkit nor the Python standard library to automatically handle this.
