### ISSUE TITLE
Detect and remove UTF-8 BOM

### ISSUE THREAD

**Issue by doekman** [wireservice/csvkit#1007]
The bug is illustrated [with files from this zip](https://github.com/wireservice/csvkit/files/2652481/csvkit-UTF8_BOM-bug.zip)

`example.csv` is a CSV file, saved with UTF-8 with BOM marker and LF linefeeds (the webapp [highrise](https://highrisehq.com) uses this format).

When running `./setup.sh` the file is imported into the user-database, and everything seems fine:

    csvsql 1.0.2
    Python 2.7.15
    ProductName:	Mac OS X
    ProductVersion:	10.13.6
    BuildVersion:	17G3025
    NOTICE:  table "example" does not exist, skipping
    DROP TABLE

However, when running `./test.sh`, the second command fails (and the first and third succeed):

    ----[ select * ]--------------------------------------------
       ﻿FullName   |        Email        
    --------------+---------------------
     Test User    | test@example.com
     Another User | another@example.com
    (2 rows)

    ----[ select FullName, Email ]------------------------------
    ERROR:  column "fullname" does not exist
    LINE 1: SELECT FullName, Email from example;
                   ^
    HINT:  Perhaps you meant to reference the column "example.﻿FullName".
    ----[ select [BOM-marker]FullName, Email ]------------------
       ﻿FullName   |        Email        
    --------------+---------------------
     Test User    | test@example.com
     Another User | another@example.com
    (2 rows)

This is because the first column name is prefixed with the BOM marker, and is demonstrated by the third command. When you copy/paste the output into an editor that shows control characters (TextMate), you see the name of the first column is actually `U&"\FEFFFullName"

When the header columns in the CSV file are double-quoted ("FullName","Email"), the behaviour is different but also undesirable, but I haven't checked that.

The error message could be nicer (non-printable characters could be shown escaped as I did in the third example), but I'm not sure which software part that would have to do...

From **csvkit**, I expect the UTF-BOM marker to be detected and removed.

**Comment by chrstphrchvz** [comment]
Have you tried `csvsql -e utf-8-sig`? https://csvkit.readthedocs.io/en/1.0.3/tricks.html#reading-a-csv-with-a-byte-order-mark-bom

I'm guessing that since this is documented, it might be expected behavior.

**Comment by doekman** [comment]
That will probably work. 

But it's a difficult problem to debug. An editor like TextMate detects automatically if there's an UTF-8 BOM.

Anyways, I'm not saying csvkit is not correct, I'm saying csvkit could be more helpful. But I know Python and Unicode can be a rabit hole...

**Comment by jpmckinney** [comment]
CSVs with BOM markers are relatively rare, so we haven't built in support for automatic detection and removal. It's come up in a few issues, though, so I'll rename this issue as a feature request.

**Comment by felixbuenemann** [comment]
@jpmckinney Why not simply change the default encoding from `utf-8` to `utf-8-sig`.

Since `utf-8-sig` works with and without BOM, so there isn't really a drawback to use if by default.

This is not as cool as full autodetection of encoding when a BOM is present (UTF-16LE/BE, UTF-32LE/BE etc.), but will handle the most common case of UTF-8 with and without BOM.

**Comment by jpmckinney** [comment]
I wasn't aware that it worked without BOM. I'd be happy to merge a pull request (with a test) that changes the default.

**Comment by felixbuenemann** [comment]
@jpmckinney I submitted my proposed change in #1037.
