### ISSUE TITLE
csvlook - border lines?

### ISSUE THREAD

**Issue by sarnobat** [wireservice/csvkit#1008]
Is there a way to make tables show borders a lot like MySql or SQLPlus? e.g.

```
+----------+-------+--------+
| count(1) | state | status |
+----------+-------+--------+
|    36980 |     0 |      0 |
|  5792900 |     1 |      1 |
|    14787 |     2 |      2 |
|      214 |     3 |      2 |
|     1247 |     4 |      2 |
| 35788849 |     5 |      2 |
|        1 |     7 |      1 |
+----------+-------+--------+
```

As far as I know, you just get field delimiting and whitespace padding but no header and footer borders.

```
| count(1) | state | status |
|----------|-------|--------|
|    36980 |     0 |      0 |
|  5792900 |     1 |      1 |
|    14787 |     2 |      2 |
|      214 |     3 |      2 |
|     1247 |     4 |      2 |
| 35788849 |     5 |      2 |
|        1 |     7 |      1 |
```

The `+` signs make it look even nicer.

**Comment by sarnobat** [comment]
Hmmmmmm, is it my version of csvkit that is old?

Here I see the desired output: https://www.slideshare.net/g33ktalk/command-line-data-science

**Comment by jpmckinney** [comment]
`+` might look nicer, but it's not Markdown-compatible.

Those slides must be using version 0.9.x

**Comment by sarnobat** [comment]
If it was just an option rather than mandatory, would it still need to be markdown compatible?

**Comment by jpmckinney** [comment]
Why do you need this feature? We're not looking to support multiple output formats.

**Comment by sarnobat** [comment]
It's more natural to human readers. Sometimes over Slack or in Jira tickets I need to share rest results or data with colleagues. Aesthetics make a difference ;)

**Comment by jpmckinney** [comment]
Hmm, if you paste the output into a Gist on GitHub it will render it as a table, which is even more friendly to human readers.

**Comment by sarnobat** [comment]
Those are just example use cases. I don't have a list of use cases. As a geek I'm looking for attractive plaintext, not rich text. I thought the whole point of csvkit was to make work at the command line more enjoyable (and it does, minus this one thing).

**Comment by jpmckinney** [comment]
This is a very minor improvement, so will likely not be changed.
