### ISSUE TITLE
Join behavior

### ISSUE THREAD

**Issue by asbuch** [wireservice/csvkit#1009]
The result of csvjoin is not what I expected.  I believe that "csvjoin file1.txt file2.txt" should produce join12.txt.

[file1.txt](https://github.com/wireservice/csvkit/files/2718955/file1.txt)
[file2.txt](https://github.com/wireservice/csvkit/files/2718956/file2.txt)
[join12.txt](https://github.com/wireservice/csvkit/files/2718957/join12.txt)

**Comment by jpmckinney** [comment]
That's not how it's supposed to work:

https://csvkit.readthedocs.io/en/1.0.3/tutorial/3_power_tools.html#csvjoin-merging-related-data
https://csvkit.readthedocs.io/en/1.0.3/scripts/csvjoin.html

Your two files have no column in common, so there is nothing to join.

To get your output, you would need to add a column to each CSV to use as a join column, e.g;

    csvjoin -c group <(csvstack -g 1 file1.txt) <(csvstack -g 1 file2.txt) | csvcut -C group
