### ISSUE TITLE
Sorting huge CSV by 7th column

### ISSUE THREAD

**Issue by baerbock** [wireservice/csvkit#1010]
I would like to sort a 300 MB CSV (with header) from https://data.open-power-system-data.org/renewable_power_plants/2018-03-08/renewable_power_plants_DE.csv by the 7th column _electrical_capacity_ which contains numerical values:

```
0.075
0.02937
0.4
0.303
```

How could I do this with csvkit? Thank you very much for any guidance.

**Comment by kintaro1981** [comment]
csvsort is not working with it?

**Comment by jpmckinney** [comment]
Please try csvsort: https://csvkit.readthedocs.io/en/1.0.3/scripts/csvsort.html
