### ISSUE TITLE
in2csv ''gbk' codec can't encode character '\xa0' in position 200: illegal multibyte sequence

### ISSUE THREAD

**Issue by benci042** [wireservice/csvkit#1012]
Hi guys, when i using in2csv to convert excel files .xls to csv . i got error like this 
d:\ in2csv --encoding-xls utf-8 --skip-lines 2 20190108102954.xls > 6.csv
'gbk' codec can't encode character '\xa0' in position 200: illegal multibyte sequence.
 and the new csv files only part of source execl file.

**Comment by jpmckinney** [comment]
Can you provide (a sample of) the Excel file? Otherwise, I can't debug.

**Comment by jpmckinney** [comment]
No answer, so closing.
