### ISSUE TITLE
csvsql boolean column incorrect for mssql

### ISSUE THREAD

**Issue by fretje** [wireservice/csvkit#1015]
When I try to generate a create table statement for sql server from a csv file which contains a boolean field, the create table statement uses the "BOOLEAN" datatype, which is not supported by sql server. It should use "BIT".

E.g. a csv file (test.csv) with the following contents:

```
Test
Yes
No
```

When using this commandline:

` csvsql .\test.csv -i mssql`

generates the following statement:

```
CREATE TABLE test (
        [Test] BOOLEAN NOT NULL
);
```

but it should generate this:

```
CREATE TABLE test (
        [Test] BIT NOT NULL
);
```

**Comment by jpmckinney** [comment]
Does `BOOLEAN` cause an error in SQL Server?

**Comment by jpmckinney** [comment]
Closed by above commit
