### ISSUE TITLE
Dependencies are not frozen

### ISSUE THREAD

**Issue by wagonli** [wireservice/csvkit#1016]
Dependencies should be set to a specific version and not "greater than" a specific version to avoid potential breaking changes introduced by dependencies updates.

**Comment by jpmckinney** [comment]
Is there a dependency that caused an error? We can simply set a "less than" for that dependency.

**Comment by jpmckinney** [comment]
Ah, related to openpyxl. I'll fix the bug instead.

Freezing dependencies makes sense for deployments. It doesn't make sense for libraries (unless you're using Node, which isolates each library's dependencies). Imagine I freeze openpyxl to 2.3, but another library you use expects > 2.3. The two libraries won't work together…
