### ISSUE TITLE
error using in2csv for xlsx: iter_rows() got an unexpected keyword argument 'row_offset'

### ISSUE THREAD

**Issue by AlexHaaniWink** [wireservice/csvkit#1017]
Searching for that error I found this discussion and specific remark: https://stackoverflow.com/a/54716591

There someone found that something recently changed in openpyxl.
Uninstalling the 2.6.0 version and forcing 2.5.0 (as mentioned in the follow-up comment) made that the conversion of my test file worked.

I used the following file (downloaded from http://file-examples.com/index.php/sample-documents-download/sample-xls-download/):

[file_example_XLSX_50.xlsx](https://github.com/wireservice/csvkit/files/2888230/file_example_XLSX_50.xlsx)

**Comment by leftiness** [comment]
Duplicates https://github.com/wireservice/agate-excel/issues/26

**Comment by timfreund** [comment]
Thanks for spotting this @leftiness - this error in in2csv is what got me looking at agate-excel. PR 27 on that project will solve this issue.  (I tested locally on a sample doc before submitting that PR)

**Comment by jpmckinney** [comment]
Thanks! I merged https://github.com/wireservice/agate-excel/pull/27
