### ISSUE TITLE
csvclean 1.0.3 delimiter arg not working 

### ISSUE THREAD

**Issue by odalton** [wireservice/csvkit#1019]
There seems to be an issue with **csvclean 1.0.3** where the -d or --delimiter is not working,
I have a load of csv files that are meant to be comma separated and a few seem to be tab separated.
I am looping over these files with this cmd : 

```csvclean -n -d "," path_to_file.csv```

The output shows "No Errors." even when it reads in a csv that is \t tab separated.  

Is this a known issue in this version should I roll back to a previous version? 

Thanks for your help - I think this is an excellent tool.

## Python Debug:
Namespace(delimiter=',', doublequote=True, dryrun=True, encoding='utf-8', escapechar=None, field_size_limit=None, input_path='staff.csv', line_numbers=False, no_header_row=False, quotechar=None, quoting=None, skip_lines=0, skipinitialspace=False, tabs=False, verbose=False, zero_based=False)

self.reader_kwargs = {'delimiter': ',', 'doublequote': True, 'skipinitialspace': False}

## Virtual Environment running 
Python 3.6.5
csvclean 1.0.3
System Version: macOS 10.14.2 (18C54)
Kernel Version: Darwin 18.2.0

## Csvclean 1.0.3 documentation:
  -d DELIMITER, --delimiter DELIMITER
                        Delimiting character of the input CSV file.
  -t, --tabs            Specify that the input CSV file is delimited with
                        tabs. Overrides "-d".

**Comment by jpmckinney** [comment]
If you set the delimiter as comma when the real delimiter is tab, no program can know that the real delimiter is tab (without performing some form of heuristic analysis). The tab characters will simply be interpreted as data within a cell. So, it makes sense that it reports no errors. How would it know otherwise?
