### ISSUE TITLE
in2csv -- columns with only zeroes and/or ones will become boolean

### ISSUE THREAD

**Issue by myrdd** [wireservice/csvkit#1020]
very quick demonstration:

<pre>
<b>$ echo '[{"int":0},{"int":1},{"int":2}]' | in2csv -f json</b>
int
0
1
2
<b>$ echo '[{"int":0},{"int":1}]' | in2csv -f json</b>
int
False
True
</pre>

workaround: use `-I`

<pre>
<b>$ echo '[{"int":0},{"int":1}]' | in2csv --no-inference -f json</b>
int
0
1
</pre>

my environment:

* csvkit 1.0.3, installed via pip3
* Python 3.5.3
* Debian GNU/Linux v9 (stretch)
* Linux kernel 4.9.144-3.1 (2019-02-19) x86_64

**Comment by jpmckinney** [comment]
This goes back to the design decision to have inference on by default (for which the workaround described here is to explicitly turn off inference). See #890 (and other issues) about why the default is what it is.

**Comment by myrdd** [comment]
Thanks. I should have checked [Tips and Troubleshooting • CSV data interpretation](https://csvkit.readthedocs.io/en/latest/tricks.html#csv-data-interpretation).
