### ISSUE TITLE
csvstat adds commas in numeric outputs

### ISSUE THREAD

**Issue by dmillzilla** [wireservice/csvkit#1021]
I recently updated from v0.9.1 to v1.0.3 and noticed `csvstat` now includes commas to separate number values. It doesn't appear there is a flag to specify all the values as `Text` to disallow csvstat from injecting commas.

As an example, suppose I have `foo.csv`:

```
country_name,token,cardholder_name,identifier,city
US,100,Orisa,5555555555554444,Numbani
Canada,99,McCree,2223000048400011,Château Guillard
GB,98,Zenyatta,4111111111111111,Lijiang Tower
```

Running `csvstat --freq foo.csv` outputs something including the following:

```
  4. identifier: { "5555555555554444": 1, "2223000048400011": 1, "4111111111111111": 1 }
```

That is the ideal styling for output. However, when all of the data is queried with `csvstat foo.csv`:

```
  4. "identifier"

	Type of data:          Number
	Contains null values:  False
	Unique values:         3
	Smallest value:        2,223,000,048,400,011
	Largest value:         5,555,555,555,554,444
	Sum:                   11,889,666,715,065,566
	Mean:                  3,963,222,238,355,188.667
	Median:                4,111,111,111,111,111
	StDev:                 1,671,192,655,285,469.496
	Most common values:    5,555,555,555,554,444 (1x)
	                       2,223,000,048,400,011 (1x)
	                       4,111,111,111,111,111 (1x)
```

That is not ideal and I'd like to discover a way to remove the commas without needing to `sed` away the output. These are being falsely labelled as numbers, even though they should be evaluated as strings. Is there an effective way to correct this?

**Comment by jpmckinney** [comment]
Use `--no-inference` to treat all values as text.

**Comment by dmillzilla** [comment]
Thanks for the input. I see that available for other utilities like `csvjoin`, but not `csvstat`. Perhaps it's worth adding?

**Comment by jpmckinney** [comment]
Aha, yes, that's issue #965
