### ISSUE TITLE
csvkit 0.9 series

### ISSUE THREAD

**Issue by fgregg** [wireservice/csvkit#1022]
At DataMade, we've found that the 0.9 series is a bit more reliable for us than than the 1.0 series. 

I was about to fork the project in order to work on modernizing some dependencies, but I wondered if there would be any appetite to allow me to become an official maintainer of a 0.9 series? 

Thanks for your consideration!

Best,

Forest

**Comment by jpmckinney** [comment]
@fgregg I'd be happy for you to maintain the 0.9 series.

However, it'd be helpful to know what issues you have with the 1.0 series, as 1.0 contains a lot of improvements and bugfixes compared to 0.9.

**Comment by fgregg** [comment]
That's a very fair question, and I'm sorry I don't have a fuller accounting. My generalized perception is that I run into more problems converting excel files into csv, and that I seem to have more problems related to sniffing. If I was a better citizen, I would continue to report these.

**Comment by jpmckinney** [comment]
Both use Python's [csv.Sniffer](https://docs.python.org/3.7/library/csv.html#csv.Sniffer), so I'm not sure there is a real difference in behavior across csvkit versions; if there is, the cause can likely be corrected in 1.0.

I'm not aware of any change in behavior with respect to Excel files (no issues have been reported about that), and 1.0 includes several bugfixes in Excel handling.

I think the first steps (like when I became maintainer) would be to write PRs for the fixes you want, and to open issues for bugs you find, and after a time @onyxfish can add you to the project (I don't have admin access, only write access).

**Comment by fgregg** [comment]
i'm quite able to believe I have some superstitious learning. I will write some PRs against the 0.9 branch

**Comment by jpmckinney** [comment]
Great! 🎉

**Comment by jpmckinney** [comment]
One thing: Please @ me in the PRs when ready, as I don't watch this repository (I instead check every once in a while).
