### ISSUE TITLE
Confusion with STDIN

### ISSUE THREAD

**Issue by slhck** [wireservice/csvkit#1023]
I am using 1.0.3, and I'm trying to run a query using `sql2csv`. Since the query is somewhat complex, I don't want to wrap it in quotes and use the `--query` parameter. Instead, I want to use STDIN.

From the help, I see that "If both FILE and QUERY are omitted, query will be read from STDIN.".

I expected to be able to run:

```
sql2csv --db "mysql+pymysql://root:foo@localhost:3307"
```

And wait for the program to me to enter something, but that doesn't work. Instead it shows:

```
sql2csv: error: You must provide an input file or piped data
```

The documentation should mention that "read from STDIN" means that you have to pipe, because the program could in principle just wait for me to enter data like `cat` does.

I see that [using `-`](https://csvkit.readthedocs.io/en/1.0.3/tricks.html#specifying-stdin-as-a-file) is also possible, but it's not mentioned in the `sql2csv` usage. Would it make sense to explicitly add this?

**Comment by jpmckinney** [comment]
I've corrected the documentation – thanks!
