### ISSUE TITLE
can we install csvtool kit on windows?

### ISSUE THREAD

**Issue by Hari5734** [wireservice/csvkit#1024]
Hi All,

Can we install csv toolkit on my windows, if yes, what would be the recommended configurations.?
can any one help on this?
Thanks,
Hari

**Comment by jpmckinney** [comment]
Once you've installed Python on Windows, you can install it with `pip`, like in the docs https://csvkit.readthedocs.io/en/latest/tutorial/1_getting_started.html#installing-csvkit

**Comment by VladimirVinarsky** [comment]
Hello, installed the csv kit, but does not work (not recognized as cmdlet), so wondering if it shuould be added to the path? Cant find it in programmes to add it.
Thank you very much for you help

**Comment by jpmckinney** [comment]
I'm not familiar with Windows installations (there are many ways to get Python available on Windows). In general, if you're able to install *any* Python package that provides a command-line command, then csvkit will also work.
