### ISSUE TITLE
"unsupported operand type(s) for -: 'int' and 'str'" error

### ISSUE THREAD

**Issue by slhck** [wireservice/csvkit#1025]
Using version 1.0.4 for this file I get:

```
➜ csvlook logs/BigBuckBunny-1080-2pass-maxrate1-bufsize1_quality.csv
unsupported operand type(s) for -: 'int' and 'str'
```

[BigBuckBunny-1080-2pass-maxrate1-bufsize1_quality.log](https://github.com/wireservice/csvkit/files/3094334/BigBuckBunny-1080-2pass-maxrate1-bufsize1_quality.log)

(`.log` extension used instead of `.csv` to upload here.)

**Comment by jpmckinney** [comment]
You have several rows with `inf` (infinity) causing errors in agate. I've created a PR for agate, but for now you can try removing those inf values. https://github.com/wireservice/agate/pull/726

**Comment by slhck** [comment]
Thanks a lot for filing/fixing that upstream bug, much appreciated!

**Comment by jpmckinney** [comment]
Looks like I fixed the upstream issue and never closed this!
