### ISSUE TITLE
Install cvskit in Centos 7

### ISSUE THREAD

**Issue by nishajgd** [wireservice/csvkit#1026]
I am unable to find an option through which I can successfully install csvkit in Centos 7.
The details related to that is also missing in cvskit installation documentation.
Can anyone please throw light on this if possible? Thank You!

**Comment by nishajgd** [comment]
I found a way out for this here.
https://github.com/amandabee/workshops/wiki/Tutorial:-Installing-CSVKit

**Comment by jpmckinney** [comment]
For others, see this part of the docs: https://csvkit.readthedocs.io/en/latest/tricks.html#installation
