### ISSUE TITLE
csvjson does not convert integers in proper format

### ISSUE THREAD

**Issue by nishajgd** [wireservice/csvkit#1028]
I am using  the below commands to convert from csv to json.

`csvjson input.csv > output.json
`
input.csv

`name,number_field
test,0050`

current output.json

`[
{ "name": "test",
  "number_field": 0.50
}
]`

expected output.json

`[
{ "name": "test",
  "number_field": "0050"
}
]`

Am I missing anything here. Can anyone look into this please? Thank you!

**Comment by jpmckinney** [comment]
Command:

    echo "test,0050" | csvjson --no-header-row

Output:

    [{"a": "test", "b": 50.0}]

Anyhow: use `--no-inference` to avoid inferring 0050 to be the number 50.
