### ISSUE TITLE
TimeDelta sum

### ISSUE THREAD

**Issue by oplatek** [wireservice/csvkit#1029]
Hi! 

Thank you for csvkit. 
I am wondering if it would be possible to add the "sum feature" for `TimeDelta` type?

How would I use it?

```
$ csvstat -c Duration --unique test.csv
2

$ csvstat -c Duration --sum test.csv
None   # Here I would expect 4:06:00 instead of None -- sum of the time delta times

$ cat test.csv
Duration
01:16:00
02:50:00
```

I am happy to submit PR.

Thanks

**Comment by jpmckinney** [comment]
Yes, PR welcome! I don't know if agate already supports summing of TimeDelta. If not, you'll have to add it there first, and then update csvkit.

**Comment by dannysepler** [comment]
> Yes, PR welcome! I don't know if agate already supports summing of TimeDelta. If not, you'll have to add it there first, and then update csvkit.

This seemed right! The underlying fix was to support it in agate, which was done here: https://github.com/wireservice/agate/pull/735

How do we update csvkit now? Or does that happen automatically?

**Comment by jpmckinney** [comment]
Yes, if the latest version of agate is installed, it will work!

```
echo "Duration
01:16:00
02:50:00" | csvstat -c Duration --sum
# 4:06:00
```

Thanks for the PR in agate!
