### ISSUE TITLE
in2csv cannot disable type inference on xls files

### ISSUE THREAD

**Issue by arisv** [wireservice/csvkit#1033]
`-I` key is working as intended on .xlsx files
```
>in2csv format.xlsx
A,B,C,D,E,F,G,H,I,J,K
1006209997,1006209997,BOSCH,Vendor,Description,260.46,True,True,4,False,False
```
```
>in2csv -I format.xlsx
A,B,C,D,E,F,G,H,I,J,K
1006209997,1006209997,BOSCH,Vendor,Description,260.46,1,1,4,0,0
```
but that same data in `xls` file has trailing zeroes appended to text fields that look like numbers, which is annoying for my use case because those fields may or may not contain periods that are significant for the data
```
g:\webthings\bonsai_upload_stuff>in2csv format.xls
A,B,C,D,E,F,G,H,I,J,K
1006209997.0,1006209997.0,BOSCH,Vendor,Description,260.46,1.0,1.0,4.0,0.0,0.0
```
```
g:\webthings\bonsai_upload_stuff>in2csv -I format.xls
A,B,C,D,E,F,G,H,I,J,K
1006209997.0,1006209997.0,BOSCH,Vendor,Description,260.46,1.0,1.0,4.0,0.0,0.0
```
So is there any way to force `in2csv` to treat everything in `xls` file as text and text only?

**Comment by jpmckinney** [comment]
Inference is only done on CSV input. Re: XLS, that's just how it comes out of the XLS – nothing csvkit can do about it, as that's the way XLS is storing the data.

**Comment by jpmckinney** [comment]
See #507 - this is a limitation of XLS.
