### ISSUE TITLE
How to specify composite id in csvjoin

### ISSUE THREAD

**Issue by PedroHFranco** [wireservice/csvkit#1036]
I'm trying to make a csvjoin with composite id and is returning duplicate files,

This is the command I'm running

`csvjoin --no-inference --left -c "CODPRODUTOMAPA, CODPRODUTO" -c "NRNF, NUMEROPEDIDO" "saidaAgrotoxicoItens.csv" "receitaItens.csv" -e utf-8 -v > "saidaAgrotoxicoItensTemporary.csv"`

The result is not comming as expected:

Example
saidaAgrotoxicoItens.csv
CNPJRevanda, NRNF, CPDPRODUTOMAPA, VALOR
123,000030855,9298,10
123,000030855,9298,10
123,000030855,9298,10
123,000030855,2008305,10
123,000030855,2008305,10
123,000030855,14511,10

receitaItens.csv
NRART,NUMEROPEDIDO,CODPRODUTO
677,000030855,9298
677,000030855,2008305
677,000030855,14511

saidaAgrotoxicoItensTemporary.csv
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,9298,677
123,000030855,2008305,677
123,000030855,2008305,677
123,000030855,2008305,677
123,000030855,2008305,677
123,000030855,2008305,677
123,000030855,2008305,677
123,000030855,14511,677
123,000030855,14511,677
123,000030855,14511,677

I inserted this columns in a SQL Server and runing the expected left join and its returning just 6 rows, have an way to pass composite id ?

Thanks.

**Comment by jpmckinney** [comment]
You can't specify `-c` multiple times; only the last value is used.

csvjoin doesn't support composite IDs, and is intended for simple joins. Loading the data into SQL seems like the better approach.
