### ISSUE TITLE
Mistyped columns from csvsql

### ISSUE THREAD

**Issue by matthieuoliveira** [wireservice/csvkit#1039]
Since i've moved from version 1.0.3 to the latest version of csvkit, I noticed one of my test failing due to mistyped columns. An example test includes, converting json into csv via in2csv, and then running that output through csvsql. The error that now occurs in the latest version is a decimal type column is labeled as a date type column.

```
import subprocess

table_name = 'demo_table'
path = 'path/to/converted/json/to/csv'
schema_cmd = f'echo $(csvsql --version); cat {path} | csvsql --table {table_name} | sed "s/INTERVAL/VARCHAR/g"'

def generate_schema(command):
    process = subprocess.Popen(command,stdout=subprocess.PIPE, shell=True)
    output, error = process.communicate() 
    schema = output.decode(errors="replace").strip()
    schema= f"DROP TABLE IF EXISTS {table_name}; \n" + schema
    return schema

schema = generate_schema(schema_cmd)

print(schema)
```
I attached the data that was converted from in2csv. Running the above function via 1.0.3 and 1.0.4 should result in the issue I'm seeing. 

Thanks

[data.zip](https://github.com/wireservice/csvkit/files/3493616/data.zip)

**Comment by jpmckinney** [comment]
Using the attached data, I ran:

    cat data | csvsql --table demo_table

And got:

```
CREATE TABLE demo_table (
	id DECIMAL NOT NULL, 
	name VARCHAR NOT NULL, 
	date DATE NOT NULL, 
	description VARCHAR NOT NULL, 
	image_url VARCHAR NOT NULL, 
	mean DATE NOT NULL, 
	average DECIMAL NOT NULL
);
```

What is your expected output?

**Comment by matthieuoliveira** [comment]
@jpmckinney Yes, that seems to be the same output. Notice the 'mean' field is a DATE type which is incorrect given the data in the zip file. I believe if you revert back to  v1.0.3, the correct type should output.

**Comment by jpmckinney** [comment]
Indeed. 1.0.3 has:

```
CREATE TABLE demo_table (
	id DECIMAL NOT NULL, 
	name VARCHAR NOT NULL, 
	date DATE NOT NULL, 
	description VARCHAR NOT NULL, 
	image_url VARCHAR NOT NULL, 
	mean DECIMAL NOT NULL, 
	average DECIMAL NOT NULL
);
```

It's related to supporting the parsing of dates and datetimes without punctuation – we changed the code to try to parse dates first, before parsing numbers. That's why values like `4.5` are being parsed as dates now. I'll push a commit to fix this.

**Comment by matthieuoliveira** [comment]
@jpmckinney Got it got it, thank you!
