### ISSUE TITLE
Don`t create UnnamedColumns  in in2csv.

### ISSUE THREAD

**Issue by sergeydru** [wireservice/csvkit#1044]
Is it possible do not create  UnnamedColumns in in2csv or delete only UnnamedColumns  ?
I would like to delete only UnnamedColumns  not by generated  column name or  column number.

**Comment by jpmckinney** [comment]
Can you not use `csvcut` after using `in2csv`?

**Comment by sergeydru** [comment]
Will  use something  else after in2csv  if it`s not possible in csvcut or in2csv.

**Comment by jpmckinney** [comment]
In what format is your input data?

The usual process is to allow in2csv to create the columns, and to then remove them in a second step, for example:

    echo '1,2,,
    a,b,c,d' | in2csv -f csv | csvcut -C 3-4

or:

    echo '1,2,,
    a,b,c,d' | in2csv -f csv | csvcut -c 1-2
