### ISSUE TITLE
csvjoin producing weird output

### ISSUE THREAD

**Issue by ekkal** [wireservice/csvkit#1047]
csvjoin producing weird output and this is observed on Windows and on Linux when -c option is ignored.

The following are 2 files named as 1 and 2 with the content displayed.

$ head 1 2
==> 1 <==
1,y
2,y
3,y
4,y

==> 2 <==
1,x
2,x
3,x
4,x

csvjoin produces wrong output on 1st record 3rd column (12) and also strange output on the second column on the remaining records (True). 

$ csvjoin 1 2
1,y,12,x
2,True,2,x
3,True,3,x
4,True,4,x

Wondering if I'm missing anything in understanding the usage of the command.

**Comment by jpmckinney** [comment]
`y` is interpreted as `yes` i.e. `True`. Use `-I` (capital i) or `--no-inference` to disable that behavior.

`csvjoin`, like all csvkit tools, assumes that the first row is a header row. If it sees two identical headers, it appends a suffix.  For example:

    $ csvjoin <(echo a,b) <(echo a,b)
    a,b,a2,b2

If the `-c` option is omitted, then as documented:

> -c COLUMNS, --columns COLUMNS
The column name(s) on which to join. Should be either
one name (or index) or a comma-separated list with one
name (or index) for each file, in the same order that
the files were specified. **May also be left
unspecified, in which case the two files will be
joined sequentially without performing any matching.**
