### ISSUE TITLE
using this in python script

### ISSUE THREAD

**Issue by wispedia** [wireservice/csvkit#1050]
how can i  use csvkit in my python script?

**Comment by AnkurBegining** [comment]
You can use `os.system()` and run all the `csvkit` command inside it. It may not be the right solution but it will serve your purpose.

**Comment by liorhar** [comment]
Not sure if that's the way it was meant to be but I was successful with the following:
```
from csvkit.utilities.csvsql import CSVSQL
csvsql = CSVSQL(args=["./myfilecsv"])
csvsql.run()
```

**Comment by jpmckinney** [comment]
Please have a look at agate (and its extensions) which CSV Kit uses. CSV Kit is not intended to be used as a library, but agate is. https://agate.readthedocs.io/
