### ISSUE TITLE
unexpected behavior, (bug?)

### ISSUE THREAD

**Issue by gasconheart** [wireservice/csvkit#1053]
I am a heavy user of csvsql. Thanks for creating this great tool and for making it publicly available. I am not a programmer, I created this account at Github only to contact the maintainers of csvsql.

I had a small database with about 200 lines. It always worked fine with csvsql. I added over 5000 new lines all at once, it works great like that as well. Then I added about 31.000 new lines. I can't have csvsql to process it. I checked the integrity of the csv file, and it is OK. It has no quoted cell whatsoever. It is a personal file for personal use, my personal policy is to automatically remove quotation marks.

The csv file has over 35.000 lines and when I run a query it returns an error message which does not apply to the situation: "Row 0 has 2 values, but Table only has 1 columns." Which is simply not true.

Is this a known issue? Is it solvable? Has anyone ever reported it? I can submit the csv file if you want.

I may not log in to Github soon (or ever), I only created the account to post this feedback. But you can reach me at gasconheart@rawtext.club

Greetings from Spain.

**Comment by jpmckinney** [comment]
Hi @gasconheart, I think the issue is that Python is sniffing the incorrect CSV format. Try with `--snifflimit 0`.
