### ISSUE TITLE
Using in2csv "{xlsx_path}" --write-sheets "-"  to particular directory

### ISSUE THREAD

**Issue by AnkurBegining** [wireservice/csvkit#1054]
Is there any way to run the above command and get all CSV to a particular directory. For now, it is creating all-new CSV file to the directory where my xlsx file is present. I want to create all csv files to my desired directory.

**Comment by jpmckinney** [comment]
Do this instead:

```
mkdir yourdirectory
mv yourfile.xlsx yourdirectory
in2csv yourfile.xlsx --write-sheets -
```

In general, csvkit tries to keep its features to a minimum, especially if a problem can be solved with a couple extra commands.
