### ISSUE TITLE
csvclean: Option to remove newlines from header

### ISSUE THREAD

**Issue by timcashin** [wireservice/csvkit#1056]
I'd love to be able to remove embedded newlines from the header row when converting an Excel file. (May even need ability to remove embedded newlines from all rows, but I haven't encountered that issue yet...)

I see issue #929 is related and may be implemented soon. The sed 1d workaround for that issue doesn't work with newlines in the header.

**Comment by jpmckinney** [comment]
Why do you need to remove the newlines? This might instead be relevant to `csvclean`.

**Comment by timcashin** [comment]
I don't care which tool implements it, but I need all of the column headers to be on one line so that the file can be processed properly by downstream programs such as awk and loaded into a database (where newlines in the file denote new records...)

**Comment by jangxyz** [comment]
I generally need this to pass it over to other unix tooks like `sed`, like the reason in #929. Especially when we don't have #929 yet.

Meanwhile, I did manage to do it by piping around `sed` and `tr`:

```bash
$ cat $file | csvcut OPTIONS | csvformat -M $'\r' | sed -e ':a' -e 'N;$!ba' -e 's/\n/\\n/g' | tr '\r' '\n'
```

Not an expert in `sed`, but the idea is to temporarily change the line terminator to `\r`, then convert all `\n` to `\\n`, and change back `\r` to `\n`.
* `csvformat -M $'\r' `: change character used to terminate lines to `\r` (temporary)
* `sed -e ':a' -e 'N;$!ba' -e 's/\n\\n/g'`: sed command escaping `\n` to `\\n` (from [SO](https://stackoverflow.com/a/1252191/1405998), macos compatible version)
* `tr '\r' '\n'`: now change `\r` back to `\n`

This of course will not run properly if you are already using `\r` characters in your csv file.
I'm not 100% sure if this works for all patterns.
