### ISSUE TITLE
Please consider cutting a release

### ISSUE THREAD

**Issue by alerque** [wireservice/csvkit#1062]
I just ran into a bug that has apparently been [fixed for a long time](https://github.com/wireservice/csvkit/commit/3fee4b03bda058b6e0caed0aca7daea73a115565). It's kind of complicated to move a bunch of production machines from stable packaged releases to git versions. It would be really nice if there was a patch release cut that included at least that, if not other improvements since the last release.

**Comment by jpmckinney** [comment]
Done! https://pypi.org/project/csvkit/

**Comment by alerque** [comment]
Great thanks @jpmckinney! Please also push that tagged commit to the master branch though!

**Comment by jpmckinney** [comment]
Isn't it here? https://github.com/wireservice/csvkit/tree/1.0.5

**Comment by jpmckinney** [comment]
Ah, weird, it wasn't on master for some reason.

**Comment by alerque** [comment]
@jpmckinney That happens when you `git push --tags` without pushing the _branch_. Git will happily send over the commits required to get to the tagged commit and post the tag, but there is nothing that says tags have to be commits on branches. You also need to push the branch so that those commits are included in the branch. It's not uncommon for people no not realize git took them so literally ;-)

**Comment by jpmckinney** [comment]
Thanks :) I usually push both when making a release, but I guess I only did tags this time.
