### ISSUE TITLE
csvsql: is it possible to use a csvsql sql statement output to create a table (inferencing related)

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#1063]
Hi,
sometimes the field inferencing does not work properly. An example I have is a field with this kind of value - `085232` - that becomes `DECIMAL(38, 0)` and it's converted to 85232.

Then I modify

```sql
CREATE TABLE mytable (
	fieldone VARCHAR(27) NOT NULL, 
	`MYFIELD` DECIMAL(38, 0) NOT NULL, 
);
```

to

```sql
CREATE TABLE mytable (
	fieldone VARCHAR(27) NOT NULL, 
	`MYFIELD` VARCHAR(6) NOT NULL, 
);
```

For me it would be great to use csvsql to create a first version of sql statement, to edit it, and then to have have the opportunity to run something like:

```bash
# create the table if not exist
csvsql --db "mysql+pymysql://user:password@localhost/test" --create-if-not-exists --statement mystatement.sql
# insert the data in the table
csvsql --db "mysql+pymysql://user:password@localhost/test" --tables mytable --insert --overwrite --create-if-not-exists myfile.csv
```

Is there a way, using csvkit, to use a sql statement to create a table?

Thank you

**Comment by jpmckinney** [comment]
What would the content of `mystatement.sql` be?

**Comment by aborruso** [comment]
Hi @jpmckinney ,
this is the workflow I'm imaging

```
# create first version of the sql statetement
csvsql -i mysql myfile.csv >mystatement.sql

# edit the statement if it's necessary (as in my example of wrong inferencing)
# then here I have a new version of mystatement.sql

# create the table if not exist
csvsql --db "mysql+pymysql://user:password@localhost/test" --create-if-not-exists --statement mystatement.sql
# insert the data in the table
csvsql --db "mysql+pymysql://user:password@localhost/test" --tables mytable --insert --overwrite --create-if-not-exists myfile.csv
```

Thank you

**Comment by jpmckinney** [comment]
Can you instead run the edited statement directly with mysql (or whichever database you like), and then run the csvsql command with `--no-create` so that it doesn't attempt to re-create the table?

**Comment by aborruso** [comment]
Sure yes, but it would be very comfortable to use it as a complete swiss knife tool.

It's only a csvkit lover feature request

**Comment by jpmckinney** [comment]
Ah, okay. To keep the maintenance burden low, we recommend using tools that are already installed, wherever possible. That way, csvkit is focused on unique features. So, I'll close.
