### ISSUE TITLE
Line count is a little bit off for incorrect CSVs

### ISSUE THREAD

**Issue by wkoszek** [wireservice/csvkit#1064]
### Version + OS info

macOS Catalina. 

### Tool version:

```
$ which csvsql
/usr/local/bin/csvsql
$ csvsql -V
csvsql 1.0.4
```

### Python used:

```
$ head /usr/local/bin/csvsql
#!/usr/local/opt/python/bin/python3.7
...
```

### File:

[csv1.txt](https://github.com/wireservice/csvkit/files/4289808/csv1.txt)

**csv1.txt**

```
hex1,hex2,vr,description
0018,9080,ST,Metabolite Map Description
0018,9081,CS,Partial Fourier
0018,9082,FD,Effective Echo Time (0018,9083) SQ Metabolite Map Code Sequence
0018,9084,SQ,Chemical Shift Sequence
0018,9085,CS,Cardiac Signal Source
```

### Commmand + output:

```
$ csvsql -q ,  csv1.txt
Row 2 has 5 values, but Table only has 4 columns.
```

Assuming header line is Row 0, row 2 in the attached file is fine. It's the row 3 that has a incorrect format.

For couple of other CSV files I see line count is off by 2, not 1.

**Comment by jpmckinney** [comment]
The rows in the error message are 0-indexed, and do not include the column names. So "Row 2" means the 4th line in your CSV. I understand this is confusing, but it'll be more confusing to change the behavior now.

**Comment by wkoszek** [comment]
@jpmckinney Why? It's just the error message needs to be changed. `cat -n` and 'vi' and other tools where you'll be debugging the CSV issues, should patch what the `csvkit` is saying.
