### ISSUE TITLE
csvclean using on all files in a directory (possibly feature or bug)

### ISSUE THREAD

**Issue by stevejlock** [wireservice/csvkit#1066]
Apologies as I am ok on the command line, but not an expert, so this may be something silly or this tool may just not work on multiple CSV files. The files I am using are Google Ads keyword planner outputs that are notoriously difficult to work with as use UTF-16 and tabs with some odd quirks and odd formatting (random rows etc.). All other files I have been using with csvkit have been pretty straight forward. 

`csvclean -e utf-16 -t -K2 example.csv` works very well.

`csvclean csvclean -e utf-16 -t -K2 *.csv` doesn't work as expected as with other commands like stacking files.

Also trying bash code like `for f in *.csv ; do csvclean -e utf-16 -t -K2 $f ; done` doesn't work either or piping into the command or a number of items I tried.

I get the following:

`csvclean csvclean -e utf-16 -t -K2 *.csv` (returns error and all file names)
csvclean: error: unrecognized arguments: Changed Stats 2020-02-19 at 15_17_14.csv Changed Stats 2020-02-19 at 15_17_35.csv

`for f in *.csv ; do csvclean -e utf-16 -t -K2 $f ; done` (returns error and all file names removing the first word)
csvclean: error: unrecognized arguments: Stats 2020-02-19 at 15_21_33.csv

Many thanks in advance, apologies if this is a silly user error issue.

If it helps I've tried using Mac OS X iTerm with both the normal command line environment and switching to conda activate py3.

**Comment by jpmckinney** [comment]
It seems like your shell isn't automatically quoting $f, so do:

`for f in *.csv ; do csvclean -e utf-16 -t -K2 "$f"; done`

This is not a CSV Kit issue.

I don't understand what `csvclean csvclean -e utf-16 -t -K2 *.csv` is expected to do.
