### ISSUE TITLE
How to get just the row count

### ISSUE THREAD

**Issue by Lenbok** [wireservice/csvkit#1067]
Ideally I'd want `csvgrep` to directly support the equivalent of  `grep -c` and `grep -q`, but as a poor man's equivalent we are recommended in #441 to pipe to `csvstat --count`.

However, `csvstat --count` outputs extra text (e.g: `Row count: 8`) so it's an extra step just to extract the count out.

Other commands like `csvstat -c foo --sum` simply output the raw number, so it seems the behaviour of `--count` is a little inconsistent as well as being not very useful.

**Comment by jpmckinney** [comment]
Thanks! This is fixed in HEAD.
