### ISSUE TITLE
csvcut -  null delimited output.

### ISSUE THREAD

**Issue by dontdieych** [wireservice/csvkit#1069]
Hi,

Have one question, does csvcut supports NULL delimited ouput? e.g. for feed to `xargs -0` etc.

Thanks for any advice.

```
❯ csvcut --version
csvcut 1.0.5

~
❯ python --version
Python 3.8.2

Arch Linux
```

**Comment by jpmckinney** [comment]
Can you provide some example usage? I am not sure what you want to do.
