### ISSUE TITLE
in2csv reports field names in lower case, even when they are upper case

### ISSUE THREAD

**Issue by spmundi** [wireservice/csvkit#1073]
Occurs when reading a dbf file.
I don't know whether there exists different species of .dbf files, but the ones I am reading are components of an ESRI Shapefile (a geographic information system file format).

**Comment by jpmckinney** [comment]
Fixed in https://github.com/wireservice/agate-dbf/commit/790e30f65211435da958e93bbec2c04bac5ce205. You'll just need to upgrade agate-dbf.
