### ISSUE TITLE
csvjoin removes "none" values when joining on other columns

### ISSUE THREAD

**Issue by chrisgow** [wireservice/csvkit#1074]
Occurs in csvjoin 1.0.5. Doesn't happen in csvcut, it keeps the none values as is

Example:
a.csv
```
id,name,value,fk
1,Foo,"none",2
2,Bar,"some",2
3,Faz,"none",2
4,Baz,"None",2
```
b.csv
```
id,name
1,Somename1
2,Some Name2
```
command: `csvjoin --verbose --no-inference -c "fk,id" a.csv b.csv`
result:
```
id,name,value,fk,name2
1,Foo,,2,Some Name2
2,Bar,some,2,Some Name2
3,Faz,,2,Some Name2
4,Baz,,2,Some Name2
```
I would expect that columns with "none" in them would still contain the value "none" like csvcut does

**Comment by jpmckinney** [comment]
You need to also set `--blanks`. Type inference is about identifying columns of integers, dates, etc. whereas `--blanks` is about identifying blank values (which can occur in any column).
