### ISSUE TITLE
in2csv: -H flag turns off -I flag

### ISSUE THREAD

**Issue by b-hodge** [wireservice/csvkit#1075]
I have an XLS file in which dates are encoded as "number of days since January 1, 1900". I want date strings, not a float value, so I'm using the -I (or --no-inference) flag to treat every column as text. I also want to use the -H flag so that I can do header processing myself downstream, but these two flags seem to be incompatible:
```
> in2csv -v -I -H test.xls| head | csvcut -c 6
f
Birthdate
29739.0
28637.0
26753.0
21203.0
25800.0
21809.0
27981.0
29046.0

> in2csv -v -I test.xls| head | csvcut -c 6
Birthdate
1981-06-02
1978-05-27
1973-03-30
1958-01-18
1970-08-20
1959-09-16
1976-08-09
1979-07-10
1979-03-02
```

Is this intended behavior? 

Details about my environment:
**in2csv version:** in2csv 1.0.5
**python version:** Python 3.7.3
**OS and version:** macOS Catalina 10.15.3

**Comment by jpmckinney** [comment]
I am confused as to how you are getting different output. Can you share the file? You might need to ZIP it to upload to GitHub.
