### ISSUE TITLE
Disable number formatting with thousands-separators?

### ISSUE THREAD

**Issue by alanhoyle** [wireservice/csvkit#1076]
My apologies if this is covered somewhere, but I can't find it in the command-line help or the readthedocs.io documentation....

How do I disable number formatting with the thousands separator?  When I pipe large numbers through csvlook, it turns "1234567 into "1,234,567" which I can't copy and paste for other purposes as easily.

**Comment by jpmckinney** [comment]
csvlook is intended to format CSVs for human readers, not machine readers. (Machine readers can just use `cat`). That said, if you use `--no-inference`, it should print the numbers without formatting.

**Comment by alanhoyle** [comment]
Thanks @jpmckinney , that is exactly what I needed.  In my case, the numbers are functioning as text identifiers, and have no numerical meaning in the context I use.  E.g. I don't care that it was the 1,234,567th job, I care that it was JOBID  "1234567".  

Much appreciated!
