### ISSUE TITLE
New tool suggestion: csvzip

### ISSUE THREAD

**Issue by ferblape** [wireservice/csvkit#1078]
Hi there,

We have published a small tool we use in many projects [csvzip](https://github.com/PopulateTools/csvzip) to compress CSVs before publishing them as web visualizations with javascript. It's a very basic technique but very effective to reduce the amount of data browsers have to download.

What the script does is to extract categorical variables to a dictionary and replace those values by integers in the CSV.

If you feel like this could be useful to add in csvkit I'm available to migrate the code from Cystal to Python. Otherwise feel free to close the issue :)

You are doing a great job with csvkit, thank you so mucho for your work and time 💪

**Comment by jpmckinney** [comment]
Sorry, we aren't adding new tools to csvkit, but we would welcome a PR to add a link to your project :)
