### ISSUE TITLE
in2csv adds a .0 decimal at the end of xls files 

### ISSUE THREAD

**Issue by alexcaglairi** [wireservice/csvkit#1079]
Hi,
I have a problem in the XLS conversion.
Every cell that contains only numbers, even if its format is set to "Text", when is converted add automatically a ".0" at the end.
What can we do? i need to use xls and not xlsx.
To convert my XLS files i use this command:
`in2csv file.xls --no-inference -e utf-8| csvformat -D ";" > test.csv `

Thanks

**Comment by jpmckinney** [comment]
See #507 - this is a limitation of XLS.
