### ISSUE TITLE
[suggestion] allow wildcard for input files

### ISSUE THREAD

**Issue by scollovati** [wireservice/csvkit#1082]
Scenario: a folder full of csv with identical structure (i.e. different annual/monthly/daily reports from an application),

For example it would be great if this command can work:
`csvstack *.csv > total.csv`

Possible issues: deal with duplicated/identical rows.

**Comment by jpmckinney** [comment]
This works out of the box; wildcard expansion is a shell feature, not a csvkit feature. Make sure you are using a shell that does wildcard expansion, like bash, zsh, fish, etc.
