### ISSUE TITLE
Suggestion:  csvuniq

### ISSUE THREAD

**Issue by tseemann** [wireservice/csvkit#1083]
`csvuniq -c col1,col2,...`  would only keep rows where the tuple `(col1,col2,..)` was unique.
This would keep the first row seen.
It would be up to the user to use `csvsort` beforehand.

**Comment by jpmckinney** [comment]
Sorry, csvkit no longer adds entirely new tools: https://github.com/wireservice/csvkit/issues/996#issuecomment-436751706
