### ISSUE TITLE
Line breaks inside cells are normalized

### ISSUE THREAD

**Issue by bodograumann** [wireservice/csvkit#1084]
I chose this tool, because it can transparently handle multi-line cell values.

Now the data contains `<CR><LF>` line breaks in values, e.g.:
```
col1;col2;col3<LF>
val1.1;"long text<CR><LF>
which continues on the next line";val1.3<LF>
```

The `<CR><LF>` should be kept as-is, because it does not delimit two records, but is part of the string value of a cell.
Unfortunatley when handling the file data with `csvcut`, all such line-endings are normalized to `<LF>`.

**Comment by jpmckinney** [comment]
Duplicate #606
