### ISSUE TITLE
sql2csv ask to use PYTHONIOENCODING but even with it the query does not complete

### ISSUE THREAD

**Issue by calebeaires** [wireservice/csvkit#1085]
Python 3 
CSVKit 1.0.5
Ubuntu 18

Everything were working ok, but at some point it stop working.

Error 

```
Your file is not "utf8" encoded. Please specify the correct encoding 
with the -e flag or with the PYTHONIOENCODING environment variable
```

I have tried to execute the command with -e flag or with python tag like above, but still does not run and print the same error:

```
PYTHONIOENCODING='utf-8' sql2csv -H -e utf8 --db 'mysql+mysqldb:// (...)
```

**Comment by jpmckinney** [comment]
Can you share a sample file that causes the error? Impossible to debug, otherwise.

**Comment by UncleSamTech** [comment]
how was this PYTHONIOENCODING resolved?
