### ISSUE TITLE
csvsql : Update an already existing row in an existing db server

### ISSUE THREAD

**Issue by EngineerReversed** [wireservice/csvkit#1087]
I have an already existing postgres server containing a table named `metadata` in `cromwell` database. The current state looks like this:

```
cromwell=> select * from metadata;
                Run ID                |  Person  | Pipeline name |   Tags
--------------------------------------+----------+---------------+----------
 D25A1045-9CA5-4DFB-BB30-F9406CEDFF27 | abhishek | RNA-Seq       | bmrn,dln
```

Now, I have an updated column named `Tags` in `metadata.csv`.
```
Run ID,Person,Pipeline name,Tags
D25A1045-9CA5-4DFB-BB30-F9406CEDFF27,abhishek,RNA-Seq,"bmrn,dln,mn"
```

When I am trying to update the row
`csvsql --db postgresql://<username>:<password>@<ip>:<port>/cromwell --tables metadata --no-create --insert metadata.csv`
it throws an error.
```
IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "metadata_pkey"
DETAIL:  Key ("Run ID")=(D25A1045-9CA5-4DFB-BB30-F9406CEDFF27) already exists.

[SQL: INSERT INTO metadata ("Run ID", "Person", "Pipeline name", "Tags") VALUES (%(Run ID)s, %(Person)s, %(Pipeline name)s, %(Tags)s)]
[parameters: {'Run ID': 'D25A1045-9CA5-4DFB-BB30-F9406CEDFF27', 'Person': 'abhishek', 'Pipeline name': 'RNA-Seq', 'Tags': 'bmrn,dln,mn'}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```
I have kept **RUN ID** as the unique key. I just want to update **Tags** column.
How to update a column value in already existing db server using `csvsql`?

**Comment by jpmckinney** [comment]
csvsql does not have this as a feature. You would have to drop and re-create the tables.
