### ISSUE TITLE
Is there a way to set an entire column equal to a value ??

### ISSUE THREAD

**Issue by isgoren** [wireservice/csvkit#1088]
sorry for posting this here, I don't see a forum or anyplace else to ask this question. 

I'm looking to edit a spreadsheet with 470 columns and set three columns equal to a value like "0" .
I've tried doing this with awk but there are text columns that cause awk to blow out and write to the wrong columns...
hoping there is a way to do this quickly and efficiently with csvkit... 
any advice or way to point me in the right direction... ?

**Comment by jpmckinney** [comment]
You can probably do this a few ways.

First create a new CSV with the three columns, as tall as the original CSV:

```bash
echo 'sepal_length,sepal_width,petal_width' > tmp.csv
for i in $(seq 1 `csvstat --count examples/iris.csv`); do echo '2,3,4' >> tmp.csv; done
```

Then, join it with the original CSV, after cutting those columns:

```bash
csvjoin tmp.csv <(csvcut -C sepal_length,sepal_width,petal_width examples/iris.csv)
```
