### ISSUE TITLE
Option to handle values in columns with no header

### ISSUE THREAD

**Issue by frafra** [wireservice/csvkit#1093]
When a value is linked to a column with no header, csvsql will stop. I think there could be some options to better handle such situations, for example:

- Add an option to discard/ignore those datas (raise a warning instead)
- Add an extra column to catch all the extra values, defined as a list

**Comment by jpmckinney** [comment]
We can add a lot of error-handling in every tool... or you can run the CSV through `in2csv`, which will add the missing headers. The latter is the simpler option.
