### ISSUE TITLE
Question: xlsx files converting 'number' format to floating point

### ISSUE THREAD

**Issue by JashanChopra** [wireservice/csvkit#1097]
Hello! I had a question about the existence of a feature that I was unable to figure out from the documentation. I've got an excel spreadsheet in .xlsx format. Inside it, there are some cells that are formatted with the "number" format type in excel. The raw value of the cell is actually just an integer, but because of the cell being formatted with the "number" format, it appears as a floating point value. I'm converting to a .csv format using `in2csv`, but the tool reads the cell's raw value (the integer) and not what is displayed (the floating point). 

For example:
Raw cell value: 0
What excel displays: 0.0
What in2csv reads: 0
What I need: 0.0

Unfortunately, I cannot change the excel files. Is there any way to specify that `in2csv` reads what excel is displaying, and not the actual raw values that are in the cells?

**Comment by jpmckinney** [comment]
Sorry, this is not supported.
