### ISSUE TITLE
UnicodeEncodeError when trying to write files

### ISSUE THREAD

**Issue by Naudiz** [wireservice/csvkit#1098]
I'm having trouble processing UTF-8 encoded files with csvkit. The system is Windows 10, Python 3.9 although I tested it on 3.6 - 3.8 as well and the error was always the same.

Quick steps to reproduce:

Make a simple CSV with Unicode characters like Russian:
```
ID,Lang,Lang_Native
EN,English,English
DE,German,Deutsch
RU,Russian,Русский
```

Use csvlook to output this file:
```
C:\csvkit_tutorial>csvlook.exe Languages.csv
| ID | Lang    | Lang_Native |
| -- | ------- | ----------- |
| EN | English | English     |
| DE | German  | Deutsch     |
| RU | Russian | Русский     |
```
Looks great! Now try the same, but this time write to a file.
```
C:\csvkit_tutorial>csvlook.exe Languages.csv > out.txt
UnicodeEncodeError: 'charmap' codec can't encode characters in position 17-23: character maps to <undefined>
```

csvlook is just an example for the ease of reproducing the bug. The same error occurs in in2csv and probably all other tools as well.

**Comment by alessandro-lion** [comment]
That codec issue on command redirection to a file is an old "friend" with Python stuff.
I used to bypass it on Windows 7 these two commands before the redirect command, it could be still working on W10:
chcp 65001
set PYTHONIOENCODING=utf-8

**Comment by Naudiz** [comment]
Wow, thanks. I tried chcp 65001 before and had no luck, but had no idea about PYTHONIOENCODING. It seems to fix the issue indeed.

**Comment by Naudiz** [comment]
Small update: The above workaround did not work for "csvclean".
Instead, the following command did work for csvclean:
set PYTHONUTF8=1

**Comment by jpmckinney** [comment]
Yes, these are common issues for Python on Windows.

To set this environment variable for all future sessions, run `setx PYTHONIOENCODING utf-8` and `setx PYTHONUTF8 1`.
