### ISSUE TITLE
csvsql: Row has X values, but Table only has Y columns (for CSV file with ')

### ISSUE THREAD

**Issue by ciupicri** [wireservice/csvkit#1099]
```sh
csvsql --query 'SELECT "Product" FROM stdin' << EOF
Product,Quantity,Price
Bobby 'Tables' XKCD,1,42
EOF
```

fails with:
> Row 0 has 3 values, but Table only has 1 columns.

---

If I remove one of the `'` characters from the input, csvsql stops complaining.

**Comment by jpmckinney** [comment]
Related: #986

Python's CSV sniffer (used by csvkit) is guessing the wrong CSV dialect. To disable it, use `--snifflimit 0`.
