### ISSUE TITLE
Possible way to improve `csvsort` performance

### ISSUE THREAD

**Issue by torotil** [wireservice/csvkit#1101]
A few years ago I’ve written a quick & dirty script for sorting a big (millions of rows, ~1GB) file. It was able to sort the file within less than a minute. The general idea to make it scalable was:

1. Split the file into smaller chunks that can quickly be sorted in memory. Save the in-memory sorted result into one (temporary) file per chunk.
2. [Merge sort](https://en.wikipedia.org/wiki/Merge_sort) two files at a time until there is only one file left. That’s the result.

I didn’t do this back then but this could easily be done in a multi-threaded way for even more performance.

Is this something that’s interesting for this project … or do you rather think this is beyond its scope?

**Comment by jpmckinney** [comment]
[External sorting](https://en.wikipedia.org/wiki/External_sorting) was proposed in #338, but I think it's somewhat beyond the scope. Have you tried xsv for sorting? https://github.com/BurntSushi/xsv

**Comment by torotil** [comment]
@jpmckinney Thanks for the pointer to xsv and also for being clear about the scope of this project.
