### ISSUE TITLE
csvlook no-inference switch needs better description

### ISSUE THREAD

**Issue by eyalroz** [wireservice/csvkit#1103]
When I use `csvlook` on a CSV file, I notice that it does some formatting of fields for me. Specifically, it adds digit-grouping marks  (probably according to my locale). I don't want it to do that, since my content is not necessarily a regular decimal number but a sequence of digits.

I would like to be able to tell csvlook: "Don't change anything in the data you see, just give me what's in the field (without the enclosing double-quotes if they exist)".

**edit:** I've just realized `--no-inference` does this. However - its functionality is not 100% clear from the help screen. Please consider explicitly stating that it prevents any formatting of values for output.

**Comment by jpmckinney** [comment]
Could you suggest the precise help text that you would prefer?

**Comment by eyalroz** [comment]
Right now, the text is:
```
-I, --no-inference    Disable type inference when parsing the input.
```
I would make it, say:
```
-I, --no-inference --no-reformatting
                              Disable all type inference and reformatting of fields
```
(i.e. I would also add an alias for the long-form of the option)
