### ISSUE TITLE
in2csv feature request: only use top-level json keys as columns

### ISSUE THREAD

**Issue by gmile** [wireservice/csvkit#1106]
I am pulling the data from API, converting it into a CSV file, and later pushing this into a PostgreSQL database. `in2csv` is part of this pipeline:

```bash
curl https://api.hubapi.com/companies/v2/companies/paged&limit=250
| in2csv --format json --only-top-level-keys
| csvsql \
    --db my_database \
    --tables hubspot_companies \
    --insert \
    --overwrite
```

The JSON coming from the API I am dealing with looks like this ([source](https://legacydocs.hubspot.com/docs/methods/companies/get-all-companies)):

<details>

```json
[
  {
    "portalId": 62515,
    "additionalDomains": [],
    "properties": {
      "website": {
        "sourceId": null,
        "timestamp": 1457513066540,
        "versions": [
          {
            "timestamp": 1457513066540,
            "sourceVid": [],
            "name": "website",
            "value": "example.com",
            "source": "COMPANIES"
          }
        ],
        "value": "example.com",
        "source": "COMPANIES"
      },
      "name": {
        "sourceId": "name",
        "timestamp": 1464484587592,
        "versions": [
          {
            "name": "name",
            "sourceId": "name",
            "timestamp": 1464484587592,
            "value": "Example Company",
            "source": "BIDEN",
            "sourceVid": []
          }
        ],
        "value": "Example Company",
        "source": "BIDEN"
      }
    },
    "isDeleted": false,
    "companyId": 115200636
  },
  {
    "portalId": 62515,
    "additionalDomains": [],
    "properties": {
      "website": {
        "sourceId": null,
        "timestamp": 1457535205549,
        "versions": [
          {
            "timestamp": 1457535205549,
            "sourceVid": [],
            "name": "website",
            "value": "test.com",
            "source": "COMPANIES"
          }
        ],
        "value": "test.com",
        "source": "COMPANIES"
      },
      "name": {
        "sourceId": "name",
        "timestamp": 1468832771769,
        "versions": [
          {
            "name": "name",
            "sourceId": "name",
            "timestamp": 1468832771769,
            "value": "Test Company",
            "source": "BIDEN",
            "sourceVid": []
          }
        ],
        "value": "Test Company",
        "source": "BIDEN"
      }
    },
    "isDeleted": false,
    "companyId": 115279791
  }
]
```

</details>

The nature of the API I am pulling the data from is such that it would contain a lot of user-defined nested JSON objects. Right now, if I feed the JSON above into `in2csv`, produced CSV has lots of columns, e.g.:

<details>

```csv
portalId,properties/website/sourceId,properties/website/timestamp,properties/website/versions/0/timestamp,properties/website/versions/0/name,properties/website/versions/0/value,properties/website/versions/0/source,properties/website/value,properties/website/source,properties/name/sourceId,properties/name/timestamp,properties/name/versions/0/name,properties/name/versions/0/sourceId,properties/name/versions/0/timestamp,properties/name/versions/0/value,properties/name/versions/0/source,properties/name/value,properties/name/source,isDeleted,companyId
62515,,1457513066540,1457513066540,website,example.com,COMPANIES,example.com,COMPANIES,name,1464484587592,name,name,1464484587592,Example Company,BIDEN,Example Company,BIDEN,False,115200636
62515,,1457535205549,1457535205549,website,test.com,COMPANIES,test.com,COMPANIES,name,1468832771769,name,name,1468832771769,Test Company,BIDEN,Test Company,BIDEN,False,115279791
```

</details>

However, each JSON object from the list has a well-defined small set of keys:

```
isDeleted
companyId
portalId
additionalDomains
properties
```

What would come in handy is if in2csv would be able to use only top-level object keys as column names. For example, where `properties` would be column that would contain a raw array of JSON objects as value in each row.

**Comment by jpmckinney** [comment]
So the CSV cell would contain JSON text? What is the use case for that?

**Comment by gmile** [comment]
> So the CSV cell would contain JSON text?

In short: yes, exactly.

> What is the use case for that?

A request for this feature comes from a need to process JSON items of poorly defined structure.

For example, consider this:

```json
[
  {
    "a": 1,
    "b": {
      "c": 2
    }
  },
  {
    "a": 1,
    "b": {
      "d": 3
    }
  }
]
```

When converting this JSON to a CSV, `in2csv` will produce a CSV with 3 columns:
* `a`,
* `b.c`,
* `b.d`.

On a scale, when processing a list of JSON objects that has many nested objects of poorly defined structure, `in2csv` will produce a CSV with lots and lots (hundreds) of columns.

Later, it is somewhat problematic to import such a CSV containing a lot of columns into a database. For example, we started to hit an issue with PostgreSQL, that would complain about an attempt to make a DB insert with too many columns:
> ERROR: row is too big: size 8344, maximum size 8160

Good explanation of the issue can be seen in [this answer](https://stackoverflow.com/a/57089028/80851) to a question on SO.

Having ability to tell `in2csv` to not "expand" certain top-level JSON keys would help our case tremendously.

**Comment by jpmckinney** [comment]
Thanks for explaining. I see the issue, but I don't know if it's too narrow for csvkit. Could you perhaps remove unwanted keys with jq, so that the total columns for import to the DB is reasonable? https://stedolan.github.io/jq/

**Comment by jpmckinney** [comment]
I'll close the issue as no response. I'm also not sure there is enough demand for this feature.

**Comment by gmile** [comment]
@jpmckinney fair enough. I was able to get around my issue by writing a script in Elixir.

Still glad I've written down the issue though. Perhaps in future this can be revisiting in case someone finds this having a similar need.
