### ISSUE TITLE
in2csv adds unnamed columns the end of file

### ISSUE THREAD

**Issue by GabrielSlPires** [wireservice/csvkit#1108]
I'm using in2csv to open this [file](https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fpce.13687&file=pce13687-sup-0002-Supinfo02.xlsx) with fread() in R. No matter if I use -H or not, I still got the same warning when use:

`in2csv -H raw_files/Janssen_2020/supinfo02.xlsx --sheet Database -K 2`

The warning:
```
/usr/lib/python3/dist-packages/agate/utils.py:275: UnnamedColumnWarning: Column 75 has no name. Using "xxx".
/usr/lib/python3/dist-packages/agate/utils.py:275: UnnamedColumnWarning: Column 76 has no name. Using "yyy".
/usr/lib/python3/dist-packages/agate/utils.py:275: UnnamedColumnWarning: Column 77 has no name. Using "zzz".
/usr/lib/python3/dist-packages/agate/utils.py:275: UnnamedColumnWarning: Column 78 has no name. Using "aaaa".
```

Notice that those columns have no data in the original file.
I can live with that issue, but it would be nice if there is a way that avoids it.

**Comment by jpmckinney** [comment]
Indeed. The columns must be truly empty to be skipped. The test.xlsx file in csvkit's examples/ directory has lots of empty columns that are ignored. If you can ZIP and attach your ZIP file, I can debug. Closing for now.
