### ISSUE TITLE
Undocumented parameter in in2csv

### ISSUE THREAD

**Issue by steve-estes** [wireservice/csvkit#1111]
in2csv's doc page mentions a parameter:

[--encoding-xls ENCODING_XLS]

...but does not explain what it is or how it's used.

I'm trying to wrangle a (maybe partially corrupted?) XLSX file and that seems like it could possibly be helpful, but I don't know what it is / how to use it.

**Comment by jpmckinney** [comment]
Ah, the docs page needs to be updated. When you run `in2csv --help` it shows:

```
  --encoding-xls ENCODING_XLS
                        Specify the encoding of the input XLS file.
```

This is only relevant to XLS files, not XLSX. XLS is a binary format from older versions of Microsoft Excel. XLSX is an XML format. So, if your file is XLSX, this option will have no effect. As you can see here, it is only applied to XLS files:

https://github.com/wireservice/csvkit/blob/7781760655dc9bd3ae0b050030f05728175a23f2/csvkit/utilities/in2csv.py#L145-L146

**Comment by jpmckinney** [comment]
Added in 9bc19f9e
