### ISSUE TITLE
Result is empty

### ISSUE THREAD

**Issue by entin-hun** [wireservice/csvkit#1113]
Hi,
My issue is that upon hitting enter after `csvjson source.csv > result.txt` just an empty result.txt is created (_MacOS Catalina 10.15.7, Python version 3.7.9, pip version: 21.0.1_)
I've got some errors while installing the kit (e.g. "Command errored out with exit status 1"), [please check my install log here](https://docs.google.com/document/d/1E1fT_nCZCRXcp2NpRQv8MFGr2ThtouCGgUX8ZZNDoXQ/edit?usp=sharing)

I need to have a BigQuery-compatible JSONL as soon as possible.

**Comment by jpmckinney** [comment]
See #1122 regarding the PyICU-related errors.

Without a copy or sample of source.csv, this is not possible to debug. Can you attach the file?

**Comment by jpmckinney** [comment]
Closing as no response.

**Comment by jpmckinney** [comment]
Related: #1127
