### ISSUE TITLE
--help should document options to --encoding

### ISSUE THREAD

**Issue by mtfurlan** [wireservice/csvkit#1117]
I just ran into an issue with csvjoin 1.0.5 where a file was failing to parse because
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 377: invalid start byte
```
It didn't like `Á`.

In the end the solution was `--encoding iso-8859-1`, but it was really frustrating that the help said there was an encoding flag and nothing about how to use it.

**Comment by jpmckinney** [comment]
Right now the `--help` has:

```
-e ENCODING, --encoding ENCODING
                      Specify the encoding of the input CSV file.
```

What do you suggest it say?

**Comment by mtfurlan** [comment]
Either have a list of formats in the help there, or add a way to list formats.
* `ffmpeg` has `-formats`
* `convert` does `-list formats`

I think `--encoding` with no argument would be most reasonable, but also not as easy as just putting the list in the help.

**Comment by jpmckinney** [comment]
In the meantime, you can refer to the available encodings in Python here: https://docs.python.org/3/library/codecs.html#standard-encodings

**Comment by jpmckinney** [comment]
Python apparently has [no easy way](https://stackoverflow.com/questions/1728376/get-a-list-of-all-the-encodings-python-can-encode-to) to report the available encodings on a given platform.

I instead just added a link to those docs from https://csvkit.readthedocs.io/en/latest/common_arguments.html

**Comment by mtfurlan** [comment]
Cool, thanks.
