### ISSUE TITLE
sql2csv - Unicode indicators 

### ISSUE THREAD

**Issue by IdrissaD** [wireservice/csvkit#1118]
Hello!
Exporting postgresql table into csv with csvkit added a unicode marker `u` before every json element, as you can see here:
```[{u'nom': u'CC Gorges Causses C\xe9vennes', u'contact': u'https://www.gorgescaussescevennes.fr/'}]```

Is there a way to avoid this, as it causes problems afterwards for validating the json against a schema?

**Comment by jpmckinney** [comment]
What version of Python are you using? I think this can only occur in Python 2.7, which is end-of-life and is not supported.

**Comment by IdrissaD** [comment]
Hm yeah I think that was the reason, thanks! I got away with it by casting my field to text instead of json.
