### ISSUE TITLE
Feature to disable auto generating header rows a,b,c,d ... when using in2csv

### ISSUE THREAD

**Issue by shipsywor** [wireservice/csvkit#1119]
I have a usecase where I do not want header rows generated at all when using in2csv.

Right now, there is no command to disable generating header rows it seems.

If there is a way to disable header rows, please let know.

**Comment by jpmckinney** [comment]
See solution here using *nix commands: https://github.com/wireservice/csvkit/issues/967#issuecomment-418463954
