### ISSUE TITLE
csvjson output with root property name?

### ISSUE THREAD

**Issue by cosmoKenney** [wireservice/csvkit#1121]
Converting csv to json works great. One thing I would like to be able to do is wrap the entire array in an object with a single named property. Instead of outputting this:
```
[
    {
        "prop1": "1234"
    },
    {
        "prop1": "2233"
    }
]
```
Is there a way to output this:
```
{
    "rootProp": [
        {
            "prop1": "1234"
        },
        {
            "prop1": "2233"
        }
    ]
}
```

**Comment by cosmoKenney** [comment]
Nothing?

**Comment by jpmckinney** [comment]
This feature is not provided. You will have to do this as a post-processing step.
