### ISSUE TITLE
Numerical csvsort with --no-inference

### ISSUE THREAD

**Issue by niklaswallerstedt** [wireservice/csvkit#1125]
I'm trying to sort a list of customer ids numerically, a sort of similar issue is #637.

Given this made up list

```csv
id,date,boolean
5009,2021-06-08 15:09:11,true
515,2020-11-08 15:09:11,false
```
If I run this:
```sh
csvsort -c 1 input.csv
```
the sorting is working as expected, except for the type-inference messing with the values.
```csv
id,date,boolean
515,2020-11-08T15:09:11,False
5009,2021-06-08T15:09:11,True
```

Tried this:
```sh
csvsort -c 1 -I input.csv
```

However, quite expected the sorting is no longer numerical.
```csv
id,date,boolean
5009,2021-06-08 15:09:11,true
515,2020-11-08 15:09:11,false
```

How do I keep the numerical sort but preserve the values that `--no-inference` gets me?

And.. as I was typing this up, this does what I want:
```sh
sort -t, -n input.csv
```

**Comment by brewingcode** [comment]
I ran into this same thing, the type inference is wrecking the output, BUT the type inference is required for sorting to infer numeric values. @niklaswallerstedt thanks for posting the `sort` version, I just ended up re-ordering my csv columns so that the field I wanted to sort by was first, and `sort -nt,` did the job. Bummer that `csvsort` couldn't do it.

**Comment by niklaswallerstedt** [comment]
@brewingcode I'm glad I could help.

I saw this mentioned in the docs

> If your file is large, try sort -t, file.csv instead.

but I agree it would be great to be able to pass `--numerical` in conjunction with `-I` (`-n` is already in use) or something similar to preserve the output.

**Comment by jpmckinney** [comment]
I think we would need to be able to enable inference on only specific columns, which is the topic of #151. Adding something like `--numerical` would essentially be the same thing. #151 has the advantage of building on existing code.

Closing in favor of #151.
