### ISSUE TITLE
Upstream PyICU dep prevents installation on Heroku

### ISSUE THREAD

**Issue by palewire** [wireservice/csvkit#1127]
As documented here

https://gitlab.pyicu.org/main/pyicu/-/issues/150

I've seen the same bug myself when installing csvkit on heroku. It might be beyond the scope of what maintainers here can take on, but a package of csvkit and agate that did not rely on PyICU, or that made it optional, would be appreciated. From reading the thread above, it does not sound like a fix will arrive anytime soon. That leaves your package very difficult to use on Heroku and some other platforms.

**Comment by jpmckinney** [comment]
Hmm, well Heroku making it hard to install packages isn't necessarily csvkit's problem. Have you tried using heroku-buildpack-apt to install the ICU package?

https://stackoverflow.com/questions/31975668/installation-of-pyicu-on-heroku/32022933#32022933

**Comment by palewire** [comment]
I agree it's def. not your fault or problem. The apt fix doesn't work sadly. In the time since, I have a found a work around, with this ugly Pipfile hack. The fake platform will cause your computer to skip PyICU, and then your program appears to fail to import it gracefully and work well, as far as I can tell.

```
[packages]
csvkit = "*"
PyICU = {version = "*", markers="sys_platform == 'foobar'"}apscheduler = "*"
```

I don't expect you guys to rush to fix this, but I will log this patch here for future bug hunters. Thank you.

**Comment by jpmckinney** [comment]
After looking into it more, `parsedatetime` already has fallback behavior if PyICU isn't available, so it is not strictly required by agate. I've made it optional on agate's HEAD. If you report that it works, I can make a release.
