### ISSUE TITLE
[SOLVED] String "NA" is treated as EMPTY when converting from XLSX with in2csv

### ISSUE THREAD

**Issue by LaazV** [wireservice/csvkit#1134]
**edit:**

Solved using `--blanks` flag. The documentation at ReadTheDocs is not up to date with the latest version of csvkit. I was trying to fix it in the source and found the flag there. Gonna try to send a pull request later updating the docs file if that's ok. 

Hello, 
I noticed in my routine that any cell that has its contents equal to` NA` in Excel is interpreted as being empty when converting to csv using in2csv. It doesn't matter if the formatting is specified in Excel as "general", "text", "number", or any other format and neither adding a single quote before the text in excel does the trick. Also, using the flag `--no-inference` also has no impact on the output. 

Also, saving as CSV within Excel correctly parses the file and the output includes all strings as the original XLSX. The string disappears only when converting with csvkit's in2csv.

**Enviroment:**
```
O:\>systeminfo
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042

O:\>python --version
Python 3.9.6

O:\>in2csv --version
in2csv 1.0.6
```

**Example**

1. Create a new Excel file and add random values to cells with a few being "NA" (attachment [b.xlsx](https://github.com/wireservice/csvkit/files/7007687/b.xlsx))

| A    | B    | C    | D      | E    | F    | G    |
| ---- | ---- | ---- | ------ | ---- | ---- | ---- |
| 13   | 4    | 234  | 234231 | na   | 43   | na   |
| NA   | ASA  | NA   | 4      | 423  | 423  | na   |
| NA   | 34   | NL   | 4      | 432  | 23   | na   |
| na   | 3    | NB   | 4      | 234  | 4    | 243  |
| a    | na   | NA   | na     | na   | 2314 | 2143 |

2. Save it and run the command
`in2csv b.xlsx -e iso-8859-1 --no-inference --verbose`

3. Received output
```
A,B,C,D,E,F,G
13,4,234,234231,,43,
,ASA,,4,423,423,
,34,NL,4,432,23,
,3,NB,4,234,4,243
a,,,,,2314,2143
```
4. Expected output
```
A,B,C,D,E,F,G
13,4,234,234231,na,43,na
NA,ASA,NA,4,423,423,na
NA,34,NL,4,432,23,na
na,3,NB,4,234,4,243
a,na,NA,na,na,2314,2143
```

Is this the intended behavior? If so, is there a way to work around this and get the exact value in the cell? 
I also included another excel file ([a.xlsx](https://github.com/wireservice/csvkit/files/7007696/a.xlsx)) which includes a few cells from real world use, just as another example.

**Edit:**

Behavior is the exact same on Debian with python 2.7

```
in2csv --version
in2csv 1.0.6

python --version
Python 2.7.16

cat /etc/debian_version
10.10
```

**Comment by jpmckinney** [comment]
I think it's up-to-date: https://csvkit.readthedocs.io/en/latest/common_arguments.html

On https://csvkit.readthedocs.io/en/latest/scripts/in2csv.html it says

> See also: Arguments common to all tools. [linked]
