### ISSUE TITLE
csvsql --db argument trouble connecting to PostgreSQL

### ISSUE THREAD

**Issue by frafra** [wireservice/csvkit#1135]
I used the very same example provided by the documentation, but csvsql tries to connect to a Unix domain socket all the times, no matter what is the value of the argument of the `--db` option.

```
$ csvsql --db postgresql:///database --insert data.csv
/home/francesco.frassinell/.local/pipx/venvs/csvkit/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
OperationalError: (psycopg2.OperationalError) could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
$ csvsql --version
csvsql 1.0.6
```

**Comment by LaazV** [comment]
Not at all my domain, but I had similar issues before with postgre. Did you install it from from source? if so the default path is /tmp/ and csvsql is trying to reach it in /var/.

**Comment by frafra** [comment]
> Not at all my domain, but I had similar issues before with postgre. Did you install it from from source? if so the default path is /tmp/ and csvsql is trying to reach it in /var/.

That could be an issue if you try to connect over a Unix socket, while in this case I used a hostname, to establish a connection over TCP. `psql` without arguments try to connect over a Unix socket, but if you use ` psql -h database` it uses TCP.

**Comment by jpmckinney** [comment]
We are using SQLAlchemy's [create_engine](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine). CSV Kit has no knowledge of Unix sockets or TCP.

**Comment by jpmckinney** [comment]
You might try `postgresql://localhost/database`
