### ISSUE TITLE
csvgrep -m "multiple" 

### ISSUE THREAD

**Issue by tb582** [wireservice/csvkit#1136]
Looking at the docs for csvgrep https://csvkit.readthedocs.io/en/1.0.2/scripts/csvgrep.html

I don't inherently see a way to search for multiple strings? Am I missing something?

`csvgrep -c 1 -m "test" -m " test2" file.csv | csvlook | less -s`

**Comment by tb582** [comment]
Kinda figured out a hack solution using regex:

(?:^|W)thing1|thing2|something else(?:$|\W)

**Comment by jpmckinney** [comment]
Yes, the way to search multiple strings is to use a regex. Typically `one|two|three` and if you want to match word boundaries `\b(one|two|three)\b`, or if you want to match only exact strings then `^(one|two|three)$`.
