### ISSUE TITLE
heterogeous headers in csvstack 

### ISSUE THREAD

**Issue by fgregg** [wireservice/csvkit#1141]
i often am writing a little script like this to handle combing data with fields that largely overlap, but do not completely overlap

```
input_filename_list
headers = set()
for file in input_filename_list:
     with open(filename) as f:
         reader = csv.DictReader(f)
         header.update(reader.fieldnames)

writer = csv.DictWriter(sys.stdout, fieldnames=header, extrasaction='ignore')
writer.writeheader()

for file in input_filename_list:
     with open(filename) as f:
         reader = csv.DictReader(f)
         for row in reader:
             writer.writerow(row)
```

Would you be interested in having this as a flag to csvstack? Would also address #245

**Comment by jpmckinney** [comment]
Yes, if you can fix #245, that'd be great! Closing in favor of that issue.

**Comment by fgregg** [comment]
i thought #245 was a narrower issue, sorry for the noise.

**Comment by jpmckinney** [comment]
I think they can be solved the same way, but if there's a difference, I'm happy to merge a PR that addresses heterogenous columns but not disordered columns.
