### ISSUE TITLE
Alternative way of data ingestion

### ISSUE THREAD

**Issue by nikita2206** [wireservice/csvkit#1149]
I've seen a few issues in the past about not being able to set up csvkit with brew on MacOS but they seem to have been solved. However their solutions don't work for me and would it be better to support an easier way of installation of csvkit?

Specifically for me what doesn't work is that Python doesn't find the necessary MySQL driver, even after installing it. I suspect it just can't find the relevant library (doesn't know where to look for it maybe). 

I understand that this is a problem of both dynamic linking (with the native MySQL driver/library) and finding correct libraries (Pything seems to be horrible at doing this). Plus, as someone who's never used Python I find its DB connection string syntax completely alien, in fact even JDBC syntax (as a user of JDBC) is alien too, I'm a lot more comfortable with MySQL's CLI client's options (`-h -u -p -P`) but users of let's say PostgreSQL might be more comfortable with psql's options (`-h -U -W -p`), and implementing all these in a single tool like csvkit would be doable but hard and there'd be lots of edge cases.  
How about instead sql2csv would allow us to pipe `mysql ... -e 'SELECT * FROM tbl'` to it? You can't programmatically read that format in 100% of cases because it heavily relies on tab formatting but it could work for the majority, I'd wager that people would mostly use sql2csv for numbers anyway and not for textual tables.

**Comment by jpmckinney** [comment]
Most popular SQL dialects allow exporting data to CSV files, so you should just do that if you prefer to using the specific database's commands. `csvkit` doesn't need to provide a copy of that functionality.


https://dev.mysql.com/doc/refman/8.0/en/mysqldump-delimited-text.html
https://www.postgresql.org/docs/9.2/sql-copy.html
etc.
