### ISSUE TITLE
(Csvsql) Encoding argument not working for stdin

### ISSUE THREAD

**Issue by Glupschauge** [wireservice/csvkit#1150]
Hi,
When using csvsql and piping the content from a windows-1252 encoded file into the stdin of csvsql the encoding is not used correctly. 

### Example:
**Command:**
`cat test_win1252.csv | csvsql --query "select data2 from stdin" -e windows-1252 -d ";" -v` 

**Output:**
`Traceback (most recent call last):
  File "/usr/bin/csvsql", line 11, in <module>
    load_entry_point('csvkit==1.0.6', 'console_scripts', 'csvsql')()
  File "/usr/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 248, in launch_new_instance
    utility.run()
  File "/usr/lib/python3.6/site-packages/csvkit/cli.py", line 118, in run
    self.main()
  File "/usr/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 142, in main
    self._failsafe_main()
  File "/usr/lib/python3.6/site-packages/csvkit/utilities/csvsql.py", line 177, in _failsafe_main
    **self.reader_kwargs
  File "/usr/lib/python3.6/site-packages/agate/table/from_csv.py", line 69, in from_csv
    contents = six.StringIO(f.read())
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 25: invalid continuation byte
`

It shows that stdin is read via the utf-8 encoding. 

### TestData:
My testfile (Cant upload because of company policy)
`data1;data2;data3;data4
jährlich;monatlich;täglich;asdhdf`
Encoded in win-1252 and windows lineending(CRLF)

### Workaround:
Set environment variable "PYTHONIOENCODING=windows-1252"
`cat test_win1252.csv | PYTHONIOENCODING=windows-1252 csvsql --query "select data2 from stdin" -e windows-1252 -d ";" -v` 

In version 1.0.5 it was the opposite. Argument was working but not environment variable.

**Comment by jpmckinney** [comment]
In this case, csvkit is reading `sys.stdin` whose encoding in Python 3 is controlled by `PYTHONIOENCODING`.

`-e` only has an effect on the CSV *file*, and in this case there is no file being opened by Python.

The other thing you can do is instead of piping with `cat`, just pass the filename as a positional argument.

I've added a note to the documentation.
