### ISSUE TITLE
Feature request: Option for delimited data in Excel cell

### ISSUE THREAD

**Issue by abalter** [wireservice/csvkit#1153]
It's common (whether good practice or not) to have delimited lists in Excel cells. Something like this:

`people_pets.xlsx`
------------
| Person   | Pets             |
|----------|------------------|
| Ahmad    | Simba, Mushu     |
| Rosita   | Paco, Bubblehead |
| Shulamit | Coleslaw, Tali   |
------------

In my case it's something more practical like gene names or alternative names of a drug.

Many databases these days allow ["nested" data "repeated" data][1] or "record data type" These can be entire tables, etc. 

For the simple case where the "record" or "nested data" is just a list, how about an option like `--nesting-delimiter`? 

Quick point: In TSV files, records can be comma-delimited. In CSV files they need a different delimiter.

[1]: https://www.kaggle.com/alexisbcook/nested-and-repeated-data

**Comment by jpmckinney** [comment]
Sorry, this would be a major feature (in terms of effort), and csvkit's feature set is essentially frozen.

**Comment by jpmckinney** [comment]
@abalter After converting the Excel to CSV (e.g. with CSV Kit), you can use qsv's explode command: https://github.com/jqnatividad/qsv
