### ISSUE TITLE
Replace slash "/" by a more sql friendly character?

### ISSUE THREAD

**Issue by mardub1635** [wireservice/csvkit#1154]
Hi,
when using in2csv to generate csv from json files, the default behaviour is to use slash "/" to make subcategories:
Below an example of name in a csv generated by in2csv:
**author/avatar** | **author/name** | id | numReplies

Now if I want to use csvsql to get "author/name" I get an error message
![image](https://user-images.githubusercontent.com/13570586/144494132-99402dc3-ca67-4303-a71b-422b1b76a602.png)

sql does not like slashes "/" in name field...

It took me a while to figure out how to escape "/" in sql. One can indeed use [author/name] and then it will work. 
So can we apply any of the following fixe:
- Either make sure in2csv does not use "/" in the naming for subcategories? For instance using underscore or "." or any character that would be more sql friendly?
- Either add a similar example in the documentation so that people are not confused like I was?

**Comment by jpmckinney** [comment]
I've added an example to the documentation. Changing the column naming now would break a lot of data pipelines.
