### ISSUE TITLE
in2csv empty result

### ISSUE THREAD

**Issue by adrianmihalko** [wireservice/csvkit#1155]
I would like to convert this XLSX file:

https://www.telekom.sk/docs/updates/ins/Zoznam_planovanych_lokalit.xlsx

```
$ in2csv Zoznam_planovanych_lokalit.xlsx > zoznam.csv
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
Row 0 has 11 values, but Table only has 1 columns.
```

The result is an empty file.

**Comment by jpmckinney** [comment]
The first row in the Excel file is non-data "Report uložený: 4.3.2022"

You can use `--skip-lines` to skip it.

```
in2csv -K1 Zoznam_planovanych_lokalit.xlsx
```

I've added a note about this to the docs for `in2csv`.
