### ISSUE TITLE
How to use in2csv in a py file

### ISSUE THREAD

**Issue by aqqwvfbukn** [wireservice/csvkit#1157]
How do I not use in2csv on the command line, like in2csv ne_1033_data.xlsx > data.csv
I have several XLSX files that I want to convert to CSV format and want to batch use in2CSV in one PY file,

def convert(inputfile,outputfile):
    ...........
    ............

I would be grateful if anyone could give me an example

**Comment by aitoehigie** [comment]
You can use the subprocess module to call in2csv. Use subprocess.run for Python 3.5+

import subprocess
def convert(inputfile, outputfile):
    output = subprocess.run(['in2csv', 'ne_1033_data.xlsx'], universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    with open(outputfile, 'w') as file:
        file.write(output.stdout)

**Comment by jpmckinney** [comment]
`in2csv` mostly uses the agate Python package. https://agate.readthedocs.io/en/latest/

For XLSX, it uses agate-excel: https://agate-excel.readthedocs.io/en/latest/

You can use those directly.
