### ISSUE TITLE
Add non-CSV output

### ISSUE THREAD

**Issue by tewe** [wireservice/csvkit#1162]
I have single-column CSV with quoting and escaping. As there are no newlines in the values, it is safe to remove both quoting and escaping. But I found no way to do it, except using `csvpy`.

```python
for r in reader:
    print(r[0])
```

Please consider adding this to e.g. `csvformat`.

**Comment by jpmckinney** [comment]
Indeed, `--out-quoting 3` (Quote None) yields `Error: need to escape, but no escapechar set`, and `--out-escapechar` cannot be empty. That said, `csvkit`'s scope is to only output CSV, so this issue is wontfix.

**Comment by tewe** [comment]
Thanks for clarifying.
