### ISSUE TITLE
in2csv,  XXXXD is interpreted as a Duration

### ISSUE THREAD

**Issue by jmari** [wireservice/csvkit#1173]
I have a column for a Product ID and its format is [0,9]*D i.e. 0606D, 0170D,... this column is interpreted as a Duration so the output is "606 days, 0:00:00", "170 days, 0:00:00" how can I "force" to take these values as String? I've tried to put a single quote in the excel file '0606D but no way ...

**Comment by jpmckinney** [comment]
Use `--no-inference`.
