### ISSUE TITLE
Donation possibility

### ISSUE THREAD

**Issue by RichardLitt** [wireservice/csvkit#1174]
I don't have any technical feedback to leave, and I don't feel that looking for a low-hanging fruit to make a PR for is something I would like to do right now. However, I would like to show appreciation. 

Is there a way I can donate to this project? Are there any standing costs that I can help cover? 

Thank you.

**Comment by jpmckinney** [comment]
Thank you for the offer, @RichardLitt ! We don't presently have an option, but we'll consider it and re-open this issue if we arrive at a good option with low overhead.
