### ISSUE TITLE
csvstat: Add option to remove thousands separator

### ISSUE THREAD

**Issue by slhck** [wireservice/csvkit#1179]
`csvstat` is great for quickly summarizing data! However, its default output format is not machine-readable, in the sense that it includes thousands separators. These (sometimes) cannot be easily considered when further processing the data.

```
$ csvstat -t logs/encode-x264-16-1080-jobs.log -c JobRuntime --sum 
2,669.973
```

Would it make sense to make the grouping argument optional here (maybe `--no-decimal-grouping`/`--no-thousands-separator` or something to preserve the default)?

https://github.com/wireservice/csvkit/blob/bb34039742b0e91ce9cc26039c4292ec258fcdd1/csvkit/utilities/csvstat.py#L348-L349

Or maybe allow the user to specify via format strings how they want numbers to be printed?

**Comment by slhck** [comment]
Example where basic tools cannot parse the output:

```
$ echo "$(csvstat -t logs/encode-x264-16-1080-jobs.log -c JobRuntime --sum) / 60" | bc
(standard_in) 1: syntax error

$ echo "$(csvstat -t logs/encode-x264-16-1080-jobs.log -c JobRuntime --sum | tr -d ',') / 60" | bc
44
```

**Comment by slhck** [comment]
Ah, I didn't know that. In that case it would definitely make sense to have the same feature in csvstat.

**Comment by slhck** [comment]
In my example implementation, this would work:

```
➜ python3 -m csvkit.utilities.csvstat examples/realdata/FY09_EDU_Recipients_by_State.csv -c TOTAL --decimal-format '%.2f' --no-thousands-grouping
/Users/werner/.pyenv/versions/3.10.0/lib/python3.10/site-packages/agate/utils.py:285: UnnamedColumnWarning: Column 9 has no name. Using "j".
  9. "TOTAL"

        Type of data:          Number
        Contains null values:  True (excluded from calculations)
        Unique values:         53
        Smallest value:        768.00
        Largest value:         46897.00
        Sum:                   506914.00
        Mean:                  9748.35
        Median:                6520.00
        StDev:                 10168.65
        Most common values:    12426.00 (1x)
                               1158.00 (1x)
                               33986.00 (1x)
                               5513.00 (1x)
                               46897.00 (1x)
```

Should I provide a PR?

**Comment by timtomch** [comment]
I like the ability to specify the decimal format. And I see why implementing `-I/--no-inference` would not necessarily work for csvstat since we want to infer numerical values in order to calculate stats.

I wonder if instead of `--no-thousands-grouping`, we could toggle which [locale](https://docs.python.org/3/library/locale.html) to use to represent the thousands sep but I'm not quite sure how this would work...

**Comment by slhck** [comment]
This is not possible because the `format_string` method takes a dedicated `grouping` option. I personally would prefer to have grouping disabled by default, and enabled on request — it would also not be a breaking change.

**Comment by jpmckinney** [comment]
Thank you for the PR! I'll try to get to it.
