### ISSUE TITLE
csvsql does not work with simple csv file

### ISSUE THREAD

**Issue by kim-fehl** [wireservice/csvkit#1188]
Command:
`csvsql --query 'select *  from Quality_Metrics' Quality_Metrics.csv `
Output:
`TypeError: create() missing 1 required positional argument: 'bind'`

Python version: 3.9.14 
csvkit versions tested: 1.0.7, 1.0.6

Head of csv file:
```
Lane,SampleID,index,index2,ReadNumber,Yield,YieldQ30,QualityScoreSum,Mean Quality Score (PF),% Q30
1,WG5021,ATTACTCG,ATAGAGGC,1,54978,49075,1881350,34.22,0.89
1,WG5021,ATTACTCG,ATAGAGGC,2,270578,137683,7147328,26.42,0.51
1,MK4575,ATTACTCG,CCTATCCT,1,45441,40885,1562737,34.39,0.90
1,MK4575,ATTACTCG,CCTATCCT,2,223641,123754,6114325,27.34,0.55
```

**Comment by jpmckinney** [comment]
When I run that command with the snippet of the file you shared, I don't get any error.

Can you share a segment of the file that does error?

**Comment by jpmckinney** [comment]
Yes, SQLAlchemy 2.0 (released recently) has breaking changes. You'll need to pin to `<2`. I'll make a release declaring this in csvkit.

**Comment by jpmckinney** [comment]
Done - you'll have to upgrade agate-sql to 0.5.9.
