### ISSUE TITLE
SQLAlchemy 2.0 breaks sql2csv (maybe other stuff, too?)

### ISSUE THREAD

**Issue by dwillis** [wireservice/csvkit#1191]
Per the [migration guide](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html):

```
The connection.execute() method in SQLAlchemy 2.0 will accept parameters as a single dictionary or a single sequence of dictionaries only."
```

Which means running a command like: 

`sql2csv --db mysql://foo:bar@127.0.0.1/mydb  --query "select * from mytable where name like '%donkey%'"`

Gives you an `ObjectNotExecutableError: Not an executable object` error.

**Comment by maaaaz** [comment]
Hello there,

I don't know if it has the same root cause, but **csvkit** also gives me this warning related to **SQLAlchemy**:
```
$ wget https://github.com/maaaaz/red.flag.domains-publications/raw/main/2023/02/2023-02-18.csv

$ csvsql -u 1 2023-02-17.csv --tables db --query 'SELECT fqdn FROM db WHERE ip IS NOT NULL' 
root/venvs/venvtest/lib/python3.11/site-packages/agatesql/table.py:183: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```


Here are the versions I use:
```
(venvtest) root@kali:/tmp# cat /etc/issue
Kali GNU/Linux Rolling \n \l

(venvtest) root@kali:/tmp# uname -mrs
Linux 6.0.0-kali6-amd64 x86_64

(venvtest) root@kali:/tmp# python -V
Python 3.11.1

(venvtest) root@kali:/tmp# pip freeze
agate==1.7.1
agate-dbf==0.2.2
agate-excel==0.2.5
agate-sql==0.5.9
Babel==2.11.0
beautifulsoup4==4.11.2
certifi==2022.12.7
charset-normalizer==3.0.1
click==8.1.3
csvkit==1.1.0
cymruwhois==1.6
dbfread==2.0.7
et-xmlfile==1.1.0
greenlet==2.0.2
idna==3.4
isodate==0.6.1
leather==0.3.4
lxml==4.9.2
olefile==0.46
openpyxl==3.1.1
parsedatetime==2.6
python-slugify==8.0.0
pytimeparse==1.1.8
pytz==2022.7.1
requests==2.28.2
six==1.16.0
soupsieve==2.4
SQLAlchemy==1.4.46
text-unidecode==1.3
urllib3==1.26.14
waybackpy==3.0.6
xlrd==2.0.1
```

**Comment by jpmckinney** [comment]
@dwillis Fix is to upgrade to `agate-sql==0.5.9` (or downgrade `SQLAlchemy<2` - same outcome).

@maaaaz If you don't like SQLAlchemy's aggressive warning, set `SQLALCHEMY_SILENCE_UBER_WARNING=1` as instructed in their message.

**Comment by maaaaz** [comment]
@jpmckinney, thanks ! Instead of masking the message, is there a way to use non-deprecated functions ?

**Comment by jpmckinney** [comment]
Sure, if anyone wants to write the PR to https://github.com/wireservice/agate-excel

For whatever reason, SQLAlchemy [added a deprecation in 1.4.46](https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-1.4.46), which is an extremely late release in the 1.4 series. The typical way of doing things is to deprecate in a NEW minor version – NOT in a super late patch version.
