### ISSUE TITLE
Update documentation to use the built-in function `next()`

### ISSUE THREAD

**Issue by LKirst** [wireservice/csvkit#1204]
Should the example in the documentation of csvpy use the built-in function `next()` instead of the `reader.next()` method because most users will be using Python 3?

<https://github.com/wireservice/csvkit/blob/da9c04c1cd882d013e79575cc4c5f7de18f6babd/docs/scripts/csvpy.rst?plain=1#L47>

**Comment by jpmckinney** [comment]
Good call - thanks!
