### ISSUE TITLE
How to utilize all available Cores with csvsql?

### ISSUE THREAD

**Issue by Gill-Bates** [wireservice/csvkit#1205]
I have a big CSV-File (150 MB) which I want to import into Postgres. When I run csvsql, I can see, that the tool is not using all available cores:

![image](https://github.com/wireservice/csvkit/assets/25774289/bb215f9b-ab0e-4717-985e-79ee8ed0962d)

Is there a trick how I can control csvsql to use all cores?

```
./csvsql -V
`csvsql 1.1.1`
```

```
uname -a
inux vmgrafana 6.1.0-11-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux
```

```
./python -V
Python 3.11.2
```

**Comment by jpmckinney** [comment]
I don't see much opportunity to use multiprocessing in csvsql – especially for an import. Where would it thread?

If you want the fastest import, just use COPY. https://www.postgresql.org/docs/current/sql-copy.html

**Comment by jpmckinney** [comment]
Closing as no response.
