### ISSUE TITLE
csvsql: Catch empty CSV files

### ISSUE THREAD

**Issue by Gill-Bates** [wireservice/csvkit#1206]
Due to an export error I exported a 0 byte CSV. However, I did not notice this. Logically the import via `csvsql` failed.

The issued error message `"Could not determine delimeter"` is correct, but very confusing. It took me an hour to find the error.

Therefore my suggestion: couldn't csvkit check the file to be processed for existing content beforehand and then abort the process. For example with the error message `"Provided CSV file is empty."` ?

**Comment by jpmckinney** [comment]
```console
$ echo "" | csvsql
agate/table/from_csv.py:67: RuntimeWarning: Error sniffing CSV dialect: Could not determine delimiter
```

This is just a warning, not an error (`RuntimeWarning`).

We could write to standard error and return an error code if files are empty – but in some cases it's planned for a pipeline to yield empty input (e.g. a process that updates a database with new records could something not have any new records).

So, I'll close for now, unless others frequently run into the same issue.
