### ISSUE TITLE
make csvlook fail with errcode > 0 when header and table have mismatched number of columns

### ISSUE THREAD

**Issue by gl-yziquel** [wireservice/csvkit#1210]
Currently, when a csv file has a mismatched header with a different number of values from the number of columns in the csv table, the program fails with

```console
ValueError: Row 0 has 12 values, but Table only has 8 columns.
```

However, it does not exit with an error code. As I am scripting this from a command runner, I'd appreciate a nonzero error code being returned to the shell.

**Comment by gl-yziquel** [comment]
Suggested PR: https://github.com/wireservice/csvkit/pull/1211

**Comment by jpmckinney** [comment]
> However, it does not exit with an error code.

It does for me?

```console
$ csvlook examples/bad.csv
ValueError: Row 0 has 4 values, but Table only has 3 columns.
$ echo $?
1 
```
