### ISSUE TITLE
csvjoin question or issue

### ISSUE THREAD

**Issue by wiluite** [wireservice/csvkit#1213]
`csvjoin --version`
1.0.2
`python3 --version`
Python 3.7.3

Or
`csvjoin --version`
1.1.1

AS WELL
                
So, the question is: should we wait the same results on (the following)(or all) "SYMMETRIC" commands, or could you comment the results in the latest 2 cases (shouldn't they match?).

`csvjoin join_b.csv join_a.csv -c 2,1 --left`
b1,b2,a2
True,Hey,

`csvjoin join_a.csv join_b.csv -c 1,2 --right`
b1,b2,a1
True,Hey,

Well, now with type ignorance:

`csvjoin join_b.csv join_a.csv -c 2,1 --left -I`
b1,b2,a2
1,Hey,

`csvjoin join_a.csv join_b.csv -c 1,2 --right -I`
b1,b2,a1
1,Hey,**1**

_Files_:

join_a.csv

> a1,a2
> 1,1
> 1,c

join_b.csv

> b1,b2
> 1,"Hey"

Thank you!

**Comment by jpmckinney** [comment]
This was indeed a bug. Thank you!
