### ISSUE TITLE
Would like to be able to force the type of columns in csv file when using csvsql

### ISSUE THREAD

**Issue by ChenglimEar** [wireservice/csvkit#1220]
The underlying agate library supports a `force` option where the types can be explicitly set for the columns.  I'm hoping we can expose that capability in csvsql.  Ideally, the types can be provided using the SQL that was created by csvsql when inference is turned on.  This SQL can then be manually manipulated for the columns where the inference is wrong and fed back into csvsql for subsequent runs.

**Comment by jpmckinney** [comment]
Duplicate #151. Happy to receive any pull requests!
