### ISSUE TITLE
Specify which in-memory SQL database is created when querying CSV files directly

### ISSUE THREAD

**Issue by zachsa** [wireservice/csvkit#1222]
>You can also use CSVSQL to “directly” query one or more CSV files. Please note that this will create an in-memory SQL database, so it won’t be very fast:

I assume that this is SQLite, and that I can therefore refer to SQLite documentation for query syntax / etc?

Thanks for this library

**Comment by jpmckinney** [comment]
Yes. Documentation has now been updated. Thank you for reporting!
