### ISSUE TITLE
BadZipFile when using -f xlsx --write-sheets - on STDIN

### ISSUE THREAD

**Issue by Konfekt** [wireservice/csvkit#1225]
Running `cat file.xlsx | in2csv -f xlsx --write-sheets -` throws `BadZipFile: File is not a zip file`. Maybe https://stackoverflow.com/a/76780830/2241241 is of interest, as https://github.com/dilshod/xlsx2csv used it to implement  reading from STDIN and works fine with `--all`, analogous to `--write-sheets -`.

**Comment by jpmckinney** [comment]
Thank you for reporting!

Fixed in 88753f9

The problem was that we were reading stdin twice (once for the data, once for the sheet names), which fails.
