### ISSUE TITLE
csvlook: consider passing max_rows argument to agate.table.from_csv

### ISSUE THREAD

**Issue by morgan-dgk** [wireservice/csvkit#1230]
Hello,

Currently max_rows is not passed to the row_limit parameter for `agate.table.from_csv`. As a result, the entire contents of the input file file is read even if a user requests to render the first 100 rows only.  

Does this behaviour make sense? Why not just read the the number of rows of requested with agate?

**Comment by jpmckinney** [comment]
Ah, row_limit was added in 2021 and max_rows has existed a lot longer. But we can use it now!

Fixed in 7bba1bd
