### ISSUE TITLE
csvformat: add command-line option for output in ASV, i.e. ascii unit separator

### ISSUE THREAD

**Issue by vmchale** [wireservice/csvkit#1232]
Right now, if I'd like to convert csv to [ASV](https://metacpan.org/pod/Text::Table::ASV), I need to input the ascii unit separaator in my shell:

```
csvformat -D$'\x1f'
```

...which is a bit of a pain. A `--asv` flag, like `--out-tabs`, would be quite nice.

**Comment by jpmckinney** [comment]
ASV would also imply using `\x1e` as the record separator. Is that your intention?
