### ISSUE TITLE
Include man pages in PyPI package tarballs?

### ISSUE THREAD

**Issue by vergenzt** [wireservice/csvkit#1234]
Hi - would you be open to the man pages being included in the built barballs distributed to PyPI?

Followup from #15, #1104 

My ultimate goal is for the man pages to be accessible. I find myself regularly frustrated when using `csvkit` because I can't quickly lookup the man page for a command without clearing out my current shell pipeline to call `<tool> --help`. (My shell [has a keyboard shortcut](https://fishshell.com/docs/current/interactive.html#:~:text=Alt%2BH%20(or%20F1)%20shows%20the%20manual%20page%20for%20the%20current%20command%2C%20if%20one%20exists.) to pull up the man page for the command under cursor without clearing the command buffer.)

I do agree with your previous sentiment that the maintainers of this package cannot be responsible for making sure the man pages _end up_ in the right place. **However I think it _would_ be reasonable for this package to be responsible for _building_ its man pages.** Could this package's build script(s) _generate_ the man pages and include them in tarballs uploaded to PyPI? That would greatly simplify distribution maintainers' jobs from "`python -m venv .venv && .venv/bin/pip install docs/requirements.txt && PATH=.venv/bin:$PATH make -C docs man && cp docs/_build/man/* ...`" (which, to my knowledge, no one does currently because it's non-trivial) to simply "`cp docs/_build/man/* ...`" (which would be _very_ easy to add).

Would you be open to reviewing & merging a PR to this effect?

**Comment by jpmckinney** [comment]
Thank you!

**Comment by vergenzt** [comment]
When do you think a release which includes #1235 could be cut? I'd love to update https://github.com/Homebrew/homebrew-core/blob/master/Formula/c/csvkit.rb to install these whenever that happens. 🙂

**Comment by vergenzt** [comment]
Awesome! Thanks! 🙂 Unfortunately it turned out my change only got the manual pages included in _sdist_s and not in wheels (the latter of which are the default for installs). Filed #1236 to resolve this! THEN I can finally update the Homebrew formula!

**Comment by vergenzt** [comment]
PR to link the man pages in Homebrew formula is here: https://github.com/Homebrew/homebrew-core/pull/192380
