### ISSUE TITLE
Keying for GeoJSON.

### ISSUE THREAD

**Issue by wiluite** [wireservice/csvkit#1250]
Just a question.

csvjson says that _--key is only allowed with --stream when --lat and --lon are also specified._
But as a matter of fact no difference in output if (--stream, --lon, --lat ) and (--key, --stream, --lon, --lat) specified.

Is this for the future versions?

**Comment by jpmckinney** [comment]
Can you provide full sample commands, ideally with sample data?

**Comment by jpmckinney** [comment]
No answer. Closing.
