### ISSUE TITLE
Custom delimiter for grouping option

### ISSUE THREAD

**Issue by lukaspirpamer** [wireservice/csvkit#1253]
When the grouping option is enabled, "," is used as a field delimiter and the delimiter of the input csv file is ignored.  
Would it be possible to use the automatically determined delimiter or delimiter of the csv-input file?

https://github.com/wireservice/csvkit/blob/f73742fc0ec4c993b5f76809ee15dfab8a0cef10/csvkit/utilities/csvstack.py#L50

**Comment by jpmckinney** [comment]
Why?

**Comment by lukaspirpamer** [comment]
Hi James, 
thanks for your prompt reply!

Because the grouping option converts the delimiter to be "," 
For example, when using csvstack and the delimiter is ";" in the input csv files, in the output file it will be converted to "," when the grouping option is applied. I would have expected the same behaviour as without using the grouping option. What do you think?

Best,
Lukas

**Comment by jpmckinney** [comment]
Basically, if you are currently doing `csvstack a.csv lot.csv of.csv files.csv that.csv use.csv semicolons.csv`, then you are effectively doing the same as `cat ...`. csvstack doesn't recognize the semicolons as delimiters, unless you use `-d` (in which case, the output will use commas, as described above).
