### ISSUE TITLE
sql2csv : Memory issue : process finished with exit code 137

### ISSUE THREAD

**Issue by Philaaadata** [wireservice/csvkit#1255]
We have error 137 when using sql2csv after an hour, the output file is empty.
Version : 2.0.0
Export table : 105 million rows on 67 columns: 50 Go
cmdline : sql2csv --db 'mysql+pymysql://SERVER/DATABASE?charset=utf8&read_default_file=~/.my.cnf&read_default_group=Clientcsvkit' --query "SELECT * FROM TABLE ORDER BY KEY" > /data/export/file.csv

Is the export result put in a buffer rather than sending it to standard output line by line?

**Comment by jpmckinney** [comment]
Thanks for looking into it @sgpeter1 ! If we're not confident in adding it for all queries, we can do something like the new `--engine-options`, to allow setting `stream_results True` via the command-line.

**Comment by Philaaadata** [comment]
@sgpeter1 @jpmckinney 

Thank you for the feedback,

There is a complete example : https://docs.sqlalchemy.org/en/20/_modules/examples/performance/large_resultsets.html

I will update the kit to version 2.0.1 and test the --engine-option option, I will get back to you

**Comment by Philaaadata** [comment]
When I add --engine-option stream_results True to commandline, I have this error : TypeError: Invalid argument(s) 'stream_results' sent to create_engine(), using configuration MySQLDialect_pymysql/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by jpmckinney** [comment]
Yes, it won't work with `--engine-option`. We would need to add something similar like `--execution-option`. In the meantime, can you test with @sgpeter1's fork?

**Comment by Philaaadata** [comment]
I tested the suggested modification... and it works... the file is streamed

Can you add --execution-option option ?

![image](https://github.com/user-attachments/assets/68e777cd-eb41-4050-8295-c7682c5aeae0)

**Comment by jpmckinney** [comment]
It looks like [stream_results](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection.execution_options.params.stream_results) should be a safe default, so I set it as the default behavior, and I also added `--execution-options`.
