### ISSUE TITLE
Unhelpful error messages without traceback in csvsql

### ISSUE THREAD

**Issue by clach04** [wireservice/csvkit#1260]
When an exception occurs, csvsql hides the traceback so there is no useful stacktrace or reference to start debugging from.

I don't understand the full code path, so I don't have a solution other than iteratively running in the debugger 😿 

An example of this is with bug https://github.com/wireservice/csvkit/issues/1258 the failure gives no hints on where to start debugging. This problem is not present in https://github.com/wireservice/agate-sql (triggering failure in agate-sql outside of csvkit results in regular backtrace).

**Comment by jpmckinney** [comment]
You have to use the `-v` (`--verbose`) option

> -v, --verbose         Print detailed tracebacks when errors occur.

I'll review the other issue separately.
