### ISSUE TITLE
csvclean dry run

### ISSUE THREAD

**Issue by erin-bristow** [wireservice/csvkit#1262]
Hi! I recently updated my csvkit version and I see that the dry-run option was removed in more recent versions. This was really useful for validating CSVs and getting a quick look at which line numbers had issues and the expected vs. found number of columns. Is there a way to replicate this old functionality in the current version or would you recommend reverting to the old version? Thanks!

**Comment by jpmckinney** [comment]
> which line numbers had issues and the expected vs. found number of columns

I don't see a change in behavior here?

```
$ csvclean -a examples/bad.csv 2>&1 >/dev/null
line_number,msg,column_a,column_b,column_c
1,"Expected 3 columns, found 4 columns",1,27,,I'm too long!
2,"Expected 3 columns, found 2 columns",,I'm too short!
```

csvclean now exits with status 1 (error) if there are errors to report. So, if you just want to know whether it exited cleanly or not, you can check the exit status. Like one of:

```
if [ csvclean -a examples/bad.csv ]; then echo "my message"; fi
[ csvclean -a examples/bad.csv ] && echo "my message"
csvclean -a examples/bad.csv >/dev/null 2>&1; echo $?
```

To count the number of errors reported, you can do this:

```
csvclean -a examples/bad.csv 2>&1 1>/dev/null | csvstat --count
```

That is, ignore standard output, redirect standard error to standard output, and count the number of rows.

**Comment by erin-bristow** [comment]
Ah much appreciated! Thanks for the examples
