### ISSUE TITLE
Cannot `csvgrep` columns containing hyphens

### ISSUE THREAD

**Issue by vectro** [wireservice/csvkit#1263]
If one attempts to use `csvgrep --columns` with columns whose names contain `-`, then we get the error message
```ColumnIdentifierError: Invalid range %s. Ranges must be two integers separated by a - or : character.```
This is true even if the columns names were quoted.

Tested using csvgrep 2.0.1.

**Comment by jpmckinney** [comment]
Basically the same issue as #468. You can use column indices in your case instead of names.
