### ISSUE TITLE
csvcut: enhance to allow a range of a start column to the last column

### ISSUE THREAD

**Issue by jbreazeale** [wireservice/csvkit#1264]
Please enhance csvcut so that a range in the -c option can specify the start column to the last column, similar to the Unix/Linux cut command's -f option in the N- form.  Example:

    csvkit -d',' -c 2-

The -c range means extract column 2 through the last column.

**Comment by jpmckinney** [comment]
But that does work?

```shell session
$ csvcut -c 1- examples/dummy.csv
a,b,c
1,2,3

$ csvcut -c 2- examples/dummy.csv
b,c
2,3

$ csvcut -c 3- examples/dummy.csv
c
3
```
