### ISSUE TITLE
Why does sorting show False instead of 0?

### ISSUE THREAD

**Issue by boxley-anaconda** [wireservice/csvkit#1265]
Contrasting:
```
$ head -5 Q4_K_M-perf.csv 
now.iso,core.log,core.phys,cpu.total,mem.used,mem.active,memswap.used
2024-10-07T16:23:23+00:00,16,16,61.0,2161037312,20167680000,0
2024-10-07T16:23:23+00:00,16,16,61.0,2161033216,20167806976,0
2024-10-07T16:23:24+00:00,16,16,61.0,2161033216,20168019968,0
2024-10-07T16:23:24+00:00,16,16,61.0,2161033216,20168019968,0
```
with:
```
$ csvsort -c memswap.used < <( head -5 Q4_K_M-perf.csv )
now.iso,core.log,core.phys,cpu.total,mem.used,mem.active,memswap.used
2024-10-07T16:23:23+00:00,16,16,61.0,2161037312,20167680000,False
2024-10-07T16:23:23+00:00,16,16,61.0,2161033216,20167806976,False
2024-10-07T16:23:24+00:00,16,16,61.0,2161033216,20168019968,False
2024-10-07T16:23:24+00:00,16,16,61.0,2161033216,20168019968,False
```

Why does the "memswap.used" column show up a "False" instead of "0"?

**Comment by jpmckinney** [comment]
It's doing type inference. Disable it with `--no-inference`.

**Comment by boxley-anaconda** [comment]
I found this in other cases as well. It seems to be whenever a column is all zeros.

**Comment by boxley-anaconda** [comment]
@jpmckinney Wow, that was unexpected. Your explanation makes sense.
Why isn't `--no-inference` the default? It violated my https://en.wikipedia.org/wiki/Principle_of_least_astonishment.

**Comment by jpmckinney** [comment]
The homepage [explains](https://csvkit.readthedocs.io/en/latest/):

> csvkit, by default, [sniffs](https://docs.python.org/3/library/csv.html#csv.Sniffer) CSV formats (it deduces whether commas, tabs or spaces delimit fields, for example) based on the first 1024 bytes, and performs type inference (it converts text to numbers, dates, booleans, etc.). These features are useful and work well in most cases, but occasional errors occur. If you don’t need these features, set --snifflimit 0 (-y 0) and --no-inference (-I).

Changing defaults would result in many more upset users, for whom the defaults work.

If a column is just 0 and 1, the type is inferred as boolean.
