### ISSUE TITLE
csvjoin - UnsupportedOperation: underlying stream is not seekable

### ISSUE THREAD

**Issue by csawatzkyST** [wireservice/csvkit#1268]
I recently updated from csvkit 1.1.1 in Fedora 40 to csvkit 2.0.0 in F41.

I used to be able to use [process substitution](https://www.gnu.org/software/bash/manual/bash.html#Process-Substitution) from two commands to redirect output to `csvjoin`.  Now I am getting the errror, "UnsupportedOperation: underlying stream is not seekable".

See: https://csvkit.readthedocs.io/en/latest/tricks.html#specifying-stdin-as-a-file

Example: 
```
$ csvjoin -c C <(echo "A,B,C") <(echo "C,D,E") 
UnsupportedOperation: underlying stream is not seekable
```

Expected output:
```
$ csvjoin -c C file1 file2
A,B,C,D,E
```

**Comment by jpmckinney** [comment]
Set `--snifflimit 0` (`-y0`). Your current command is essentially asking csvjoin to sniff the CSV dialect on a nonseekable input (standard input). CSV Kit does not buffer the input for sniffing, so you need to simply disable sniffing.

**Comment by csawatzkyST** [comment]
@jpmckinney  Thank you.  I wondered if there was an option, tried a couple, but missed that one.
