### ISSUE TITLE
Possible new feature - csvuniq -c

### ISSUE THREAD

**Issue by glepore70** [wireservice/csvkit#135]
I've been using csvkit for a few days to replicate some complicated Perl programming I have to examine tabular data.  I think csvkit is great!  One feature that I would like to see is the ability to emulate the UNIX uniq -c command.  This would allow us to extract a column using csvcut, run it through csvuniq -c, sort it and get a list of the most used unique values in that column.  Currently I'm using this:
./csvcut -d"|" -c 1 $file | uniq -c | sort -gr | head -11
which basically works, but it appears that the csvkit tools are smart enough to identify the column header and not include it in results.  Piping the column through UNIX uniq -c throws the column back into the mix and doesn't properly extract it as the header (I think.)

Please let me know if I'm missing something, thanks!

GL

**Comment by Fil** [comment]
I came here because I wanted to deduplicate rows based on a certain column, say

```
a b
---
1 c
1 d
2 e
3 f
```

to:
```
a b
---
1 c
2 e
3 f
```

I finally managed with `csvsql --query "select * from 'file' group by a" file.csv`

**Comment by alerque** [comment]
I'm kind of shocked to *not* find this in CSVKit already. In case others end up here Googling for this, two things I found besides the hacks commented on above:

* [csvmerge](https://gitlab.com/ideasman42/csvmerge)
* [csvdedupe](https://pypi.org/project/csvdedupe/)
