### ISSUE TITLE
Basic benchmarking

### ISSUE THREAD

**Issue by hadley** [wireservice/csvkit#141]
It would be really useful to include some basic benchmarking.  For large data, how does csvkit compare to awk, or to pulling all my data into R?

**Comment by gsf** [comment]
This is by no means definitive but a reading of https://davidlyness.com/post/the-functional-and-performance-differences-of-sed-awk-and-other-unix-parsing-utilities suggests CSV handling in Python is already fairly performant compared to awk.

**Comment by jpmckinney** [comment]
I'm not seeing a clear issue to resolve here, so closing.
