### ISSUE TITLE
man pages for scripts

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#15]

**Comment by hut8** [comment]
Hey thanks for csvkit; it's amazing and now I use it constantly. I just generated the man pages and went through all of them to try to see what you meant. Everything looks great. I'm using Ubuntu and I'm not exactly sure how the manual viewer is set up on other systems, but mine is piped through `less`. Even if my terminal is smaller than 80 characters wide, I can still see everything fine by scrolling to the right. So do you think this could be part of the normal build process?

**Comment by jpmckinney** [comment]
What's the command to generate the man pages? My understanding is that even if generated, they won't be put on a path where `man` will see them (see https://github.com/ansible/ansible/issues/7790).

**Comment by jpmckinney** [comment]
Closing: one month without response.

**Comment by ghisvail** [comment]
> What's the command to generate the man pages?

`make -C docs man`

+1 for requesting respective manpages for each command-line tool. This is considered good integration practices in the Linux world in general.

Debian currently yields a warning when building the packaging due to their absence.

**Comment by jpmckinney** [comment]
We don't manage the Debian package, but as there is a way to generate the man pages, I figure the maintainers of that package can update it to include the man pages.

**Comment by vergenzt** [comment]
PR to link the man pages in Homebrew formula is here: https://github.com/Homebrew/homebrew-core/pull/192380
