### ISSUE TITLE
csvclean: options for stdout and stderr

### ISSUE THREAD

**Issue by eadmaster** [wireservice/csvkit#195]
to output the fixed file on stdout and errors on stderr

**Comment by cburkins** [comment]
Loving csvkit.     Would be even better if csvclean could send to stdout so I could include as part of a longer pipe.   Wonder if this feature is on the roadmap ?

**Comment by Jenselme** [comment]
What I think would be awesome is to have an option to make exit csvclean with a non 0 status code if errors are detected. That would make it easy to integrate it as a csv lint tool.

**Comment by jpmckinney** [comment]
To do:

* STDOUT for output
* STDERR for errors
* non-0 exit status if errors

**Comment by scoleri** [comment]
Any word on this?

**Comment by jpmckinney** [comment]
There's a PR #781 

For now you can use it with:

    pip install --upgrade -e git+https://github.com/wireservice/csvkit.git@csvclean#egg=csvkit
