### ISSUE TITLE
csvsql codec can't encode character

### ISSUE THREAD

**Issue by vegetable21** [wireservice/csvkit#199]
similar to (or the same as) issue #82 i get this issue on 0.5.0
to recreate use the following dataset: 
http://www.education.gov.uk/schools/performance/download/csv/england_spine.csv

usage:
csvsql --db "mysql://user:pass@localhost/db" --table "spine" --insert -e "utf8" england_spine.csv

error:
'latin-1' codec can't encode character u'\u2013' in position 12: ordinal not in range(256)

am i missing something? the file passes csvcut and csvstat just fine but the encoding appears to revert to 'latin-1' one when writing to the db

**Comment by ObsidianX** [comment]
Just so it can be noted for future users running into this:

SQLAlchemy can take in an encoding on the DB URL:

`mysql://localhost/dbname?charset=utf8`

**Comment by jayenashar** [comment]
thank you @ObsidianX for your note.  I had tried these before finding your note:
- `LC_ALL=en_US@UTF-8`
- `PYTHONIOENCODING=utf8`
- `--encoding utf-8`
