### ISSUE TITLE
Create debian package

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#20]

**Comment by sandrotosi** [comment]
ehm, I will pretend I didnt see the "script to run pip install" as a solution to package it for Debian :) but just a heads up I'm in the process to create a proper Debian package for csvkit

**Comment by sandrotosi** [comment]
@onyxfish could you please include COPYING file in the next release to PyPI? it contains vital legal information to redistribute your work

**Comment by sandrotosi** [comment]
@onyxfish hi again! in the git repo there is the docs and test directory, it would be nice if you could ship then in the PyPI tarball, so we can build doc and run tests when building the Debian packages

**Comment by sandrotosi** [comment]
package has been uploaded to Debian, it is sitting in NEW (it will take some time to be accepted and be available), the above suggestions are still valid to prepare an even better pkg ;)

**Comment by jpmckinney** [comment]
@sandrotosi Does #487 solve these issues?

**Comment by jpmckinney** [comment]
Closing: one month without response.

**Comment by sandrotosi** [comment]
late reply, but this would be ultimately solved by uploading a new release to PyPI with that fix
