### ISSUE TITLE
csvjoin includes columns on which it joins twice

### ISSUE THREAD

**Issue by gn0** [wireservice/csvkit#210]
Using csvkit 0.5.0, I get the following output:

```
$ csvlook a.csv      
|-----+--------|
|  id | a      |
|-----+--------|
|  1  | lorem  |
|  2  | ipsum  |
|  3  | dolor  |
|-----+--------|
$ csvlook b.csv 
|-----+---------|
|  id | b       |
|-----+---------|
|  2  | asztal  |
|  3  | papir   |
|  4  | toll    |
|-----+---------|
$ csvjoin -d , -c id a.csv b.csv | csvlook
|-----+-------+----+---------|
|  id | a     | id | b       |
|-----+-------+----+---------|
|  2  | ipsum | 2  | asztal  |
|  3  | dolor | 3  | papir   |
|-----+-------+----+---------|
$ 
```

The output I expected:

```
$ csvjoin -d , -c id a.csv b.csv | csvlook
|-----+-------+---------|
|  id | a     | b       |    
|-----+-------+---------|
|  2  | ipsum | asztal  |
|  3  | dolor | papir   |
|-----+-------+---------|
$ 
```

Surely I'm missing something?

**Comment by aequitas** [comment]
Also with an outer join it ends up with two columns with differing values depending on if the id was found in either or both files:

```
csvlook 1                                                                                                                                                                                                                   hardware_overview/git/master !
|----+----|
|  a | b  |
|----+----|
|  1 | 2  |
|  3 | 4  |
|----+----|
csvlook 2                                                                                                                                                                                                                   hardware_overview/git/master !
|----+----|
|  a | c  |
|----+----|
|  1 | 5  |
|  6 | 7  |
|----+----|
csvjoin --outer -c a 1 2 |csvlook                                                                                                                                                                                           hardware_overview/git/master !
|----+---+---+----|
|  a | b | a | c  |
|----+---+---+----|
|  1 | 2 | 1 | 5  |
|  3 | 4 |   |    |
|    |   | 6 | 7  |
|----+---+---+----|
```

which make is hard to delete the extra column without losing data.

An extra option to merge the join columns would be really helpful.

**Comment by aequitas** [comment]
https://github.com/onyxfish/csvkit/pull/385

**Comment by sterlinm** [comment]
+1, merge key option would be great!

**Comment by gromgit** [comment]
I too would prefer to have this issue addressed directly, but in my common case of:

* inner joins on named columns, and
* column order is not important (I'm using CSVs as flat-file DBs rather than spreadsheet source files),

a workaround is simply to `csvcut` out the join field, as follows:
`csvjoin -c <join_field> <file1> <file2> | csvcut -C <join_field>`

This works because `csvcut` currently just removes the _first_ instance of `<join_field>`, instead of all instances.

**Comment by timwis** [comment]
Hey guys, just wanted to chime in and say this would be a really helpful fix :)

**Comment by sparks1372** [comment]
Completely agree, this would be really useful and much more intuitive for people familiar with SQL.

**Comment by onyxfish** [comment]
Fixed in `1.0.0`

**Comment by abcfy2** [comment]
But csvjoin renamed the duplicate columns with `2` to the end, how could I get the joined columns ?

Like this example:

```
csvlook 1
|----+----|
|  a | b  |
|----+----|
|  1 | 2  |
|  3 | 4  |
|----+----|
csvlook 2
|----+----|
|  a | c  |
|----+----|
|  1 | 5  |
|  6 | 7  |
|----+----|
csvjoin --outer -c a 1 2 |csvlook
|----+---+---+----|
|  a | b | a2 | c  |
|----+---+---+----|
|  1 | 2 | 1 | 5  |
|  3 | 4 |   |    |
|    |   | 6 | 7  |
|----+---+---+----|

 csvjoin --outer -c a 1 2 | csvcut -c a,b,c | csvlook
| a | b | c |
| - | - | - |
| 1 | 2 | 5 |
| 3 | 4 |   |
|   |   | 7 |
```

And at the last , `a` has a null value, and that is not what I want.

I wish to get this result:

```
a | b | c
| 1 | 2 | 5 |
| 3 | 4 |   |
| 6 |   | 7 |
```

**Comment by ajorpheus** [comment]
For future readers, if you came  here looking for an option to remove duplicated join columns for `--outer` joins, here is a script that shows one way to achieve this: https://github.com/ajorpheus/csvkit_outer_join_clean_columns

Taking @abcfy2's example, that script has the following output:

```./clean_csvkit_outer.sh a
List of extraneous join columns which will be coalesced into a_coalesced : a,a2

| a | b | c |
| - | - | - |
| 1 | 2 | 5 |
| 3 | 4 |   |
| 6 |   | 7 |
```
