### ISSUE TITLE
csvgrep can't match blanks using -m

### ISSUE THREAD

**Issue by martinburch** [wireservice/csvkit#218]
If I'd like to return a row when a field is blank, I can't do something like 
`csvgrep -c 2 -m '' data.csv`

(I get the error "csvgrep: error: One of -r, -m or -f must be specified, unless using the -n option.")

Instead I must do something like
`csvgrep -c 2 -r '^.' -i data.csv`
Where we match anything in the field and then take the inverse (nothing to match)

**Comment by hydrosquall** [comment]
Landed here because I was doing the following and wondering if there was another way to match blanks, similar to what pandas does with [`dropna`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html). Anyways, this "match empty string" approach works too :).

```bash
csvgrep -c 1 -r '$^' -i myfile.csv > filtered.csv
```
