### ISSUE TITLE
csvformat: Add command-line option to set dialect for Excel compatibility

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#23]
Produces a CSV file which maximizes Excel compatibility. Uses the lessons learned here:

http://simonwillison.net/2008/Aug/20/excel/

**Comment by jpmckinney** [comment]
Blog post is no longer accessible (and it's not in Internet Archive). Excel for Mac throws a wrench into Excel compatibility. The variables I know of for better Excel support are:

* tabs are usually better than spaces
* sometimes a UTF-8 BOM is needed (but sometimes it makes things worse)
* changing the encoding to Windows-1252 is typically best

**Comment by onyxfish** [comment]
Ugh, bummer that this excel CSV reference is gone. I remember it being very useful. Pinging @simonw to see if he might have a backup copy?

**Comment by paulfitz** [comment]
Is it this http://web.archive.org/web/20081120034559/http://simonwillison.net/2008/Aug/20/excel/ https://www.djangosnippets.org/snippets/993/ ?

**Comment by onyxfish** [comment]
That looks like the one! Nice find @paulfitz!

**Comment by jpmckinney** [comment]
> UTF-16, a byte order mark and tab-delimiters

**Comment by jpmckinney** [comment]
I opened some files in Excel today, and it seems to be okay now.
