### ISSUE TITLE
Feature: if no sheet is declared with in2csv then process all sheets in .xls or xlsx files

### ISSUE THREAD

**Issue by pallih** [wireservice/csvkit#251]
Yeah. If no sheetname is specified, loop through all sheets in the Excel file and output a csv for each file.

**Comment by fgregg** [comment]
@onyxfish I'd be willing to take a pass at implementing if this is something you would accept in the library.

**Comment by jpmckinney** [comment]
Dup #217?

**Comment by waldoj** [comment]
:+1:

**Comment by jpmckinney** [comment]
Fixed in https://github.com/onyxfish/csvkit/pull/473

**Comment by waldoj** [comment]
Thank you!

**Comment by jpmckinney** [comment]
Closing in favor of eventually merging the PR.
