### ISSUE TITLE
csvstat --type option

### ISSUE THREAD

**Issue by martinzugnoni** [wireservice/csvkit#267]
I was just thinking about one new command, or just an extension to "csvclean", that validates column content types specified in some kind of mapping given as argument.
For example, somehow the user specifies that the second column "price" must be of content type "float", so the command keeps valid rows and discarts invalid ones, as "csvclean" already do.
Sounds factible to you guys? I would love to contribute.
I was just about to start a new mini project to do this when landed into "csvkit" repo in github.
See you!

**Comment by onyxfish** [comment]
`--type` flag added in `1.0.0`
