### ISSUE TITLE
in2csv doesn't convert line-separated json documents

### ISSUE THREAD

**Issue by themiurgo** [wireservice/csvkit#275]
At the moment in2csv does not convert line-separated json documents (for example, raw output of the Twitter Streaming API). Some other tools do that (for example https://github.com/jehiah/json2csv). Does it make sense to incorporate this functionality in csvkit as well?

**Comment by tobym** [comment]
Looks like this is broken as of v1.0.1.

Per-line with multiple lines:
```
$ cat input1.json
{"a": 2, "b": 3}
{"b": 2, "d": 4}
$ in2csv --format json input1.json
Extra data: line 2 column 1 - line 3 column 1 (char 17 - 34)
```

Per line with one line:
```
$ cat input2.json
{"a": 2, "b": 3}
$ in2csv --format json input2.json
When converting a JSON document with a top-level dictionary element, a key must be specified.
```

Data in array, "expected" format (works):
```
$ cat input3.json
[
{"a": 2, "b": 3},
{"b": 2, "d": 4}
]
$ in2csv --format json input3.json
a,b,d
2,3,
,2,4
```

**Comment by chuanconggao** [comment]
Encountered the same problem on version 1.0.1. Hope it is fixed soon.

**Comment by ricardoekm** [comment]
Same problem here :/
