### ISSUE TITLE
Convert from HTML tables

### ISSUE THREAD

**Issue by Changaco** [wireservice/csvkit#278]
It would be nice to add an `html2csv` script, or add `html` as an input format to `in2csv`.

Here are a couple of implementations one could draw inspiration from:
- http://sebsauvage.net/python/html2csv.py
- https://gist.github.com/mdengler/2963878

**Comment by jpmckinney** [comment]
I'm closing old feature requests that are unlikely to be developed by the maintainers. PRs with tests are welcome, though!

**Comment by Changaco** [comment]
That's a weird way to manage issues. oO
