### ISSUE TITLE
Excel unmerge cells on conversion

### ISSUE THREAD

**Issue by nathanscully** [wireservice/csvkit#293]
When converting excel documents with merged cells, the unmerged cells will contain blank data. My understanding is this is because merged cells are just a visual effect rather than manipulating the underlying data. 

If possible it would be great to have a flag to unmerge the cells and duplicate the data down.

**Comment by jpmckinney** [comment]
I'm closing old feature requests that are unlikely to be developed by the maintainers. PRs with tests are welcome, though! The repository for this feature would be https://github.com/wireservice/agate-excel
