### ISSUE TITLE
Add multiple naming columns on csvstack

### ISSUE THREAD

**Issue by metasoarous** [wireservice/csvkit#294]
A couple of possible CLI specifications

    > csvlook file1.csv
    |----+---+----|
    |  a | b | c  |
    |----+---+----|
    |  1 | 2 | 3  |
    |  4 | 5 | 6  |
    |----+---+----|

    > csvlook file2.csv
    |-----+----+-----|
    |  a  | b  | c   |
    |-----+----+-----|
    |  7  | 8  | 9   |
    |  10 | 11 | 12  |
    |-----+----+-----|

    > csvstack  -n new1,new2 -g x,y,z,w  file*.csv | csvlook
    |-------+-------+----+----+-----|
    |  new1 |  new2 | a  | b  | c   |
    |-------+-------+----+----+-----|
    |  x    |  z    | 1  | 2  | 3   |
    |  x    |  z    | 4  | 5  | 6   |
    |  y    |  w    | 7  | 8  | 9   |
    |  y    |  w    | 10 | 11 | 12  |
    |-------+-------+----+----+-----|

    > csvstack  -n new1 -g x,y -n new2 -g z,w  file*.csv | csvlook
    ... same ...

**Comment by jpmckinney** [comment]
You can do this in multiple steps:

```
csvstack -n new1 -g x file1.csv > file1new.csv
csvstack -n new1 -g y file2.csv > file2new.csv
csvstack -n new2 -g z,w file1new.csv file2new.csv
```
