### ISSUE TITLE
csvjoin: prefix joined column names

### ISSUE THREAD

**Issue by michaelmior** [wireservice/csvkit#306]
It would be helpful to have the option to add a prefix to the column names output by `csvjoin` for easy disambiguation between similarly named columns. For example, I might have two CSV files `a.csv` and `b.csv` which both have a column `foo`. It would be nice to be able to do:

```
csvjoin --columns bar,bar --prefix a,b a.csv b.csv > c.csv
```

And then get the header `a_foo,a_bar,b_foo,b_bar`. This is especially useful when you have to do further processing on the file. It's meach easier to prepend a string to the column name instead of keeping track of indices. If this is something you're open to, I could work on a PR as I don't imagine it will take a lot of work.

**Comment by jpmckinney** [comment]
Version 1.0.0 has: "csvjoin now renames duplicate columns with integer suffixes to prevent collisions in output."

**Comment by michaelmior** [comment]
@jpmckinney Great! Sorry I never got around to putting together a PR myself but glad to see this is resolved :)
