### ISSUE TITLE
A strange cron problem with csvsql 

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#342]
Hi all,
if I run this script, it runs properly
/usr/local/bin/csvsql --query  "select \* from archiviotemp_05 group by numero_protocollo" /var/www/test/archiviotemp_05.csv > /var/www/test/06_archivio.csv

If I run it via cron I have a 0 kb file. This my cron job:
*/5 \* \* \* \* root /bin/bash /usr/local/bin/csvsql --query  "select \* from archiviotemp_05 group by numero_protocollo" /var/www/test/archiviotemp_05.csv > /var/www/test/06_archivio.csv > /dev/null 2>&1

It seems to me that there is some problem related to csvsql and cron, because I use cron without any problems with the other csvkit commands. But it could be stupid error of mine.

Thank you very much

**Comment by jommgoncalves** [comment]
Hi,

I have the same problem. The proposed workaround it works for one table but for multiple tables it doesn't work :\

Anyone knows how can I solve this problem?

Thank you very much,

**Comment by jpmckinney** [comment]
@jommgoncalves You can pass multiple table names with `--tables`.

**Comment by jommgoncalves** [comment]
@jpmckinney Thank you for your quickly reply.  It works with your suggestion!

**Comment by imwikaash** [comment]
Hi all,
I am using csvsql in a script . it is executing fine. But the same is not working using a crob job.

Please help.

**Comment by aborruso** [comment]
@imwikaash please paste here your crone command

**Comment by imwikaash** [comment]
@aborruso Here is my crone command
29 * * * * python /mnt/scripts/marketplace007/files/checkImsVimSync.py >> /mnt/scripts/marketplace007/files/error.log 2>&1


here is command in checkImsVimSync python file
path="/mnt/scripts/marketplace007/files"
os.system('csvsql --query "select * from test" --tables test<'+path+'/test.csv > '+path+'/nonsynced.csv')

**Comment by aborruso** [comment]
@imwikaash try to put the absolute path of `csvsql` inside your py file

**Comment by imwikaash** [comment]
Thanks @aborruso 
working fine after adding the absolute path of csvsql ..
