### ISSUE TITLE
csvsql: filenames with leading numbers generate invalid table names in sqlite

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#343]
Hi,
if I run this command I have a token error (unrecognized token: "05_temp ..."):
csvsql --query  "select \* from 05_temp group by numero_protocollo" 05_temp.csv

I have this error because csvsql create a temp sqlite table and sqlite tables name cannot start with a number.

Probably it would be better to have an error related to table name and not to a token. But I do not know it is simple.

Thank you

**Comment by jpmckinney** [comment]
You just need to add backticks, e.g.:

    csvsql --query "select * from `05_temp` group by numero_protocollo" 05_temp.csv
