### ISSUE TITLE
csvlook, csvstat not usable due to "must be str, not bytes" error

### ISSUE THREAD

**Issue by bklaas** [wireservice/csvkit#346]
> csvlook data_dict_ca1901a.csv 
> must be str, not bytes
> 
> I am using ArchLinux, Python 3.4.1, and csvkit installed via pip (compiled against Python 3.4.1). This feels like a Python 3.x issue.

Possible pointers for a fix:
http://stackoverflow.com/questions/5512811/builtins-typeerror-must-be-str-not-bytes
http://stackoverflow.com/questions/4980292/programming-python-for-absolute-beginners-chapter-7-storing-complex-data

**Comment by critmcdonald** [comment]
I'm having this problem on Windows 8. On any file I can't use csvlook or csvstat without getting the "must be str, not bytes". I'm using Python 3.4.3

I *was* able to use csvsql command which surprised me, but pleasantly so.

**Comment by desilinguist** [comment]
I am still getting encountering this issue on OS X 10.10.3 with python 3.4.3, v 0.9.1.
