### ISSUE TITLE
text value loaded as a single char in csvsql

### ISSUE THREAD

**Issue by amnonkhen** [wireservice/csvkit#349]
I am trying to load a tsv file into mssql.
The numeric columns are loaded correctly, but all the textual columns are loaded as a single char.
I don't know if it is related, but the columns' type according to csvstat is "unicode".

Is the problem related to encoding? I found this [related post in stackoverflow](http://stackoverflow.com/questions/17394092/only-first-character-of-unicode-strings-getting-written-to-csv) 
Is there a solution?

**Comment by jpmckinney** [comment]
@amnonkhen I'll need to see a sample file, because I can't reproduce this error. You can just replace whatever private data it contains with garbage.

**Comment by jpmckinney** [comment]
Closing: one month without response.
