### ISSUE TITLE
in2csv doesn't handle blank fields?

### ISSUE THREAD

**Issue by ksakuda** [wireservice/csvkit#362]
The in2csv tutorial file (ne_1033_data.xlsx) contains blank values for the item_name for multiple rows.  Consequently, the processed file (data.csv) has shifted the values where they are not aligned to the column correctly in rows that contain blank values.   Is there a way to process a file with blank values within a column and align the columns correctly?

**Comment by searoso** [comment]
I used in2csv to convert bunch of JSON-responses for further processing, and files that had first field of first tuple blank are totally messed up with shift of columns in the result.

I'm not sure if I should create one more issue; also I can provide you the files if needed.

P.s. Thanks for awesome piece of software! =)

**Comment by onyxfish** [comment]
I can no longer replicate this issue. I know it's been a while since this issue was opened, but if either of you could attempt to verify the fix that would be much appreciated.

**Comment by searoso** [comment]
I'm sorry, this project is passed already, and I can't recollect what did I
do precisely.

If I will use the tool again (I hope), I will file it again!

2015-03-31 5:02 GMT+03:00 Christopher Groskopf <notifications@github.com>:

> I can no longer replicate this issue. I know it's been a while since this
> issue was opened, but if either of you could attempt to verify the fix that
> would be much appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/onyxfish/csvkit/issues/362#issuecomment-87898127>.
>



-- 
Сергей Александрович Каунов.

**Comment by yanofsky** [comment]
I'm running into this issue with an xlsx, after poking around it appear to be an issue with openpyxl

**Comment by jpmckinney** [comment]
@yanofsky Can you provide a sample file?

**Comment by jpmckinney** [comment]
Closing: one month without response.
