### ISSUE TITLE
csvstat doen't give counts for some columns

### ISSUE THREAD

**Issue by nealmcb** [wireservice/csvkit#383]
csvstat is great, and usually gives a sense of the mode of the data, via a count of how many rows have the most frequent values:
<pre>
 4. LAST_NAME
        <type 'unicode'>
        Nulls: True
        Unique values: 307123
        5 most frequent values:
                SMITH:  28155
                JOHNSON:        23713
                MARTINEZ:       18465
                MILLER: 16916
                BROWN:  15428
        Max length: 28
</pre>
But sometimes it doesn't, perhaps when there less than some predefined number of unique values:
 
<pre>
28. STATUS
        <type 'unicode'>
        Nulls: False
        Values: Active, Inactive
</pre>

I'd like to get counts of the top 5 most frequent values for all columns, as long as there are any repeated values.

**Comment by jpmckinney** [comment]
This behavior is from commit bc125a6e1ebdea1d0634ded6fd5199fc96e0fee4 with the comment:

> Made 'top 5' not display in csvstat if all values in a column are unique

**Comment by jpmckinney** [comment]
I don't know why we wouldn't always report frequencies, so I'll change this behavior.
