### ISSUE TITLE
csvjoin with specific output field support

### ISSUE THREAD

**Issue by nagabhushan** [wireservice/csvkit#405]
HI,

While working found that the join will give output by concatenating rows from csv.
It will be helpful if option to provide selected field like JOIN in LINUX 1.2,2.1,1.3 ..

Thanks

**Comment by jpmckinney** [comment]
@nagabhushan I'm not sure I understand. Can you give an example input, the command you would run, and the expected output?

**Comment by jpmckinney** [comment]
Closing: one month without response.
