### ISSUE TITLE
csvstat: flag to specify how many frequent values to display

### ISSUE THREAD

**Issue by lazuly** [wireservice/csvkit#408]
Csvstat is really a very useful tool, but it still could be better : the "frequent values" feature is apparently fixedly limited to 5 values. It would be great if this "5" value was only the default value, and could be altered by a new parameter, say "-f ". 

For example : "csvstat -f 20 -c 3,7 --freq myfile.csv" would return the 20 most frequent values of colums 3 and 7. Today it (seems) impossible to exceed the limit of 5 values.

Best regards, thanks for this great kit.

**Comment by jpmckinney** [comment]
Noting that this should be moved to https://github.com/onyxfish/agate-stats

**Comment by onyxfish** [comment]
This would still require some sort of a CLI option to toggle things. Once we get `csvstat` ported over onto `agate` we'll probably want to revisit how all these options are structured. Leaving it open and marking it low for now.

**Comment by Fil** [comment]
:+1:

**Comment by onyxfish** [comment]
This would be super easy to implement now if somebody wants to pick it up. Maybe ``--freq-count``
