### ISSUE TITLE
csvclean: Warn about trailing commas

### ISSUE THREAD

**Issue by inodb** [wireservice/csvkit#426]
When a csv has multiple empty columns without headers, no errors are shown.

```
$ echo -e 'h1,h2,,,\na,b,,,' | csvclean -n
No errors.
```

This is a common error when exporting data from excel so it would be nice if this would be caught in some way. Maybe by confirming there is at least one value in a given column or the column has a header.

**Comment by jpmckinney** [comment]
Is this actually an error though? It wouldn't cause problems for any code that reads CSVs that I can think of.

**Comment by inodb** [comment]
I guess it's not a syntax error, but it is a common mistake when creating csv files manually. Maybe more of a lint error. A warning would be useful though

**Comment by jpmckinney** [comment]
Good idea: We can add a warning.

**Comment by gheeshuggah** [comment]
:+1:
