### ISSUE TITLE
csvstat: Option to display unique values

### ISSUE THREAD

**Issue by stucka** [wireservice/csvkit#448]
I'd love to get the unique values themselves.

With csvkit and basic GNU or Unix tools, you can get unique values for a column:

```
csvcut -c 4 myfile.csv | sed 1d | sort | uniq
```

That takes all the 4th column, snips off the first row (header row), sorts it, and spits out unique values.

**Comment by stucka** [comment]
uniq depends on a sorted file. For the documented workflow, you'd need to use csvsort, or Unix sort after knocking off the header row. Or I may be wrong as usual. =)

**Comment by jpmckinney** [comment]
Yes, you are correct :) I've added `sort`. Thanks!
