### ISSUE TITLE
CSV Sort requires large amounts of memory

### ISSUE THREAD

**Issue by bowlofstew** [wireservice/csvkit#457]
Would it be possible to utilize external sort instead of your current reverse sorter algorithm?  If you are open to pull requests then I will do it; just let me know.

**Comment by jpmckinney** [comment]
Yes, PRs are welcome!

**Comment by onyxfish** [comment]
@bowlofstew what do you mean by "external sort"?

**Comment by jpmckinney** [comment]
No clarification...
