### ISSUE TITLE
list index out of range, ERROR

### ISSUE THREAD

**Issue by ppKrauss** [wireservice/csvkit#458]
If this tool works with https://github.com/datasets, it will be a sucess (!)... But at this moment, after install, my first test (as [this syntax example](http://csvkit.readthedocs.org/en/0.9.1/scripts/csvjoin.html)) was an error message,

`csvjoin -c "ISO3166-1-Alpha-2,iso_alpha2" --outer country-codes.csv country-wikiCodes.csv`

using [this file for `country-codes.csv`](https://github.com/datasets/country-codes/blob/master/data/country-codes.csv) and the following simple list for  `country-wikiCodes.csv`,

```
iso_alpha2
AD
AE
AF
AG
AI
AL
AM
AO
AQ
AR
AS
AT
AU
AW
AX
AZ
BA
BB
BD
...
YE
YT
ZA
ZM
ZW
```

Note that the same error occurs if you change the file2 column name to "ISO3166-1-Alpha-2", so

  `csvjoin -c "ISO3166-1-Alpha-2" --outer country-codes.csv country-wikiCodes.csv`

produce the same *list index out of range* error.

**Comment by jpmckinney** [comment]
I can't reproduce. No error from following:

```
curl -O https://raw.githubusercontent.com/datasets/country-codes/master/data/country-codes.csv
echo "iso_alpha2
AD
AE
AF
AG
AI
AL
AM
AO
AQ
AR
AS
AT
AU
AW
AX
AZ
BA
BB
BD
...
YE
YT
ZA
ZM
ZW" > country-wikiCodes.csv
csvjoin -c "ISO3166-1-Alpha-2,iso_alpha2" --outer country-codes.csv country-wikiCodes.csv
```

**Comment by jpmckinney** [comment]
Closing: one month without response.

**Comment by andrewharvey** [comment]
For anyone else landing here I got the `list index out of range error.` error when one of the CSV files had a blank/empty line.

**Comment by jpmckinney** [comment]
Hmm, I can't reproduce when doing that either. Can you upload a pair of CSVs that causes the error?

**Comment by andrewharvey** [comment]
@jpmckinney 

first.csv
```
id,value
1,a
```

second.csv
```
id,foo
1,bar

```

`csvjoin -c 1 --left first.csv second.csv`

produces

`list index out of range`

removing the empty line in second.csv fixes the issue.

**Comment by jpmckinney** [comment]
Can you report the information requested in https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst ? 

Also, make sure you're using the latest version of csvkit.

**Comment by andrewharvey** [comment]
No doubt it could be fixed in a more recent csvkit, so if you can't replicate it then don't worry about it.

I just wanted to post what the issue was for me and the workaround I used in case anyone else stumbled here with that error message.

```
> csvjoin -v -c 1 --left first.csv second.csv 
Traceback (most recent call last):
  File "/usr/bin/csvjoin", line 9, in <module>
    load_entry_point('csvkit==0.9.1', 'console_scripts', 'csvjoin')()
  File "/usr/lib/python3/dist-packages/csvkit/utilities/csvjoin.py", line 111, in launch_new_instance
    utility.main()
  File "/usr/lib/python3/dist-packages/csvkit/utilities/csvjoin.py", line 67, in main
    jointab = join.left_outer_join(jointab, join_column_ids[0], t, join_column_ids[i + 1])
  File "/usr/lib/python3/dist-packages/csvkit/join.py", line 129, in left_outer_join
    right_mapped_keys = _get_mapped_keys(right_rows, right_column_id)
  File "/usr/lib/python3/dist-packages/csvkit/join.py", line 13, in _get_mapped_keys
    key = r[column_index]
IndexError: list index out of range
```

```
> python --version
Python 2.7.13

> python3 --version
Python 3.5.3+

```

```
> uname -a
Linux hostname 4.11.0-2-amd64 #1 SMP Debian 4.11.11-1 (2017-07-17) x86_64 GNU/Linux
(Debian unstable)
```

```
> apt-show-versions python3-csvkit
python3-csvkit:all/sid 0.9.1-3 uptodate
```

**Comment by jpmckinney** [comment]
Ahh, yes 0.9.1 is an old version :)
