### ISSUE TITLE
csvstack: consumes all disk space if input file is output file

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/csvkit#466]
Take any CSV:

`csvstack file.csv > file.csv`

csvstack should error instead of ballooning.

**Comment by deps** [comment]
The problem here is that the output redirection to the same file is done by bash and is outside of the csvstack control. 
Someone please correct me if I'm wrong.

**Comment by jpmckinney** [comment]
Can't csvstack lock the file while reading to prevent writing?

**Comment by deps** [comment]
Only using platform specific code, which would not make csvkit portable. 
There exists modules for aiding in this, but not one that would work for all platforms, as far as I can tell.

**Comment by jpmckinney** [comment]
If a platform is unsupported, then we can just have the default behavior of ballooning forever.

**Comment by jpmckinney** [comment]
A promising library is http://fasteners.readthedocs.io/en/latest/ but ultimately this is a rare case that can be dealt with in the documentation.
