### ISSUE TITLE
windows 8.1 failed to create proccess

### ISSUE THREAD

**Issue by jrjames83** [wireservice/csvkit#474]
Hopefully missing something really basic here. I conda installed csvkit, went fine. Steps:

conda install csvkit - OK

PATH

PATH=
C:\Python27;
C:\Python27\Lib\site-packages\;
C:\Python27\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;
C:\Users\Jeffrey\Anaconda;
C:\Users\Jeffrey\Anaconda\Scripts;

C:\Users\Jeffrey\ csvlook tcdata.csv
failed to create process.

**Comment by onyxfish** [comment]
I don't have any experience using csvkit on a Windows environment so I'm really not sure what to suggest. Maybe @mattwaite's students have run into this?

**Comment by satish4j** [comment]
I'm having the same problem

**Comment by jpmckinney** [comment]
@jrjames83 @satish4j Is this still an issue with csvkit>=1.0.0?

**Comment by jpmckinney** [comment]
Just noticed Anaconda uses old version of csvkit. Need to be using csvkit >= 1.0.0.
