### ISSUE TITLE
Remove requirements/dependencies that aren't needed after agate refactor

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#490]

**Comment by jpmckinney** [comment]
Any opinion on unfreezing date-util as part of this? #436 #370

**Comment by onyxfish** [comment]
Date-util actually isn't used in agate—I use parsedatatime instead. It's proven somewhat more reliable and infinitely easier to test. So assuming we remove the rest of the references to the original table I think we can axe date-util entirely.

**Comment by jpmckinney** [comment]
:ok_hand:

**Comment by jpmckinney** [comment]
Should also check whether we need to bump the minimum versions of any. (SQLAlchemy is at 0.6 in setup.py, which is pretty old.)

**Comment by jpmckinney** [comment]
Noting that in Python 2, ordereddict and simplejson are only needed for GeoJSON support.

**Comment by jpmckinney** [comment]
I think all have been removed except date-util blocked by #497
