### ISSUE TITLE
Update documentation to point to agate

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#491]
"csvkit is the command-line interface to agate"
"If you need to do complex data analysis that csvkit can't handle, use agate."

etc, etc

**Comment by jpmckinney** [comment]
Note that this was in install.rst (which I'm moving per #529) without any context:

```
If you only want to use agate, install it this way::

    pip install agate
```

**Comment by onyxfish** [comment]
Ha, woops, looks like I made a copy and paste mistake there. ;)
