### ISSUE TITLE
csvkit.utilities.csvsql still relies on bespoke Table implementation

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#494]
Should use https://github.com/onyxfish/agate-sql

**Comment by jpmckinney** [comment]
Blocked: https://github.com/onyxfish/agate/issues/444

**Comment by jpmckinney** [comment]
Unblocked - but not sure how to replicate `blanks_as_nulls` behavior in agate.

**Comment by jpmckinney** [comment]
Can we remove the `--blanks` option? Otherwise we need to add it to agate.

I started working on this, but I need to know agate-sql, and I don't really have the time to do that. https://github.com/wireservice/agate-sql
