### ISSUE TITLE
csvkit.utilities.csvstat still relies on bespoke Table implementation

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#496]
Should use https://github.com/onyxfish/agate-stats

**Comment by jpmckinney** [comment]
Blocked: https://github.com/onyxfish/agate/issues/444

**Comment by jpmckinney** [comment]
Unblocked - but not sure how to replicate `column_ids` behavior in agate.

Note that I renamed `zero_based` to `column_offset`, and `zero_based` no longer made sense when combined with `line_numbers` in csvgrep (using both options together would produce something like "-1 based").

**Comment by onyxfish** [comment]
This and #494 are both effectively done my `kill-table` branch. A release of `agate-sql` is necessary for any of it to work. A very minor bug fix for `agate` is also necessary for the tests to pass.

**Comment by onyxfish** [comment]
`agate-sql` release is done. Still have to do a minor agate release before merging.
