### ISSUE TITLE
Agate/Table different in handling of unnamed columns

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#498]
In the old table implementation they got named "_unnamed"

In agate they just don't get a name. (presuming you'll access them by column index).

Need to make sure this doesn't live any lingering bugs or bad docs.

**Comment by onyxfish** [comment]
New agate behavior: an unnamed column that is passed to agate as "None" will receive a letter name corresponding to its position.

**Comment by jpmckinney** [comment]
Noting that agate/csvkit should perhaps use lowercase letters in column names to avoid having to quote the columns in the SQL tools.

**Comment by onyxfish** [comment]
Yeah, lowercase is probably more Pythonic anyway. See onyxfish/agate#464.

**Comment by jpmckinney** [comment]
I don't think there's anything more to do here.
