### ISSUE TITLE
Precise behavior of type inference around integers and decimals has changed with agate refactor

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#506]
Need to make sure docs reflect this. (Principles section is def wrong.)

**Comment by jpmckinney** [comment]
And booleans?

**Comment by jpmckinney** [comment]
New CHANGELOG items, per #501:

Backwards-incompatible changes:

* csvjson now infers data types (e.g. integer, float, boolean).

**Comment by onyxfish** [comment]
Has the boolean behavior changed?

**Comment by jpmckinney** [comment]
I had to change a bunch of tests (e.g. reading dummy.csv has `True` in column `a` instead of `1`), so I think it has.

**Comment by onyxfish** [comment]
Hmmm, that's true because if a column contains only zeros and ones than it is interpreted as boolean. However, I think the other point there is that `dummy.csv` is a pretty bad test. We should probably fix that where it's relevant.

**Comment by onyxfish** [comment]
And also we should update the docs to specify that 0/1 columns will now be interpreted as booleans

**Comment by onyxfish** [comment]
Did a bit of a half-ass job of this but I think it's good enough for now. More as time allows to do a proper complete revision of the docs.
