### ISSUE TITLE
Fix versions of agate and agate-excel 

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#508]
I currently have the requirements set so these are pointing to my master branch. Need to release those fixes and set versions before next csvkit release.

**Comment by jpmckinney** [comment]
And agate-sql

**Comment by onyxfish** [comment]
agate is now 1.2.2, agate-excel is now at 0.1.0

**Comment by onyxfish** [comment]
agate-dbf at 0.1.0. All versions updated for the moment.

**Comment by jpmckinney** [comment]
Seems done.
