### ISSUE TITLE
csvsql: Support for direct queries on files with special characters in their names

### ISSUE THREAD

**Issue by elfring** [wireservice/csvkit#521]
A command like "`csvsql --query …`" can perform interesting data analysis if the provided input data can be converted to an in-memory database.
This detail has got further consequences on the passed SQL script because the needed table names should be determined somehow.

1. I observed that a message (like "syntax error") can be presented if an input file was passed with a name that contained "special characters" which did not fit to the supported character set for a SQL table name.
 [A related issue](https://github.com/onyxfish/csvkit/issues/343 "csvsql and sqlite table name") was reported by Andrea Borruso on 2014-10-05.

2. But I do not need such an error message for the rejection of a "questionable" table name occasionally. I would prefer in some use cases that a specific query can still be executed.
 * The table name generation rules should become completely predictable then if I would like to ensure myself to some degree that file and table names will finally be compatible.
 * Appropriate table names could also be automatically selected without deriving them from provided special file names.
 * The chosen table names need eventually to be stored into additional environment variables if further data processing should be performed after a specific command call.

**Comment by jpmckinney** [comment]
Are you aware of the `--table` option that lets you name the table something else?

**Comment by elfring** [comment]
Should I read any more explanations for such a parameter if I check the result from a command like "`csvsql --help|grep table`"?

**Comment by jpmckinney** [comment]
Yes, sorry, the option is `--tables` though `--table` is accepted. If you just grep you won't get the complete help because the help text goes on multiple lines.

**Comment by elfring** [comment]
How often can the tool "csvsql" take care for appropriate table names itself (instead of expecting restricted command parameters)?

**Comment by elfring** [comment]
By the way:
* How good does the wording '… `or "stdin" will be used.` …' in the shown help text fit to the key word "`tables`" finally?
* Would an unambigous description be more useful here?

**Comment by jpmckinney** [comment]
Yes, that help text should be improved.

**Comment by jpmckinney** [comment]
Related #525

**Comment by jpmckinney** [comment]
I improved the help text. I think this issue is partly superseded by #343.

In terms of automatically determining appropriate table names if the filename is not a valid table name: I don't think there's a general solution to that, because the table name needs to appear in the SQL command, and thus the user must know the table name when writing that command, and so it just makes sense for the user to use the `--tables` option, instead of expecting CSVKit to handle everything automatically.

**Comment by elfring** [comment]
Would you like to make the name mapping algorithm more configurable (besides the parameter "tables")?

**Comment by jpmckinney** [comment]
--tables gives the user complete control over the names of tables. What more could you need?

**Comment by elfring** [comment]
I imagine a need to select the place better where table names will be adjusted according to the rules of a chosen SQL engine. How do you think about an improved name selection which could take also patterns into account?

**Comment by jpmckinney** [comment]
I'm not clear on the need for it.

**Comment by elfring** [comment]
* Where should an enhanced name selection be performed for the supported SQL dialects?
* Would you like to achieve that tables can be created with a higher probability after changes for challenging file names?
