### ISSUE TITLE
csvsql: Add --unique-index a,b to add unique index

### ISSUE THREAD

**Issue by brandon-rhodes** [wireservice/csvkit#572]
It is wonderful that `--insert` exists and provides a quick way to have a table created and loaded with data!

But if the source CSV file is improved, tweaked, or regenerated, then the user is dead in the water. The table in the database is now out of sync with the CSV data, and there is no facility for ever updating it. There are at least two ways that csvkit could solve this:
- Provide a `--drop` option that would, in a single database transaction, drop the table, create the table, and reload it with the new data.
- The really fun solution would be an `--upsert COLUMN[,COLUMN...]` option that attempted to insert all of the rows, but for those that failed switched to attempting an update using the given columns as keys to search for and match.

**Comment by jpmckinney** [comment]
Related #200. What if we allowed `--prefixes REPLACE` to run an `INSERT OR REPLACE` query? You'd just have to manually set a unique key constraint on the columns that you would have put after `--upsert` in your example.

**Comment by jpmckinney** [comment]
`--overwrite` done in #572.

`test_query_with_prefix` has code for creating indexes if we want to implement `--unique-index a,b`.
