### ISSUE TITLE
csvclean: performance issue detecting errors

### ISSUE THREAD

**Issue by ThomasMic** [wireservice/csvkit#575]
Hello,

we faced a problem with csvclean on a simple case of error :
- the header of the file is composed of n columns
- the rest of the file is a great number of lines with n+1 columns

while validating this kind of file with found that csvclean is taking more and more time, not in a linear scale, to report errors that it found on each line

Thanks

**Comment by ThomasMic** [comment]
I forgot to mention it was a tab separated kind of file, csvclean is launched with the following options /usr/bin/python /usr/bin/csvclean -e UTF-8 -t

**Comment by jpmckinney** [comment]
Can you provide a sample CSV please?

**Comment by ThomasMic** [comment]
Yes,

see attached 2 samples files one with 300 lines of "extra columns" (csvkit_clean_crash_300.tsv) datas, the other (csvkit_clean_crash_600.tsv) with 600 lines of "extra columns" datas (first part of the file up to line 300 is the same as in the first file)



1/ execution on file csvkit_clean_crash_300.tsv took 1:10 minute :

[devel@begonias ~]$ date
jeu. févr. 11 16:40:43 CET 2016
[devel@begonias ~]$  /usr/bin/python /usr/bin/csvclean -e UTF-8 -t csvkit_clean_crash_300.tsv
299 errors logged to csvkit_clean_crash_300_err.csv
[devel@begonias ~]$ date
jeu. févr. 11 16:41:52 CET 2016



2/ execution on file  csvkit_clean_crash_600.tsv  took much much much more time :  8 minutes ! , if it was linear to #of input lines we could have expected double time of test 1, that is around 2 minutes).

[devel@begonias ~]$ date
jeu. févr. 11 16:42:36 CET 2016
[devel@begonias ~]$  /usr/bin/python /usr/bin/csvclean -e UTF-8 -t csvkit_clean_crash_600.tsv
599 errors logged to csvkit_clean_crash_600_err.csv
[devel@begonias ~]$ date
jeu. févr. 11 16:50:46 CET 2016



In production we need to check files with 4000 lines and it's almost never ending...

[csvkit_clean_crash_300.tsv.txt](https://github.com/onyxfish/csvkit/files/126621/csvkit_clean_crash_300.tsv.txt)
[csvkit_clean_crash_600.tsv.txt](https://github.com/onyxfish/csvkit/files/126622/csvkit_clean_crash_600.tsv.txt)

**Comment by jpmckinney** [comment]
Are you using a release of csvkit or the most recent version in GitHub? I recommend trying the most recent GitHub version and seeing if the issue still exists. We'll have an official release soon.

**Comment by ThomasMic** [comment]
the informations I have is :
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'csvkit==0.9.0','console_scripts','csvclean'
__requires__ = 'csvkit==0.9.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('csvkit==0.9.0', 'console_scripts', 'csvclean')()
    )

**Comment by jpmckinney** [comment]
Can you install with the following, then run csvclean again:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by ThomasMic** [comment]
I'm going to try, but I think it's already a lot better in 0.9.1 relase :) , as you can see (not exactly same env w64/linux) the 600 errors only took 3 minutes !

C:\Python27\Scripts>time
L’heure actuelle est : 17:42:59,63
Entrez la nouvelle heure :

C:\Python27\Scripts>csvclean -e UTF-8 -t C:\Users\michaux\Desktop\csvkit_clean_crash_300.tsv
299 errors logged to C:\Users\michaux\Desktop\csvkit_clean_crash_300_err.csv

C:\Python27\Scripts>time
L’heure actuelle est : 17:43:27,31
Entrez la nouvelle heure :


C:\Python27\Scripts>time
L’heure actuelle est : 17:43:58,39
Entrez la nouvelle heure :

C:\Python27\Scripts>csvclean -e UTF-8 -t C:\Users\michaux\Desktop\csvkit_clean_crash_600.tsv
599 errors logged to C:\Users\michaux\Desktop\csvkit_clean_crash_600_err.csv

C:\Python27\Scripts>time
L’heure actuelle est : 17:46:49,45
Entrez la nouvelle heure :

**Comment by jpmckinney** [comment]
Ok, but ideally it should not take so long for 600 lines :) so if it still takes that long on the in-development version, then we should keep this issue open.

**Comment by ThomasMic** [comment]
ok from the github dev version it's the same timing than release 0.9.1, 600 erreanous lines in 2 minutes. 

C:\Python27\Scripts>time
L’heure actuelle est : 18:02:50,72
Entrez la nouvelle heure :

C:\Python27\Scripts>csvclean -e UTF-8 -t C:\Users\michaux\Desktop\csvkit_clean_crash_600.tsv
599 errors logged to C:\Users\michaux\Desktop\csvkit_clean_crash_600_err.csv

C:\Python27\Scripts>time
L’heure actuelle est : 18:04:27,33

**Comment by ThomasMic** [comment]
If you find it slow I will be happy if you can do the same thing faster :)  anyway i think time is now linear with releases after 0.9.1 and the biggest problem was non linear time in 0.9.0

**Comment by jpmckinney** [comment]
I found the exponential growth; it only occurs in files where every row has a different length than the first row. Working on a fix though.
