### ISSUE TITLE
Q: csv to fixed length file

### ISSUE THREAD

**Issue by tkang007** [wireservice/csvkit#576]
CSVkit is wonderful. Many thanks to all who contribute for this nice tool. 
I will very appreciate if anyone can give me any hint how to convert csv file to fixed length flat file at command line?

**Comment by jpmckinney** [comment]
Thank you for suggesting this new CSV tool. However, the maintainers have decided to not author, merge or maintain new tools; there is simply not enough time to do so. Our focus is instead on making the existing tools as good as possible.
