### ISSUE TITLE
Requirements hard-coded and agate.reader does not exist

### ISSUE THREAD

**Issue by Gerenuk** [wireservice/csvkit#579]
When using csvkit 1.0.0:

In setup.py the requirement python-dateutils==2.2 is hard-coded which makes the installation fail (for Python 3.4)

Also agate.reader required in __init__.py does not exist in agate 1.3.0

**Comment by onyxfish** [comment]
The reader and writer have been moved into the `agate.csv` namespace. I haven't gotten around to updating master yet.

**Comment by Fil** [comment]
hmm I've been biten by this too :(

Can you point to an install/build from source docs?

I've done
```
python setup.py install
python setup.py build
```
(it fails on this issue, which I understand, but is it the right way to install?).

**Comment by jpmckinney** [comment]
Fixed in master!
