### ISSUE TITLE
Add example to csvsql documentation of using csvstack to stack files first

### ISSUE THREAD

**Issue by esafak** [wireservice/csvkit#580]
A query of the form `csvsql --tables data --db "postgresql://user:pass@localhost" --insert foo*` results in the creation of table `data` for the first file match, followed by tables names matching the file names of subsequent matches. A more reasonable behavior would be to insert them all into the same table.

**Comment by jpmckinney** [comment]
Why don't you `csvstack` the files first? I can see a use case for creating tables for a bunch of files that don't have the same structure.

**Comment by esafak** [comment]
That's a valid approach. Maybe you should clarify this in the documents. Close at will.

**Comment by jpmckinney** [comment]
Thanks! Renamed and tagged as a documentation issue.
