### ISSUE TITLE
in2csv: how to override duplicate column names error?

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#582]
Dear all,
often I use csvkit to clean messy xls input files.

I start usually from in2csv to convert input xls file to a more comfortable csv file, and than I remove empty rows, normalize content, filter content, etc..
An input file often has inside it every kind of error, and one of this could be "duplicate column names". 

But if I start from in2csv with a file as the attached one, I must immediately stop because I have "Duplicate column names are not allowed." error.
I there a way to override this and create a csv file?

Thank you

[in2csv_test.xls](https://files.zenhub.io/56dc17af601c8dd53dda776b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by jpmckinney** [comment]
Are you experiencing this error with a released version of csvkit (if so, which version are you using?), or do you only experience it with the development version from GitHub? Related #563

**Comment by aborruso** [comment]
hi @jpmckinney I'm using the dev version because I need to override #578

Thank you

**Comment by jpmckinney** [comment]
Try upgrading agate `pip install --upgrade agate`.

**Comment by aborruso** [comment]
what a project and what a great people.

Thank you, it works
