### ISSUE TITLE
csvstat: output in CSV format

### ISSUE THREAD

**Issue by KarolTx** [wireservice/csvkit#584]
Hi, could the csvstat command be extended to output the stats in CSV-like format:?

```
column,class,count,nulls,unique,min,max,sum,mean,median,stdev,max_length,fv_1,fv_2,fv_3,fv_4,fv_5
AAA,int,1000,23,4,...
```

It would help a lot on data discovery. Thank you for the great tool.
Cheers,
Karol

**Comment by dannguyen** [comment]
Was just about to open an issue about this but figured someone else might have the same itch. I'm undergoing a project involving curating a lot of datasets, and having CSV output would be great. A few things would have to be altered, such as the way categorical values are listed. Basically, I want to be able to output something that I can throw into a Markdown documentation file:

|   Column   |  Type  | Unique values | Nulls | Length |  Min  |  Max   |  Mean  | Standard Deviation |
|------------|--------|---------------|-------|--------|-------|--------|--------|--------------------|
| first_name | string |            42 | False | 12     |       |        |        |                    |
| last_name  | string |            19 | False | 24     |       |        |        |                    |
| age        | int    |            30 | False | 3      |     8 |    102 |     37 |             18.324 |
| weight     | float  |            56 | True  | 3,2    | 35.61 | 245.39 | 146.70 |             25.386 |

csvstat wouldn't have to do the formatting, of course...it just needs a CSV output option, and the formatting/header order can be handled by the user piping through csvcut/csvlook. I'll try to hack away at it and maybe make a pull request if I make something usable.

**Comment by dannguyen** [comment]
Here's a draft implementation...I'll clean it up after I get a better idea of how to best refactor `csvstat.py`: https://github.com/dannguyen/csvkit/commit/afce5362823d9be97a202b1376090df324ed0baa

Proposed usage is a `--as-csv` flag. Not sure if it's worth throwing in another flag to configure how many example values are shown...for some tables, an example value might be massive (e.g. for text fields):

```sh
$ curl -s http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.csv \
      | csvstat --as-csv
```


Here's a gist that shows sample output:
 
https://gist.github.com/dannguyen/3917a4b5c9550a910c3434e30e6896bd

**Comment by KarolTx** [comment]
Looks great :)
