### ISSUE TITLE
csvclean returns no errors BUT...

### ISSUE THREAD

**Issue by 7starsone** [wireservice/csvkit#586]
Hello :-)
installed on CentOS 7

but on a .csv file with tab delimiter just from the 3rd row there are 14 columns instead of 15... and it passes with "no errors" lol how is possible?

then... I have the header with the very first column named eg "name" and it returns that name is not there lol "Column identifier "name" is neither an integer, nor a existing column's name."

what's... ?

**Comment by 7starsone** [comment]
***header***
name|brand|descrizione|prezzolistino(ii)|prezzorivenditore(ie)|codice|linkscheda|disponibile|categoria|urlimg|ext1|ext2|ean|qtadisp|listaimg

***3rd row***
"7959 STAR WARS...  | Lego | Sul desolato... | 56,99|42,83|7959|http://www.website.com/prodotti_dettaglio.php?id_pro=1004|non disponibile | lego -  | http://www.website.com/catalogo/img/774_1313759777.jpg |  |  |  |  | http://www.website.com/catalogo/img/774_1313759777.jpg,http://www.website.com/catalogo/img/774_13137597772.jpg"

**Comment by jpmckinney** [comment]
Please provide the CSV, otherwise impossible to test.
