### ISSUE TITLE
Pinned dependencies a bit of an issue

### ISSUE THREAD

**Issue by dartdog** [wireservice/csvkit#587]
Love the package and features! Great work.

It seems that the dependencies are pinned to specific revs rather than the minimum required revision. While I appreciate The issue you are trying to avoid,   when updating other packages which have the same pkg dep but get updated versions it breaks csv kit.. Date utilit most recently

**Comment by jpmckinney** [comment]
I believe this is fixed in the unreleased version. Try:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by dartdog** [comment]
fantastic, Thanks! This has become the default 1st thing I use with any incoming file

**Comment by dartdog** [comment]
Oopse I did resintall as suggested but csvkit fails, is still looking for python-dateutil==2.2 and Pandas now asks for python-dateutil (2.5.1) so it is in conflict

**Comment by jpmckinney** [comment]
Ah, you're right. We need to close #490 an #497 first.

**Comment by dartdog** [comment]
Think this might ought to be listed as open? Warning others? As well as reminder to fix the dependency?

**Comment by jpmckinney** [comment]
We already have open issues for this issue. We don't need duplicates.

**Comment by dartdog** [comment]
ok thanks
