### ISSUE TITLE
Tip: Pipe multiple files into csvjoin

### ISSUE THREAD

**Issue by timwis** [wireservice/csvkit#590]
Hey guys, I noticed in [the docs](http://csvkit.readthedocs.org/en/540/tricks.html#specifying-stdin-as-a-file) a tip about piping a file to commands like `csvjoin`. In my case, I wanted to pipe the results of multiple streams into `csvjoin` for a [data workflow](https://github.com/CityOfPhiladelphia/property-assessments-data-pipeline), so I did some digging and came across [named pipes](http://www.linuxjournal.com/article/2156). For example, if you want to cut 2 files before joining them:

```bash
csvjoin -c "id,id" <(csvcut -c 2,5,6 file_a.csv) <(csvcut -c 1,7 file_b.csv)
```
Thought it might be handy to mention in the tricks section if you're interested.

**Comment by jpmckinney** [comment]
Sure! A good trick to share. Can you write a PR?

**Comment by timwis** [comment]
Thanks! Sorry that I never got round to writing this up :-/

**Comment by jpmckinney** [comment]
No worries, easy fix :)
