### ISSUE TITLE
Docs default to old version

### ISSUE THREAD

**Issue by timwis** [wireservice/csvkit#591]
Hey guys, forgive me if this is intentional, but going to csvkit.readthedocs.org redirects you to http://csvkit.readthedocs.org/en/0.9.1/ with an alert box at the top telling you that you're not viewing the latest version, offering a link to http://csvkit.readthedocs.org/en/540/

Is this intentional? Why wouldn't the docs default to the latest version?

**Comment by jpmckinney** [comment]
It's not intentional - I don't know what causes that alert box.

**Comment by timwis** [comment]
According to [read the docs docs](http://read-the-docs.readthedocs.org/en/latest/versions.html#redirects-on-root-urls) I think the problem is [this line](https://github.com/wireservice/csvkit/blob/0.9.1/docs/conf.py#L44) in `conf.py`. Perhaps the solution is just to comment out that line entirely? (Forgive me, I've never used read the docs other than as a reader)

**Comment by jpmckinney** [comment]
@onyxfish Can you have a look? I don't have access to the Readthedocs account of the GitHub webhooks.

**Comment by timwis** [comment]
According to @mjumbewu, you can click the `Admin` button in the readthedocs project, then under `Advanced Settings` there's a `Default version` textbox. You can change that to `latest` to show the latest docs by default.

**Comment by timwis** [comment]
Hey folks, FYI this has happened again

**Comment by jpmckinney** [comment]
Fixed, thanks for reporting!

It seems readthedocs automatically promotes a numeric branch as the latest branch. I guess we'll just remember to only push alphanumeric branch names.
