### ISSUE TITLE
Working with big files

### ISSUE THREAD

**Issue by inkrement** [wireservice/csvkit#592]
I have to analyse big csv files and I tried this toolkit. So I have some questions and maybe ideas for enhancements. 

* csvstat returns an error if the file is not utf8 encoded and prints some message like "please use param -e if not utf8" - But this message is not printed immediately... instead the message pops out after some time which was annoying because the computer was processing a while (~ 10min). 

Are there any tips or best practices how to process big files with csvkit (especially csvstat)?

**Comment by jpmckinney** [comment]
Merging into #581
