### ISSUE TITLE
moving to CLI to script?

### ISSUE THREAD

**Issue by dberansky** [wireservice/csvkit#593]
My current process (that came out of manual exploratory work) is to run a number of piped csvkit tools and save the results into a file. Then load the file into pandas for further processing. Here's and example of one such chain:

```
find /mnt/logs/compress -name "cx*.csv" -print0 |
    xargs -0 csvstack --filenames |
    csvgrep -c versions -i -m "N/A" |
    csvgrep -c version -r ".+"     |
    csvcut -c group,vendor,serial,versions

```

I am moving to automate data processing and I don't want to deal with both batch scripts and python scripts. I want to have everything running in python. I already have code for enumerating files (i.e. py replacement for `find`); it's csvkit specific processing that I'm having a difficulty with.

csvkit is already written in python, but as far as I could tell there is no straight forward migration path from CLI to py.

Did I overlook something? What are the recommendations?

subproccess from python isn't an option because the script has to be runnable on various linux/windows/mac systems and I don't want to have system level dependencies outside of python (that's also why I don't want to use a batch file to run this).

**Comment by jpmckinney** [comment]
Hi @dberansky, CSVKit uses the agate library for most of its functionality: https://github.com/wireservice/agate I recommend using agate directly to implement that functionality.
