### ISSUE TITLE
Upload v1 to pip

### ISSUE THREAD

**Issue by dan-may** [wireservice/csvkit#594]
As far as I can tell, v1 is the current supported version of csvkit, according to the changelog in this github repository, and according to the documentation page.

However, PyPI still lists 0.9.1 as the most recent update: https://pypi.python.org/pypi/csvkit

I am currently referencing the git repository in my requirements file, but would like to be able to reference the official PyPI package so I can hardcode my requirements to v1.0.0 instead of being subject to whatever is currently in the github repository.

Cheers

**Comment by jpmckinney** [comment]
v1 isn't ready yet, but you can set your requirements.txt to refer to a specific commit, so that the csvkit dependency doesn't change when we make new commits.

**Comment by dan-may** [comment]
Thanks for the clarification.

Have tagged my git reference to the latest commit in master.
