### ISSUE TITLE
Why sniff limit option is only in csvsql?

### ISSUE THREAD

**Issue by bryant1410** [wireservice/csvkit#600]
I am trying to read a file which works out-of-the-box with csvlook and csvcut (and others), but after some time I realize that with csvsql it was not working. Then I figured out that a sniffing is enabled for this command (and only this one), which particularly fails to discover the quoting char. So I reach `--snifflimit` flag, and I wanted to know, why is this option available only for this command?

**Comment by jpmckinney** [comment]
`--snifflimit` exists on csvsort, csvstat, in2csv.

In the upcoming version 1.0, it's been added to csvjson and csvlook.

`--snifflimit` is implemented on any tool that reads an entire CSV file at once. For tools that can process on row at a time, like csvcut, it is not implemented.

**Comment by bryant1410** [comment]
Makes sense. But I think it is a problem that files are out-of-the-box parsed differently depending on the command used. Maybe letting the sniff limit in 0 by default?

**Comment by bryant1410** [comment]
Or maybe that all commands accept this flag, and all with 0 by default.

**Comment by jpmckinney** [comment]
In general, snifflimit does exactly what people expect. Changing the default would cause a lot more problems for a lot more people. Just pass a snifflimit of 0 on the command-line to turn it off.
