### ISSUE TITLE
Take into account the row size limit in csvsql

### ISSUE THREAD

**Issue by bryant1410** [wireservice/csvkit#602]
Like, for example, [this SO answer states about MySQL](http://stackoverflow.com/a/332805/1165181).

**Comment by onyxfish** [comment]
Unfortunately, this is going to be almost impossible to support across dialects. The best we might be able to do is issue a warning for very long fields, however, I'd rather just say this is outside the tool scope. If you have huge fields best to use csvsql to create the schema, tweak as needed, and then import data directly into the table.
