### ISSUE TITLE
XLS only: time >= 24:00 renders invalid result

### ISSUE THREAD

**Issue by crazyshot** [wireservice/csvkit#605]
When at least one cell in the XLS document has time equal or greater than 24:00:00, it renders ONLY this cell numeric content instead of whole document:

> `in2csv ~/Documents/test-in2csv.xls`
> 1.04166666667
> 
> `in2csv -v ~/Documents/test-in2csv.xls`
> Traceback (most recent call last):
>   File "/usr/local/bin/in2csv", line 11, in <module>
>     sys.exit(launch_new_instance())
>   File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 82, in launch_new_instance
>     utility.main()
>   File "/usr/local/lib/python2.7/site-packages/csvkit/utilities/in2csv.py", line 76, in main
>     data = convert.convert(self.input_file, filetype, *_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/csvkit/convert/**init**.py", line 37, in convert
>     return xls2csv(f, *_kwargs)
>   File "/usr/local/lib/python2.7/site-packages/csvkit/convert/xls.py", line 144, in xls2csv
>     t, normal_values = NORMALIZERS[column_type](values, datemode=book.datemode)
>   File "/usr/local/lib/python2.7/site-packages/csvkit/convert/xls.py", line 54, in normalize_dates
>     v_tuple = xlrd.xldate_as_tuple(v, datemode)
>   File "/usr/local/lib/python2.7/site-packages/xlrd/xldate.py", line 86, in xldate_as_tuple
>     raise XLDateAmbiguous(xldate)
> xlrd.xldate.XLDateAmbiguous: 1.04166666667

If same document is saved as XLSX, everything fine:

> `in2csv -v ~/Documents/test-in2csv.xlsx`
> Time
> 15:23:00
> 1.04166666667
> 17:23:00

**Comment by jpmckinney** [comment]
Thanks for reporting. Could you upload a sample XLSX file to test with?

**Comment by jpmckinney** [comment]
Can't resolve issue without sample file.
