### ISSUE TITLE
install and 'using csvkit as a python library' docs for 540 are missing

### ISSUE THREAD

**Issue by skorasaurus** [wireservice/csvkit#608]
Hi, 

I noticed a few of the docs ([The install page](https://csvkit.readthedocs.io/en/540/install.html)
and [using csvkit as a library](https://csvkit.readthedocs.io/en/540/lib.html))  aren't built for the newest version (540) that had previously existed for 0.9.1.

**Comment by jpmckinney** [comment]
Thanks - dupe #591
