### ISSUE TITLE
csvsort behaves as though --skipinitialspace is set

### ISSUE THREAD

**Issue by uji-villapla** [wireservice/csvkit#609]
**csvsort** removes initial whitespace from fields by default (note white space before 'z' on column 'C'):

```
$ printf "A,B,C\n1,2,3\nx,y, z\n0,0,0\n" | csvsort
A,B,C
0,0,0
1,2,3
x,y,z
```

other utilities don't:

```
$ printf "A,B,C\n1,2,3\nx,y, z\n0,0,0\n" | csvformat 
A,B,C
1,2,3
x,y, z
0,0,0
```

unless you request it:

```
$ printf "A,B,C\n1,2,3\nx,y, z\n0,0,0\n" | csvformat --skipinitialspace
A,B,C
1,2,3
x,y,z
0,0,0
```

Regards,
                   Juanjo

**Comment by uji-villapla** [comment]
Sorry, forgot to mention the csvkit version I'm using:

```
$ pip list | grep csvkit
csvkit (0.9.1)
```

**Comment by jpmckinney** [comment]
Produces the bug in HEAD as well.

**Comment by jpmckinney** [comment]
@nbedi @onyxfish This seems to be an agate bug.

**Comment by onyxfish** [comment]
Fascinating. Ticketing upstream.

**Comment by onyxfish** [comment]
Fixed upstream. Require new version of agate.
