### ISSUE TITLE
sql2csv: Support encoding flag for query files (--query-encoding)

### ISSUE THREAD

**Issue by jonashaag** [wireservice/csvkit#614]
```
$ sql2csv ...
...
Your file is not "utf-8" encoded. Please specify the correct encoding with the -e flag.
Use the -v flag to see the complete error.

$ sql2csv ... -e 'iso-8859-1'
usage: sql2csv [-h] [-v] [-l] [--db CONNECTION_STRING] [--query QUERY] [-H]
               [FILE]
sql2csv: error: argument FILE: can't open 'iso-8859-1': [Errno 2] No such file or directory: 'iso-8859-1'
```

**Comment by jpmckinney** [comment]
Can you provide a sample file?

**Comment by jonashaag** [comment]
This doesn't have anything to do with my input fine. It's simply that the -e option is not implemented.

**Comment by jpmckinney** [comment]
To reproduce the first error:

    sql2csv examples/test_latin1.csv

**Comment by jpmckinney** [comment]
sql2csv accepts a SQL query as an argument, not a CSV file. The -e option only applies to input CSV files. Why is your SQL query stored in a non-UTF-8 file?

**Comment by jonashaag** [comment]
> Why is your SQL query stored in a non-UTF-8 file?

I don't know, it's simply what comes out of `mysqldump`

**Comment by todofixthis** [comment]
`mysqldump` should default to using UTF8 as the character set for its output ([source](http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_default-character-set)).  If necessary, you can instruct it to use a different character set via the `--default-character-set` option.

Are you running `mysqldump` on Windows?  See this note in the [mysqldump documentation](http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_result-file):

> **Note**
>
> A dump made using PowerShell on Windows with output redirection creates a file that has UTF-16 encoding:
> 
>     shell> mysqldump [options] > dump.sql
> However, UTF-16 is not permitted as a connection character set (see Section 11.1.4, “Connection Character Sets and Collations”), so the dump file will not load correctly. To work around this issue, use the `--result-file` option, which creates the output in ASCII format:
> 
>     shell> mysqldump [options] --result-file=dump.sql

**Comment by jonashaag** [comment]
No, Linux/Mac OS but the table is in Latin1
