### ISSUE TITLE
csvlook: Flag for Multi-Markdown friendly output?

### ISSUE THREAD

**Issue by brentajones** [wireservice/csvkit#620]
Not sure if this is a feature that would be useful to many. There have been a few occasions where I'd like the output of csvlook to be a [Multi-Markdown table](http://fletcher.github.io/MultiMarkdown-5/tables.html). It's _very_ close to being compatible as it is. 

Here are the changes I just made to a very simple table to change from csvlook output to make a Markdown-friendly table:

- Remove top and bottom "frame" rows (the pipe, dashes and plus signs on the first and last line).
- Remove pipes at beginning and end of lines
- Change plus signs in separator rows to pipes

**Comment by jpmckinney** [comment]
Thanks @brentajones. csvkit uses [agate](https://github.com/wireservice/agate) to render the table, so I recommend re-opening the issue over there.

**Comment by jpmckinney** [comment]
You can try https://github.com/pstaender/csv2md
