### ISSUE TITLE
Lack of releases/tags - possibility of tagging and releasing distinct releases?

### ISSUE THREAD

**Issue by thor** [wireservice/csvkit#622]
Hi,

As both a person heavily relying on csvkit for all sorts of exporting and importing (thanks!) and someone who likes to package software, I was wondering if you could forewards from here -- or even now, just as easily really -- to tag the new versions that you release of csvkit with a version number in the repository as well! 👍 

I mention this because currently the last tag is v0.9.1, but that's ancient! There's been so many useful updates, and it'd be nice to be able to package them when they come out.

Furthermore, it'd be great if you could do this in tandem with updating the PyPI version. That'd make life easier for both developers and packagers alike.

**Comment by jpmckinney** [comment]
We're working towards 1.0.0. The current master has many breaking changes from 0.9.1, but it's not yet ready for 1.0.0 - there are some medium/high priority issues we need to close first. For now, I've been recommending people install the GitHub version.
