### ISSUE TITLE
csvlook 1.0 unable to read from stdin, raises error "underlying stream is not seekable"

### ISSUE THREAD

**Issue by dannguyen** [wireservice/csvkit#623]
In csvkit 0.9.1, you could do this:

```sh
$ csvcut -c 1,2,3 examples/iris.csv | csvlook
|---------------+-------------+---------------|
|  sepal_length | sepal_width | petal_length  |
|---------------+-------------+---------------|
|  5.1          | 3.5         | 1.4           |
|  4.9          | 3.0         | 1.4           |
|  4.7          | 3.2         | 1.3           |
|  4.6          | 3.1         | 1.5           |
```

In 1.0, this error is raised: `underlying stream is not seekable`. This seems like it would be expected behavior for `csvsort`, but doesn't seem necessary for `csvlook`:

https://github.com/wireservice/csvkit/blob/master/csvkit/utilities/csvsort.py#L31

(actually, is it necessary for csvsort? Doesn't csvstat essentially require the entire input to be read before it can do its aggregation? I guess that can be saved for another issue/feature request)

**Comment by jpmckinney** [comment]
I'll apply the same fix as in `csvsort`. `csvlook` needs to read the entire input to draw the table properly.
