### ISSUE TITLE
csvsort memory limit

### ISSUE THREAD

**Issue by simogeo** [wireservice/csvkit#626]
Hi,
I've tried to sort a 1 Gb (only) file with csvsort and `-c` option ... My computer ends up freezing and using all memory (12 Gb) 

Is that "normal" ? is that a known issue ? I've also seen issues #581 and #338. 
Is there any tip to do so. Thanks

**Comment by jpmckinney** [comment]
Is it faster with `--no-inference`?

**Comment by simogeo** [comment]
I'll try it soon ... but it looks like a memory leak more than a performance issue ...

**Comment by simogeo** [comment]
same behaviour with `no-inference` option.

Here is the whole command line : 

```
csvsort -d ";" --no-inference  -c DCLT ./FD_MOBPRO_2011.txt > ./FD_MOBPRO_2011-order-by-lieu-de-travail-test.txt
```

**Comment by onyxfish** [comment]
@simogeo You could try this with the `1.0.0` release, but realistically sorting a 1GB file is unlikely to ever be performant with csvkit. That's pretty far outside the intended use-case.

**Comment by simogeo** [comment]
got it. Thanks
