### ISSUE TITLE
Allow `-H` to relabel headers

### ISSUE THREAD

**Issue by solidsnack** [wireservice/csvkit#628]
Consider data sources that generate CSV without headers -- this might be due to chunking or something similar in a processing pipeline.

With `-H` as it stands we can use this data but the resulting query code is confusing. If `-H` or a related argument accepted a comma separated list of new column names, it would alleviate the confusion thus resulting.

A penny for your thoughts.

**Comment by jpmckinney** [comment]
Can you explain what's confusing?

**Comment by jpmckinney** [comment]
Closing - over a month without clarification.
