### ISSUE TITLE
Add option to in2csv to list sheet names

### ISSUE THREAD

**Issue by khughitt** [wireservice/csvkit#632]
When converting multi-sheet excel spreadsheets to CSV, the `--sheet` option for `in2csv` is needed.

Currently, I don't believe there is any way to _list_ the sheets in the document without viewing it in something external like Excel or LibreOffice.

Would it be possible to add an option to list all available sheets? It may even be worth making this the default behavior for in2csv when multiple sheets are present and no specific sheet is specified -- this way a user doesn't accidentally grab the first sheet without realizing there are others.

**Comment by onyxfish** [comment]
Very useful idea. Bumping priority.
