### ISSUE TITLE
csvsql Killed 

### ISSUE THREAD

**Issue by NickBuchny** [wireservice/csvkit#633]
I've been attempting to use csvsql to create a table from an ~4gb .csv file and after around 10-15 minutes the ubuntu terminal returns 'killed'. I'm generally new to using this module etc. so if you need more information let me know. 

Input:

csvsql train.csv

csvsql --no-contraints train.csv 

output:

killed

edit: if anyone could let me know what's happening/give another route I'd appreciate it

**Comment by vielmetti** [comment]
Can you run the "top" command while this is going on - you might be running out of some system resource along the way.

**Comment by jpmckinney** [comment]
If you run `csvsql -v` you should see some more verbose output.

**Comment by BrochineLearning** [comment]
Will do! In the middle of summer finals but I'm picking my project up right after.

**Comment by aoa4eva** [comment]
I'm having a similar problem, but with a file that's about 40Mb. There is no additional output when use -v, just "Killed". 

The table is created, but is empty, and so running the same command a second time does actually yield verbose input indicating that the table already exists.

**Comment by polvoazul** [comment]
I suspect your RAM was full! Search for 'oom killer'

**Comment by aoa4eva** [comment]
Thanks. Where do I search for this?

**Comment by polvoazul** [comment]
If you are on linux you can increase the size of your swap partition, it will save your program from being killed, but it will probably slow everything down, as the OS will use HDD as substitute for memory and it is MUCH slower.
I suggest closing everything that consumes memory (browser is a big one) before running the memory intensive program.
Your ideia of splitting the files is probably the best solution for big files.
Buying more RAM is also good, it is cheap and the whole system can benefit from it automatically (through OS file caches)

**Comment by aoa4eva** [comment]
It's running on a cloud server, so there's no browser, but I'll get more memory if I need to process more files. So far, it's just the one. Thanks for your help!

**Comment by dannguyen** [comment]
csvsql is not performant on huge data, last I tried (and remembered from the docs). I recommend that you use csvsql for just creating schemas or for smaller jobs, and pipe your CSV data into a database using another tool. csvkit is great for getting the data ready for a database. I don't think it was meant for big data tasks.

As an example of another tool, datanews/tables, when i used it a long while ago when it was still in development, worked quite beautifully. It's a CLI tool too, but built in node:

https://github.com/datahoarder/fec_individual_donors#use-datanewstables-a-data-to-sql-importer-in-nodejs

**Comment by aoa4eva** [comment]
It worked when I split the file into a max of 20k records. Took some
experimentation.

Wrote a script to load each of the split files and it worked well.

**Comment by onyxfish** [comment]
Closing this since there was a resolution. Opened a documentation ticket #735.
