### ISSUE TITLE
sql2csv: Please explain UTF-8 decoding problem

### ISSUE THREAD

**Issue by chris-hailstorm** [wireservice/csvkit#635]
I'm running a MySQL query using sql2csv.  The columns involved all have utf8_general encoding.

The first several rows are returned.  Once a row is reached that includes a non-ASCII character, I get this error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xae in position 47: ordinal not in range(128)

This happens whether generating output to screen or redirecting into a file.

However by putting a debug trace in unicsv.py, I can see self.encoding is set to utf-8, which seems correct. The problem is not improved by the "-e" option nor by exporting PYTHONIOENCODING env var.

Can you suggest an approach?

**Comment by chris-hailstorm** [comment]
I just found what seems like the answer.

Add to the end of the SQLAlchemy connection string: `?charset=utf8&use_unicode=True` and no more error.  This is equivalent to setting those session variables via the `SET` operation in a SQL statement.

Odd since utf8 is configured on the DB side for all character sets and collations.  I suppose it's possible there's something happening in the driver that doesn't obey those global and session vaiables.

**Comment by onyxfish** [comment]
Not sure what to say about this, but it seems to be a MySQL configuration issue. The SQLAlchemy docs actually specifically say [not to use](http://docs.sqlalchemy.org/en/latest/dialects/mysql.html) the `use_unicode` flag.

Closing out, but feel free to reopen if there are more specifics for debugging.
