### ISSUE TITLE
Shell completion using genzshcomp

### ISSUE THREAD

**Issue by olejorgenb** [wireservice/csvkit#636]
https://pypi.python.org/pypi/genzshcomp/0.5.2

> Automatic generate to Zsh Completion Function from Python’s Option Parser Modules.
> 
> Now, It corresponds to argparse module and optparse module.

It works well (all options are correctly completed) out out the box, but have some rough edges (doesn't understand completion fo comma separated lists)

If there's interest I can attempt a PR.

**Comment by jpmckinney** [comment]
Thanks, @olejorgenb. csvkit has so far been wary of introducing new dependencies. @onyxfish Any thoughts on this?

**Comment by jpmckinney** [comment]
The package mentioned hasn't been updated in a while, and I'm wary to add auto-complete for just one shell (what about fish, etc.), which can lead to having to support many more shells (a necessary headache for projects like Homebrew). There hasn't been more demand, so closing.
