### ISSUE TITLE
csvsort is corrupting data

### ISSUE THREAD

**Issue by polvoazul** [wireservice/csvkit#637]
I have noticed strange behaviour in csvsort.  First, it outputs dates in other format YYYY-MM-DD instead of DD/MM/YYYY of the other tools, apart from that it also **CHANGED** some of my data!

Please see if you can reproduce this. I have tested it in two different **Windows** (i know, i know...) machines. Using python3, csvkit@master. (It would be usefull to add a csvkit --version argument)

```
$cat file.csv
a,b,c
00125867,01/01/2011,31/01/2011
00125868,01/12/2004,31/12/2004
00126017,01/01/2008,30/12/2008
00126025,01/01/2005,31/12/2010
```

Notice how, after applying csvsort the dates in column c are srewed up. It also assumed that column a is an int and removed the leading zeroes!

```
$csvsort -ca file.csv
a,b,c
125867,2011-01-01,3101-01-01
125868,2004-01-12,3101-01-01
126017,2008-01-01,3001-01-01
126025,2005-01-01,3101-01-01
```

**Comment by jpmckinney** [comment]
What if you run csvsort with `--no-inference`?

**Comment by jpmckinney** [comment]
No clarification received.
