### ISSUE TITLE
in2csv adds a .0 decimal at the end of xls files

### ISSUE THREAD

**Issue by ethervoid** [wireservice/csvkit#639]
We've found some strange behavior. When we use in2csv to transform a xsl file with number columns as text, it adds a .0 at the end but in xlsx files not.

What could be the cause?

Example:

```
ubuntu@cdb-dev:/tmp$ in2csv dummy_dataset.xls
a, b, c,lat,lon,d
1.4326,true,thisIsText,37.34,-2.78,234.0 #HERE
2.3857,false,soIsThis,40.34,-1.94,567.0 #AND HERE
,,,,,text
ubuntu@cdb-dev:/tmp$ in2csv dummy_dataset.xlsx
a, b, c,lat,lon,d
1.4326,true,thisIsText,37.34,-2.78,245 #HERE DONT HAVE .0
2.3857,false,soIsThis,40.34,-1.94,567 #HERE DONT HAVE .0
,,,,,text
```

Here are the example files [test.zip](https://github.com/wireservice/csvkit/files/361727/test.zip)

**Comment by jpmckinney** [comment]
XLS files and XLSX files store numbers in different ways. XLSX has integers. XLS doesn't. That's reflected in the conversion.

**Comment by alexcaglairi** [comment]
Hi, I have this orrible problem using XLS files! i convert from xls to csv using " in2csv file.xls --no-inference -e utf-8| csvformat -D ";" > test.csv " and after every field that contains only numbers i find a .0 decimal at the end, even if the cell format is set to TEXT. How can i do?

**Comment by jpmckinney** [comment]
The problem is with the XLS file. csvkit isn't doing anything to add a `.0`.

**Comment by alexcaglairi** [comment]
It's impossible, because even if i set all cells format to "Text" i have a 
decimal .0 in every cell that contains only numbers (in the converted .csv 
file).

In data 28 Maggio 2020 22:57:55 James McKinney <notifications@github.com> 
ha scritto:

**Comment by yongchao** [comment]
I am stumped into this problem, while other tools such as ssconvert and libreoffice --headless don't have such a problem with the excel file. I don't think the problem is related to the xls file, and it has more to do how to parse the xls file.

**Comment by jpmckinney** [comment]
csvkit uses xlrd, which [documents here](https://xlrd.readthedocs.io/en/latest/api.html#xlrd.sheet.Cell) that in XLS files there are very few cell types and only one number type (`XL_CELL_NUMBER`) which gets converted as a float.

If other tools omit the `.0`, they must be using cell formatting information to do that. csvkit doesn't take cell formatting into account (then we'd get complaints about currency symbols missing, people wanting to maintain six digits of decimal precision, etc. – there's a lot of formatting options in Excel!).

**Comment by jpmckinney** [comment]
If anyone wants to upload an XLS file where the cells are XL_CELL_TEXT type and not XL_CELL_NUMBER type, and still produce a `.0` with csvkit, I'll at least have an input to debug with.

**Comment by yongchao** [comment]
[ex1.xls.pdf](https://github.com/wireservice/csvkit/files/5469717/ex1.xls.pdf)

As github doesn't support attach a file with .xls extension. Please remove the .pdf extension. 

If the .xls file doesn't show properly.  You can download the xlsx file (with the same content) (the link is at the end of this message) and save it as xls file using LibreOffice calc tool or other similar tool

Please note the first column are all integers (probably XL_CELL_NUMBER type), not the exactly the same format as you requested, but this is an example to start to do comparisons with other tools.

This is one example example. the commands to check them by the following commands.
`in2csv -I ex1.xls`
The ssconvert command 
`ssconvert ex1.xls ex1_ssconvert.csv`
The libraoffice --headless command
`libreoffice --headless --convert-to csv ex1.xls --outdir /tmp`

Please note that for in2csv, it also had another bug on the dates. inc2csv treated the dates as a float number while the other two got the dates correctly.  

The bugs of adding ".0" and saving the date as a float only occurred when using xls file as the input file for in2csv. in2csv has no bugs for the xlsx input file.
The xlsx has the same content as the xls file has been attached here.
[ex1.xlsx](https://github.com/wireservice/csvkit/files/5469721/ex1.xlsx)

**Comment by jpmckinney** [comment]
Sometimes dates are treated as float for the [reasons described by xlrd here](https://xlrd.readthedocs.io/en/latest/dates.html).

I'm fairly certain this is an xlrd "issue", though I don't think its authors would consider a bug, because xlrd isn't intended to fix problems in the XLS format itself.

Since there are methods using ssconvert and libreoffice to convert XLS to CSV without trailing .0 characters, I don't think there's much motivation to change csvkit's behavior (especially since XLS isn't Excel's default since 2007).

**Comment by yongchao** [comment]
Ye, I agree with you that it is an issue with xlrd.

It will be ideal that in2csv behave the same behavior between xlsx and xls file.

Anyway, my current solution is to have script wrapper to deal with the annoying problems.  I am receiving hundreds of files. It's not realistic for me to use the libraoffice calc to convert all .xls files to .xlsx files (or ,csv files) manually.

**Comment by puste1** [comment]
Still have the same issue. Have try both with xls and xlsx and do not make any different.

**Comment by LinuxVLT** [comment]
I have same problem wth xlsx files.
