### ISSUE TITLE
csvsql: add --pretty option

### ISSUE THREAD

**Issue by Flimm** [wireservice/csvkit#641]
It would be nice of the output of `csvsql` was a pretty table, similar to the default formatting for the `mysql` prompt, perhaps enabled with the flag `--pretty`. For example:

    $ csvsql --pretty --query "select * from people" people.csv
    +----+------------+-----------+
    | id | first_name | last_name | 
    +----+------------+-----------+
    | 1  | jack       | tale      |
    | 2  | jill       | tale      |
    +----+------------+-----------+

**Comment by jpmckinney** [comment]
Just pipe the output to csvlook:

```
csvsql --query "select * from people" people.csv | csvlook
```

**Comment by Flimm** [comment]
That's perfect. Thank you!

Here's an idea: why not include an example like that in the EXAMPLES section of `csvquery`'s documentation?

**Comment by jpmckinney** [comment]
`csvlook` comes up in the Tutorial. We can add it to `csvsql`'s docs, but in that case it would make sense to add it to every tool's docs. I think it's better to just encourage people to learn all the tools and how to combine them, which is what the Tutorial does.
