### ISSUE TITLE
csvsql: it should ignore BOM

### ISSUE THREAD

**Issue by Flimm** [wireservice/csvkit#642]
If the CSV file is UTF-8 encoded, and if it begins with a BOM, then `csvsql` will create a table, where the first column's name begins with a BOM. At least it does in MySQL.

**Comment by jpmckinney** [comment]
Note: may be fixed by #494

**Comment by jpmckinney** [comment]
Based on #662, csvcut exhibits the same issue, so #494 will likely not fix

**Comment by jpmckinney** [comment]
Actually, the solution is to run the command with `-e utf-8-sig`

Added to docs: https://github.com/wireservice/csvkit/commit/81f6f3a8d3413ac0eb8fb180c1452870fb65d7f3
