### ISSUE TITLE
New utility: csvdiff

### ISSUE THREAD

**Issue by codex-paulus** [wireservice/csvkit#643]
I work a lot with CSV files and have found csvkit very helpful (thanks!). Often I need to compare data dumps and so I've created csvdiff to compare two csv files and output a diff also in csv format.  Csvdiff can use a column or columns as a key and compare the files based on this.  It also supports fuzzy matching for values that can be converted to a float.  This helps when two values are not exactly the same but close enough for your purposes.  If others would find this useful I'd like to contribute my code.

Example:
```
$ cat t1.csv
A,1
B,2
C,3

$ cat t2.csv
B,2
C,4
D,5

$ csvdiff t1.csv t2.csv -H -k 1 | csvlook
|---------------+--------------+---------------+----------------|
|  left_column1 | left_column2 | right_column1 | right_column2  |
|---------------+--------------+---------------+----------------|
|  A            | 1            |               |                |
|  C            | 3            | C             | 4              |
|               |              | D             | 5              |
|---------------+--------------+---------------+----------------|
```

**Comment by jpmckinney** [comment]
We recommend using http://paulfitz.github.io/daff/
