### ISSUE TITLE
convert csv file to xml (sepa)

### ISSUE THREAD

**Issue by Heart1010** [wireservice/csvkit#647]
I just found your fantastic csvkit and I'm really excited what csvkit is able to do.

So I just ask here for a new conversion tool which can **convert a csv file to a sepa xml file (direct debit)**. Is this possible or totally "out of scope" for csvkit? (good [explanation of the format](https://www.bundesbank.de/Redaktion/DE/Downloads/Aufgaben/Unbarer_Zahlungsverkehr/technische_spezifikation_sdd_kontoinhaber_ohne_bankleitzahl_februar_2014.pdf?__blob=publicationFile) in german)

_I can feed you with some example files (csv and xml) if you want..._

**Comment by jpmckinney** [comment]
Yes, specific export formats are out of scope. There's only csvjson to convert a generic CSV to JSON, and csvsql to import a generic CSV to the databases supported by SQLAlchemy.
