### ISSUE TITLE
Running csvsql --no-constraints against Oracle generates invalid varchar fields

### ISSUE THREAD

**Issue by rbrtmrtn** [wireservice/csvkit#648]
Running `csvsql --no-constraints -i oracle` will generate a  create statement with `varchar`/`varchar2` fields without lengths, which is invalid per Oracle and raises `ORA-00906: missing left parenthesis`.

Sample output:

```
CREATE TABLE csv_test (
        "PARCEL" VARCHAR2,
        "LOC" VARCHAR2,
        "OWNER1" VARCHAR2
)
```

**Comment by jpmckinney** [comment]
This would be a bug in SQLAlchemy: https://bitbucket.org/zzzeek/sqlalchemy/issues

**Comment by jpmckinney** [comment]
Issue needs to be reported to SQLAlchemy.
