### ISSUE TITLE
Parse non-US locale numbers

### ISSUE THREAD

**Issue by mhlr** [wireservice/csvkit#652]
Sometimes numeric data contains thousands separators, typically ',', '_' or  in Europe ','.
Also Europeans sometimes use ',' as the decimal point.

**Comment by jpmckinney** [comment]
Can you provide an example of a command that fails to handle one of these number formats?

**Comment by mhlr** [comment]
csvsql will treat such columns as varchar.

**Comment by onyxfish** [comment]
This is actually supported in agate via the `locale` parameter of the `Number` class, but has not been exposed through csvkit. Would def be useful.

**Comment by jpmckinney** [comment]
Would we just add a global flag that sets the `locale` parameter on the `Number` class in the `get_column_types` method?

**Comment by onyxfish** [comment]
I think that's exactly right, yes.
