### ISSUE TITLE
Cannot ADD a column to a CSV file

### ISSUE THREAD

**Issue by halloleo** [wireservice/csvkit#655]
I was looking at all the tools in `csvkit`, but couldn't find any tool to add/insert an empty column to a CSV file. Surely something which should be part of `csvkit`. 

I'm happy to get involved, but wanted to check whether there is an easy way to do this and I have overlooked it. The closest I got was the the `--linenumbers` option of `csvcut`.

**Comment by jpmckinney** [comment]
Thanks for the suggestion for a new CSV tool. However, the maintainers have decided to not merge and maintain new tools; there is simply not enough time to maintain new tools. Our focus is instead on making the existing tools as good as possible.

**Comment by halloleo** [comment]
Fair enough. But my question stands: Is there an easy way to insert a column I have overlooked? Thanks!

**Comment by jpmckinney** [comment]
You can create a file containing a single "," (let's call it `column.csv`) and then:

    csvjoin your-csv.csv column.csv > your-csv-with-a-new-column.csv

**Comment by jpmckinney** [comment]
Actually, even shorter:

    echo "," | csvjoin examples/your-csv.csv - > your-new-csv.csv

**Comment by halloleo** [comment]
When I run

```
echo "," | csvjoin file.csv -
```

I get (trying several different csv files) the error:

> local variable 'right_row' referenced before assignment

**Comment by halloleo** [comment]
Some details to the environment:
* OS is macOS 10.11.6
* python is 2.7.12 installed via homebrew
* csvkit is V0.9.1 installed via pip.

**Comment by jpmckinney** [comment]
You'll need to install the latest csvkit:

    pip install -e git+git://github.com/onyxfish/csvkit.git@master#egg=csvkit

**Comment by superurbi** [comment]
I also tried upgrading csvkit in Windows but I had a lot of problems with additional packages. So I remain in version 0.9.1. The only way I saw to easily add new columns with values was another utility called CSVFIX software for Windows. There is a command "csvfix put -p 1 -v "New-Value" "token_grow.csv" > "token_grow2.csv" which made the trick. [http://neilb.bitbucket.org/csvfix/manual/csvfix16/csvfix.html?put.html]

**Comment by ricecooker** [comment]
Another option is to just use awk. The following adds a column of 1337 to a csv (with headers).

```bash
cat file.csv | awk '{if(NR==1){print $0",new_column"}else{print $0",1337"}}' > added_column.csv
```

**Comment by halloleo** [comment]
Well, there are lots of ways to do this, but I guess such a basic operation as adding a column should be able to be done with csvkit itself...

**Comment by jpmckinney** [comment]
It can. As mentioned above:

    echo "," | csvjoin examples/your-csv.csv - > your-new-csv.csv

**Comment by lehoff** [comment]
As far as I can tell then

```
echo "," | csvjoin examples/your-csv.csv - > your-new-csv.csv
```

adds two columns called `a` and `b`.

```
echo "New column name" | csvjoin examples/your-csv.csv - > your-new-csv.csv
```

adds a single named column.

**Comment by lehoff** [comment]
As far as I can tell then

```
echo "," | csvjoin examples/your-csv.csv - > your-new-csv.csv
```

adds two columns called `a` and `b`.

```
echo "New column name" | csvjoin examples/your-csv.csv - > your-new-csv.csv
```

adds a single named column.

**Comment by jpmckinney** [comment]
Indeed, that's correct.

**Comment by randomizedthinking** [comment]
`csvstack` can be used to add a column by utilizing the grouping variable feature:

```sh
csvstack -n NEWCOL -g newval your-csv.csv
```

**Comment by jpmckinney** [comment]
@randomizedthinking Thanks! I've added it to the docs.
