### ISSUE TITLE
csvcut/py2.7: ascii' codec can't encode character u'\xf6'

### ISSUE THREAD

**Issue by biopsin** [wireservice/csvkit#657]
Hi,
I seem to have unicode issue, maybe a move to py3.4/3.5 solves my problem..

**Comment by jpmckinney** [comment]
Can you provide an example file and command?

**Comment by biopsin** [comment]
sure, [link to file](http://www.dn.no/finans/servlets/newt/json/stocks-excel?list=feed.ose.quotes.EQUITIES)
convert: in2csv stocks.xls > stocks.csv
csvcut -c 1,3,4 stocks.csv | csvlook > stocks.txt and here it brakes in column 1 on carracter õ

**Comment by jpmckinney** [comment]
Works fine with the unreleased version of csvkit on GitHub:

    pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit

**Comment by biopsin** [comment]
nice, thank you.
