### ISSUE TITLE
cvssql -H omits header in output and shouldn't

### ISSUE THREAD

**Issue by malcook** [wireservice/csvkit#658]
-H is documented to govern only the format of the input file

` -H , --no-header-row   Specifies that the input CSV file has no header row.
`

However, csvsql output omits header row in output when using  -H.

Arguably, the provided column names (i.e. "column1" "column2", etc) should be emitted in the output

(unless this is "by design", in which case probably the documentation should reflect this.  In any case some means of including the column names in the output would be grand)

**Comment by jpmckinney** [comment]
Thanks for reporting - fixed!
