### ISSUE TITLE
Byte order mark issues in csvsql and csvcut

### ISSUE THREAD

**Issue by CMCDragonkai** [wireservice/csvkit#662]
I used to have this command running:

```
csvsql \
--no-inference \
--query \
"SELECT Date, \`Paid Out\` FROM 'airbnb_${start}-${end}' WHERE Type = 'Payout';"
```

And it would work on a CSV file with a `Date` column.

Now when I try it complains that:

```
(sqlite3.OperationalError) no such column: Date [SQL: "SELECT Date FROM 'airbnb_2015-2016'"]
```

Why is `Date` failing to be selected now (it was working 1 year ago), what would be the solution to this error?

I tried with `csvcut` to get a `Date` column as well, and it didn't work. In fact it says:

```
Column identifier "Date" is neither an integer, nor a existing column's name.
```

Which is just not true.

**Comment by jpmckinney** [comment]
Can you provide a sample file? Are you using the version from GitHub?

    pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit

**Comment by CMCDragonkai** [comment]
Updating to your system has now revealed a different error message (for csvcut):

```
Column '\ufeffDate' is invalid. It is neither an integer nor a column name. Column names are: u'\ufeffDate', u'Type', u'Confirmation Code', u'Start Date', u'Nights', u'Guest', u'Listing', u'Details', u'Reference', u'Currency', u'Amount', u'Paid Out', u'Host Fee', u'Cleaning Fee'
```

**Comment by jpmckinney** [comment]
I haven't tried the following solution before, but what happens if you run `csvcut -e utf-8-sig` ...?

**Comment by jpmckinney** [comment]
I can confirm that `-e utf-8-sig` works.

**Comment by CMCDragonkai** [comment]
Can you add this to docs? And does this work on csvsql as well?

**Comment by jpmckinney** [comment]
`csvsql` works for me. I've added to docs.

**Comment by CMCDragonkai** [comment]
Is there a way not to auto detect the existence of the BOM, I found that I now need to add this flag to every call I make to csvkit utils (csvcut, csvgrep, csvsql...etc)

**Comment by jpmckinney** [comment]
Don't you only need to detect the BOM with the first command you run on the file? The output of commands shouldn't have the BOM. If you only use CSVs with BOMs, you can always create an alias in your shell like `alias bomcut=csvcut -e utf-8-sig`
