### ISSUE TITLE
csvjoin by column (fillup column)

### ISSUE THREAD

**Issue by markuman** [wireservice/csvkit#663]
$ cat this.csv 
	section; value
	A 12; bka
	C 1; genau
	D 2; gde
	$ cat auch.csv 
	section; value
	A 12; von 
	B 3; von
	C 1; von
	D 2; von
	$ csvjoin --outer -c "1" -d \; this.csv auch.csv 
	section, value,section, value
	A 12, bka,A 12, von 
	C 1, genau,C 1, von
	D 2, gde,D 2, von
	,,B 3, von

so it listed the column "section" two times.
I'd like to see

	$ csvjoin --outer -c "1" -d \; this.csv auch.csv 
	section, value,section, value
	A 12, bka, von 
	C 1, genau, von
	D 2, gde, von
	B 3,, von

Any ideas?

**Comment by jpmckinney** [comment]
Duplicates #210
