### ISSUE TITLE
json > csv tutorial

### ISSUE THREAD

**Issue by genfhk** [wireservice/csvkit#664]
I'm trying to convert a json file to csv (actually multiple json files, and only certain nested fields), but I'm completely new to json and don't know how to identify or express the 'key'(s). Is there a more detailed tutorial for this type of use case, or can you point me in the right direction? I've added a sample json file to help illustrate what I'm working with. 

[sample_digitized_audioreeldigital.json.zip](https://github.com/wireservice/csvkit/files/512786/sample_digitized_audioreeldigital.json.zip)

**Comment by onyxfish** [comment]
@genfhk I don't think what you're describing is possible with csvkit. You can convert the file with `in2csv my_file.json > out.csv` however you can't select specific fields with that tool. Nested fields will automatically be converted to `top_key/middle_key/bottom_key` style column names. You could then pipe the output to `csvcut` to remove columns you don't need, or just open the file in Excel and delete them.

Hope that helps!
