### ISSUE TITLE
Issue with six on install, El Capitan

### ISSUE THREAD

**Issue by mtdukes** [wireservice/csvkit#665]
Tried upgrading csvkit on El Capitan (10.11.6) and was getting issues with the step that's trying to uninstall Six. Saw a proposed fix to ignore installed packages, so I ran:

`sudo pip install csvkit --upgrade --ignore-installed six`

But still got the same error. Didn't look like any of the closed issues addressed this yet:

> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
>     status = self.run(options, args)
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1294, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 525, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1639, in remove
>     renames(path, new_path)
>   File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/util.py", line 294, in renames
>     shutil.move(old, new)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
>     copy2(src, real_dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
>     copystat(src, dst)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
>     os.chflags(dst, st.st_flags)
> OSError: [Errno 1] Operation not permitted: '/tmp/pip-ANaHWi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Any ideas on a fix?

**Comment by jpmckinney** [comment]
You should remove `six` from the above command. `--ignore-installed` doesn't take any arguments. Your command is actually asking `pip` to install `six`.
