### ISSUE TITLE
csvsql: Add MINFIELDSIZE to the csvkit

### ISSUE THREAD

**Issue by rogaha** [wireservice/csvkit#668]
I would like to be safe and create `varchar` fields with a minimum number of characters to avoid loading errors in the future, for my use-case I'm creating the table on each table load.

**Comment by jpmckinney** [comment]
Can you provide an example of how this would look on the command line?

**Comment by rogaha** [comment]
`csvsql -i postgresql invoices__2016-10-12_2016-10-12.csv --minfieldsize 512`, it would use the `MAX` between `512` and `max_lenght_found`.

**Comment by rogaha** [comment]
I can submit a PR if you can point me where does the current logic lives.

**Comment by jpmckinney** [comment]
The logic is in https://github.com/wireservice/csvkit/blob/master/csvkit/utilities/csvsql.py and possibly https://github.com/wireservice/csvkit/blob/master/csvkit/sql.py Thanks!

**Comment by onyxfish** [comment]
I'm going to close this as a bit too specific of a case. Best solution now would be to spit the table schema out to a file and modify it. Supporting all possible field flags with csvsql is a hopeless endeavor—especially given all the dialect differences.
