### ISSUE TITLE
Ability to run via library import?

### ISSUE THREAD

**Issue by chris-hailstorm** [wireservice/csvkit#670]
csvkit is wonderful as a command-line tool. I'm trying to figure out how to apply it from within other Python modules.  I'd rather avoid the subprocess approach -- would like to import and invoke the csvkit functions like typical Python functions.

I'm able to do something like this:

```
from csvkit.utilities.csvcut import CSVCut as c
c('-c 2 x4.csv'.split(' ')).main()
```

This produced the expected output in what looks like stdout.

When I try to capture the output, this simple approach fails:

```
result = c('-c 2 x4.csv'.split(' ')).main()
```
... the output is still printed and `result` is empty.

I tried creating a context manager that would capture stdout, with no luck.

How do you recommend the utilities be called from within another Python module?

Thanks

**Comment by jpmckinney** [comment]
You should use [agate](https://github.com/wireservice/agate) on which csvkit now relies for all its operations.
