### ISSUE TITLE
csvclean: report unescaped quote characters

### ISSUE THREAD

**Issue by stanislav-bios-baranov** [wireservice/csvkit#672]
Command 
`csvclean -d "," -u 3 test_csv_crlf_semicolon_allquoted.csv` 
for attached file gives 
`No errors.` 

(while file is formatted using format, which differs from passed in params)

Maybe I am getting something wrong, but shouldn't it report some errors?

[test_csv_crlf_semicolon_allquoted.csv.txt](https://github.com/wireservice/csvkit/files/547607/test_csv_crlf_semicolon_allquoted.csv.txt)

**Comment by stanislav-bios-baranov** [comment]
P.S.: attached file is random data generated and not contain any real personal data

**Comment by oleksandr** [comment]
+1 - same problem on my side.

**Comment by jpmckinney** [comment]
What error would you expect to be reported?

**Comment by stanislav-bios-baranov** [comment]
@jpmckinney 

My provided sample is in following format:
``"col1";"col2";...;"colN"``

When I am passing params ``d "," -u 3`` to ``csvclean`` I am trying to tell explicitly my expectations to file format. So basically I am expecting file to have format:
``col1,col2,...,colN``

So basically from ``col1,col2,...,colN`` format standpoint provided file have one quoted column. Which conflicts with ``-u 3``param (3 = Quote None).

So it would be nice if at this point tool at least report `Unexpected quoting type` or `Bare " in non-quoted-field` or `Extraneous " in field` or something else, instead of ``No errors.``.

**Comment by jpmckinney** [comment]
Updated issue description.

**Comment by jpmckinney** [comment]
@stanislav-bios-baranov Actually, the reason it says 'no error' is because it is reading the quote characters as data. `Quote None` still allows files to contain quote characters as data.
