### ISSUE TITLE
csvsql writes lowercase true/false instead of TRUE/FALSE

### ISSUE THREAD

**Issue by jeffreyb42** [wireservice/csvkit#674]
Not sure if this is the right place for this. Did some searching but couldn't find anything.

I'm using csvsql to extract a delta between 2 files (new version vs old version). One column in my files is boolean; the value is either TRUE or FALSE. The problem is csvsql is converting these values to 1 and 0 respectively.

How do I stop or fix this?

**Comment by jpmckinney** [comment]
Try running it with `--no-inference` ?

**Comment by jeffreyb42** [comment]
Thanks, that's better.
Now it's changing TRUE and FALSE to true and false. Not perfect but certainly better than 1 and 0 :)

**Comment by jpmckinney** [comment]
Ah, yes, all-caps would be most SQL-compliant. Is lowercase OK though?

**Comment by jeffreyb42** [comment]
Unfortunately, probably not. If there is no immediate solution, I can run it through a script to switch them back.

**Comment by jpmckinney** [comment]
What commands are you running, so I have a better sense of what to change?

**Comment by jeffreyb42** [comment]
It's in a shell script and looks like so:
```
csvsql -z 1000000 --no-inference --query "SELECT *
FROM $NEW as td
WHERE (NOT EXISTS
        (SELECT [alarmClassTag], [alarmName (id)], [alarmType (id)]
         FROM $OLD AS d
         WHERE ([alarmClassTag] = td.[alarmClassTag])
                AND
                ([alarmName (id)] = td.[alarmName (id)])
                AND
                ([alarmType (id)] = td.[alarmType (id)])
        )
)" ${OLD}.csv ${NEW}.csv > ${DELTA}.csv
```
The "-z 1000000" is excessive, but I didn't know how big my largest cell was at the time. I should drop that down to 200000.

**Comment by jpmckinney** [comment]
Hmm, I think this would require a change to SQLAlchemy.

**Comment by jpmckinney** [comment]
I can't reproduce. If the original file has `TRUE` then the output will still be uppercase:

    echo "TRUE" | csvsql --no-header-row --query "SELECT * FROM stdin"

prints `1`, but:

    echo "TRUE" | csvsql --no-header-row --no-inference --query "SELECT * FROM stdin"

prints `TRUE`.
