### ISSUE TITLE
Install with Homebrew

### ISSUE THREAD

**Issue by rnkn** [wireservice/csvkit#676]
[Homebrew](http://brew.sh)

Tried with `brew diy` but
```
Error: Couldn't determine build system
```

**Comment by jpmckinney** [comment]
What's wrong with installing with `pip` like all other Python packages?

**Comment by rnkn** [comment]
Homebrew installs everything into `/usr/local/Cellar` and symlinks binaries in place, avoiding polluting one’s system, avoids `sudo` etc. etc. More info on their FAQs.

Also, Homebrew has become the de facto package manager for macOS, so not having a Homebrew formula is like roaming the cursed earth outside of Mega-city One.

**Comment by rnkn** [comment]
That is only for libraries.

**Comment by rnkn** [comment]
> Homebrew draws a distinction between Python applications and Python libraries. The difference is that users generally do not care that applications are written in Python; it is unusual that a user would expect to be able to import foo after installing an application. Examples of applications are ansible and jrnl.
>
> Python libraries exist to be imported from other Python modules; they are often dependencies of Python applications. They are usually no more than incidentally useful from a Terminal.app command line. Examples of libraries are py2cairo and the bindings that are installed by protobuf --with-python.

https://github.com/Homebrew/brew/blob/bbed7246bc5c5b7acb8c1d427d10b43e090dfd39/docs/Python-for-Formula-Authors.md

**Comment by rnkn** [comment]
I put together an attempt at a Homebrew formula here: https://gist.github.com/rnkn/bf377f49a8cc37f50c82a7ef5b3739f4

It appears to install, but upon attempting the tutorial...
```
$ in2csv ne_1033_data.xlsx
Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/csvkit/0.9.1/libexec/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dbf==0.94.003' distribution was not found and is required by csvkit
```
🎺 #sadtrombone

Guidance appreciated.

**Comment by seasox** [comment]
You might need to include dbf (https://pypi.python.org/pypi/dbf/0.94.003) just as you included the other libraries:

```Ruby
resource "dbf" do
  url "https://pypi.python.org/packages/7c/ef/79873517838910e8f1bd5610ab3de380a3886675103072727266eec91bbc/dbf-0.94.003.tar.gz"
  sha256 "c95b688d2f28944004368799cc6e2999d78af930a69bb2643ae098c721294444"
end
```

**Comment by rnkn** [comment]
Ah I see. I was just going off contents of `requirements-py2.txt` and `requirements-py3.txt`. Are there others not listed in those files?

Will give it another shot. Thanks.

**Comment by jpmckinney** [comment]
`dbf` is a dependency of `agate-dbf`, which is a dependency of `csvkit`. I don't know Homebrew Python recipes well - maybe all dependencies need to be recursively added?

**Comment by deeTEEcee** [comment]
Just an fyi:
so, i just wanted a simple tool to read csv from the cmdline and then ended up with csvkit. i randomly tried `brew install csvkit`, wondering if it existed. after installation, the `csvkit` cmd couldn't be found but `csvsql` existed. a bit confusing what's going on here for users who just want a quick setup.
