### ISSUE TITLE
in2csv -d (delimiter) is ignored when converting to a semicolon delimited csv

### ISSUE THREAD

**Issue by superurbi** [wireservice/csvkit#680]
Hi all,

I'm using 0.9.1 in windows (Spanish) and the problem is that this command...

in2csv -d ";" --sheet %hojaexcel% "Analytics Plantilla.xlsx" > "excel2csv-hoja-%hojaexcel%.csv"

Generates a Comma separated fields and not ";" separated fields as indicated in -d ";" delimiter parameter!
This is a problem as numbers are dot containing so if I replace dots with "," can't then replace field "," with a ";"
csvgrep is also ignoring the -d ";" as the output file is using "," as field delimiter.

Thanks for your help.

**Comment by jpmckinney** [comment]
Hi @superurbi, the -d option sets the delimiter for the input. In this case, the input is XLSX, so that option is ignored. To change the output that is generated, you need to pipe in2csv into csvformat:

    in2csv --sheet %hojaexcel% "Analytics Plantilla.xlsx" | csvformat -D ";" > "excel2csv-hoja-%hojaexcel%.csv"

**Comment by superurbi** [comment]
Thanks for the fast response. Didn't know about the csvformat command. Thank you for the tip!!
