### ISSUE TITLE
agate: strings are interpreted as datetimes

### ISSUE THREAD

**Issue by vtselfa** [wireservice/csvkit#683]
CSVLook seems to interpret as dates some strings that it should not.
This is using last version (1.0.0) from github, branch master.
```
%cat test.txt          
core,app
5,05_leslie3d_base
6,06_povray_base
4,04_h264ref_base
3,03_astar_base
2,02_lu.C
7,07_cg.C
1,01_mcf_base
0,00_xalancbmk_base
```
[test.txt](https://github.com/wireservice/csvkit/files/611835/test.txt)

```
% csvlook test.txt
| core |        app |
| ---- | ---------- |
|    5 | 0501-01-01 |
|    6 | 0601-01-01 |
|    4 | 0401-01-01 |
|    3 | 0301-01-01 |
|    2 | 0201-01-01 |
|    7 | 0701-01-01 |
|    1 | 0101-01-01 |
|    0 | 0001-01-01 |
```

As can be seen, the strings in the second column have been replaced by strange dates.

**Comment by jpmckinney** [comment]
Try with `--no-inference`

**Comment by vtselfa** [comment]
It doesn't happen with --no-inference.

**Comment by jpmckinney** [comment]
agate shouln't consider text like `05_leslie3d_base` to be a date.

**Comment by onyxfish** [comment]
Tracked upstream.

**Comment by onyxfish** [comment]
Fixed upstream.
