### ISSUE TITLE
csvlook bool inference too aggressive

### ISSUE THREAD

**Issue by vtselfa** [wireservice/csvkit#685]
When dealing with csv files with only one row, csvlook converts to boolean each 0 or 1 it finds.
In my opinion this is too aggressive. See also #506.
Example:
```
$ cat test0.csv
core,us
0,60000011
```
```
$ csvlook test0.csv
|  core |         us |
| ----- | ---------- |
| False | 60.000.011 |
```
The same happens with a 1 instead of a 0.

This is with csvkit 1.0.0, from the git repository.

I think this kind of inference can be very problematic, but if done, I would be better to first wait until there is a significant number of rows with only 1 and 0 values. E.g. only try to infer booleans if the number of rows with only 1 or 0 values is > X, where X >> 1. 

However, I would totally get rid of this inference rule.

**Comment by jpmckinney** [comment]
There is value to inferences in the majority of cases. If you're of the opinion that they are not, then just run the csvkit utilities with `--no-inference`. 1-line CSVs are rare; I'm not sure we want to make the code more complex just for this special case.
