### ISSUE TITLE
csvkit appears to reject us-ascii encoding?

### ISSUE THREAD

**Issue by jackbrannen** [wireservice/csvkit#687]
When I try to run `csvstat` on the attached file, I get a message saying the file doesn't use **utf-8** encoding. 

When I run `file -I` on the file, it looks like the file is **us-ascii** encoded.

But when I run `csvstat -e us-ascii` on the file, csvkit says, "Your file is not "us-ascii" encoded."

[272 BB Calc 118357 B.csv.zip](https://github.com/wireservice/csvkit/files/620246/272.BB.Calc.118357.B.csv.zip)

**Comment by jpmckinney** [comment]
I can't reproduce. Try with latest csvkit:

    pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit

**Comment by jackbrannen** [comment]
Fixed! Thank you.
