### ISSUE TITLE
Run operations on columns like trim…

### ISSUE THREAD

**Issue by z3to** [wireservice/csvkit#689]
Hey everyone,
thanks so much for such a great tool! Since I’m often dealing with messy dataset, one feature I would love to see are basic operations one can run on selected columns. This would be for example:
- trim spaces at beginning or end of strings
- delete multiple consecutive spaces
- convert to upper-, lower-, or titlecase

Even though I’m not sure if I could fully realize this, I would give it a try if it is a wanted feature.

**Comment by jpmckinney** [comment]
@z3to We encourage people to create their own new tools, which we're happy to link to from our documentation. We recommend using the `agate` library to build those tools, as we document in our [contribution guidelines](https://github.com/wireservice/csvkit/blob/master/docs/contributing.rst#new-tools).
