### ISSUE TITLE
Requirements not installed for test `test_wildcard_on_postgresql`

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#692]
Requires psycopg2, which maybe should be avoided in the tests... though it would be nice to know it works!

Currently commented out.

**Comment by jpmckinney** [comment]
It's not a dependency issue (on Travis or on my local anyway). On my local, it fails because the test doesn't clean up the database.

**Comment by jpmckinney** [comment]
psycopg2 isn't listed in requirements because pypy needs psycopg2cffi. See .travis.yml

**Comment by onyxfish** [comment]
I see, it looks like tox doesn't have that configuration. Will add and test.
