### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#694]
I've got a little time to work on this this week. I'm of a mind to try to barrel through and get the 1.0 release out, with or without complete documentation. Just getting the tests to pass would be good enough for me right now. @jpmckinney can you update me on anything you see that's blocking a release?

**Comment by jpmckinney** [comment]
Tests pass due to regex making pypy unhappy:

    ERROR: Failure: ImportError (unable to load extension module '/home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so': /home/travis/virtualenv/pypy-2.5.0/site-packages/_regex.pypy-25.so: undefined symbol: PyLong_FromUnicode)

https://travis-ci.org/wireservice/csvkit/jobs/185611914

**Comment by jpmckinney** [comment]
Milestone is still accurate: https://github.com/wireservice/csvkit/milestone/12

Normal priority should be part of 1.0 https://github.com/wireservice/csvkit/issues?q=is%3Aissue+is%3Aopen+label%3A%22Normal+Priority%22

**Comment by jpmckinney** [comment]
All docs are up-to-date except for the one issue labeled 'documentation'.

**Comment by onyxfish** [comment]
Great, looks like a manageable amount of work to get done in a day or two.

**Comment by onyxfish** [comment]
Thanks for keeping thing so organized. I wouldn't know where to even start...

**Comment by onyxfish** [comment]
Starting release process NOW.

**Comment by onyxfish** [comment]
Well, this is an agonizing wait.
