### ISSUE TITLE
Squelch agate column name errors when running tests

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#696]
It's just annoying and hard to read

**Comment by jpmckinney** [comment]
How would we do this?

**Comment by onyxfish** [comment]
It's possible to capture warnings with the `warnings` module. I believe there is also a `nose` flag that squelches them.

**Comment by onyxfish** [comment]
If there is a flag we could code into the tox/travis config that would be ideal. If it's going to be a big boilerplate code headache than I'd just assume not do it.

**Comment by jpmckinney** [comment]
`warnings.filterwarnings` doesn't match on message text, so agate should use something more specific than `RuntimeWarning` to be able to catch it more easily.
