### ISSUE TITLE
Install docs have gone missing

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#703]
I guess they get deleted at some point....

**Comment by onyxfish** [comment]
After restoring need to add Python 3.6 as a supported version.

**Comment by jpmckinney** [comment]
What's gone missing? It's just `pip install csvkit`.

**Comment by onyxfish** [comment]
This page is gone: https://csvkit.readthedocs.io/en/0.9.1/install.html

Easy to restore.

**Comment by onyxfish** [comment]
Oh I see, you moved it into the Tips section. I'd prefer to keep this separate and up-front, in service to users who might be relatively new to the command line.

**Comment by onyxfish** [comment]
Actually, after looking closer at this, I like the way you did it. The stuff new users need is covered in the tutorial.
