### ISSUE TITLE
agate: Babel deprecation warning

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#706]
Not sure there is anything I can do about this, but maybe I can at least silence it for the time being?

```
/Users/cgroskopf/.virtualenvs/test/lib/python3.6/site-packages/Babel-2.3.4-py3.6.egg/babel/localtime/_unix.py:8: DeprecationWarning: Flags not at the start of the expression ^Time Zone: (.*)$(?m (truncated)
```

Sample tutorial command that generates this:

```
in2csv ne_1033_data.xlsx > data.csv
```

**Comment by jpmckinney** [comment]
Hmm, I don't get that warning - and Babel is an agate dependency.

**Comment by onyxfish** [comment]
Yeah, I started getting on 3.6. It's probably safe to ignore for now, but it would be nice to capture it so it doesn't confuse people.

**Comment by onyxfish** [comment]
Moving out of release since this only affects 3.6.

**Comment by jpmckinney** [comment]
Closed by https://github.com/wireservice/agate/issues/665
