### ISSUE TITLE
csvlook should support `-c`

### ISSUE THREAD

**Issue by onyxfish** [wireservice/csvkit#715]
Should be easy and not reason not to have the shortcut since its a standard arg.

**Comment by jpmckinney** [comment]
Wouldn't this normally be `csvcut -c 1 dummy.csv | csvlook` ?

**Comment by jpmckinney** [comment]
`-c` has a different meaning in each utility that has it (cut, grep, join, sort, stat)

**Comment by onyxfish** [comment]
Yes, you're right. Not a standard flag. My faulty memory at work.
