### ISSUE TITLE
Tutorial: in2csv examples/test.xls -v fails

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/csvkit#725]
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 9: ordinal not in range(128)`

**Comment by onyxfish** [comment]
I can't replicate this. Are you sure you've got the latest agate release? (`1.5.3` at time of comment)

**Comment by jpmckinney** [comment]
I can replicate in Python 2 with:

```
agate==1.5.4
agate-dbf==0.2.0
agate-excel==0.2.0
agate-sql==0.5.0
```

**Comment by onyxfish** [comment]
Weird, just tried this with a fresh env on Python 2.7.13 and it works fine for me:

```
(csvkit2) ➜  csvkit git:(master) ✗ python --version
Python 2.7.13
(csvkit2) ➜  csvkit git:(master) ✗ in2csv examples/test.xls
text,date,integer,boolean,float,datetime,empty_column,_unnamed
Chicago Reader,1971-01-01,40,True,1.0,1971-01-01T04:14:00,,
Chicago Sun-Times,1948-01-01,63,True,1.27,1948-01-01T14:57:13,,Extra data beyond headers will be trimmed
Chicago Tribune,1920-01-01,164,False,41800000.01,1920-01-01T00:00:00,,
This row has blanks,,,,,,,
Unicode! Σ,,,,,,,
```

**Comment by onyxfish** [comment]
Since I can't replicate I'm going to treat this as non-essential for 1.0. We can address in `1.0.1` if we can figure out why our local copies disagree.

**Comment by jpmckinney** [comment]
Works in clean environment for me too. Not sure what was wrong with other environment.
