### ISSUE TITLE
csvsql: When not supplying password, execution stops

### ISSUE THREAD

**Issue by doekman** [wireservice/csvkit#726]
When a connection string doesn't contain a password, but the connection needs one, csvsql stops executing (error: `(psycopg2.OperationalError) fe_sendauth: no password supplied`). 

The psql command-line program on the other hand asks for a password. Behaviour can be altered with the --password and --no-password arguments. This option would be valuable (I use both psql and csvsql in the same script)

**Comment by jpmckinney** [comment]
We're not calling the `psql` command in the shell, but it may be possible to add a prompt if password-less authentication fails. However, there are other methods for password-less authentication (dotfiles, etc.).
