### ISSUE TITLE
csvsql -i output differs from --db output

### ISSUE THREAD

**Issue by aklaver** [wireservice/csvkit#740]
openSUSE Leap 42.1
Python3.4
csvkit==1.0.1

When I do:

`csvcut -c 1,2 MOCK_DATA_MALE.csv | csvsql -i postgresql --tables first_name`

I get:

```
CREATE TABLE first_name (
        id DECIMAL NOT NULL, 
        name_first VARCHAR(11) NOT NULL
);
```

When I do:

`csvcut -c 1,2 MOCK_DATA_MALE.csv | csvsql --db postgresql://aklaver:@localhost/test --tables first_name --insert`

I get:

```
postgres@test=# \d first_name 
         Table "public.first_name"
   Column   |       Type        | Modifiers 
------------+-------------------+-----------
 id         | numeric           | 
 name_first | character varying | 
```

Looks like --db is using --no-constraints  by default.
Is that what is supposed to happen?

**Comment by aklaver** [comment]
Attaching the CSV file might help.
Interesting,  *.csv files are not supported
Well more then one way to skin a cat:
[MOCK_DATA_MALE.txt](https://github.com/wireservice/csvkit/files/681354/MOCK_DATA_MALE.txt)

**Comment by aklaver** [comment]
Alright if I am following the issue is at about line 125 in csvsql.py:

`if table:
                if self.connection:
                    table.to_sql(
                        self.connection,
                        table_name,
                        create=(not self.args.no_create),
                        insert=(self.args.insert and len(table.rows) > 0),
                        constraints=()
                    )

                # Output SQL statements
                else:
                    statement = table.to_sql_create_statement(
                        table_name,
                        dialect=self.args.dialect
                    )

self.output_file.write('%s\n' % statement)`

constraints is being set to an empty tuple which table.to_sql evaluates as False and passes on to make_sql_table which makes a table without constraints. In the create statement case constraints is not set, so the default of True is used in table.to_sql_create_statement(). My guess what is supposed to go in to_sql constraints is  (not self.args.no_constraints)

**Comment by jpmckinney** [comment]
@aklaver Can you try with the latest version on GitHub?

    pip install --upgrade -e git+git://github.com/wireservice/csvkit.git@master#egg=csvkit

**Comment by aklaver** [comment]
You beat me to it, I was putting together a PR with a similar fix:) 
Tried with the latest and it works, thanks.
