### ISSUE TITLE
CSV load is not working 

### ISSUE THREAD

**Issue by paddyriyer** [wireservice/csvkit#745]
I tried to upload the file in both mysql and postgres. I am getting following errors.
The sample file can be loaded from https://goo.gl/sZUz7u

```
csvsql --db postgresql:///paddyiyer --insert ~/Downloads/SalesJan2009.csv
(psycopg2.ProgrammingError) type "datetime" does not exist
LINE 3:  "Transaction_date" DATETIME,
```

in MySQL I am getting the following error.

```
csvsql -d , -q \" -e ISO-8859-1 --insert SalesJan2009.csv --db mysql://root@localhost:3306/mydev
(in table 'SalesJan2009', column 'Product'): VARCHAR requires a length on dialect mysql
```

(in table 'SalesJan2009', column 'Product'): VARCHAR requires a length on dialect mysql

**Comment by jpmckinney** [comment]
The first issue is same as #722 (which has a PR https://github.com/wireservice/agate-sql/pull/23).

**Comment by jpmckinney** [comment]
I can't reproduce the second issue. Are the `-d`, `-q` and `-e` options necessary?

What's the output when you run `csvsql --dialect mysql SalesJan2009.csv`?

**Comment by paddyriyer** [comment]
-d, -q and -e are not necessary. Just updated the issue related to mysql. Thanks for looking

**Comment by paddyriyer** [comment]
CREATE TABLE `SalesJan2009` (
	`Transaction_date` DATETIME NOT NULL,
	`Product` VARCHAR(9) NOT NULL,
	`Price` DECIMAL NOT NULL,
	`Payment_Type` VARCHAR(10) NOT NULL,
	`Name` VARCHAR(21) NOT NULL,
	`City` VARCHAR(33) NOT NULL,
	`State` VARCHAR(26),
	`Country` VARCHAR(20) NOT NULL,
	`Account_Created` DATETIME NOT NULL,
	`Last_Login` DATETIME NOT NULL,
	`Latitude` DECIMAL NOT NULL,
	`Longitude` DECIMAL NOT NULL
);

**Comment by jpmckinney** [comment]
Hmm, strange, VARCHAR gets a length for `Product` when printing the SQL statement, but the error suggests that it doesn't get a length when sending the statement to MySQL.

**Comment by paddyriyer** [comment]
Perfect @jpmckinney. Thanks a lot. It worked a charm. What about Postgres. I am not too concerned.

**Comment by jpmckinney** [comment]
PostgreSQL has a fix but it requires releasing a new version of agate-sql first.

**Comment by jpmckinney** [comment]
All fixed when using csvkit HEAD and agate-sql HEAD.
