### ISSUE TITLE
csvclean documentation is poor

### ISSUE THREAD

**Issue by CharlesNepote** [wireservice/csvkit#748]
Great tool really, but the documentation is very poor. It should be interesting to explain each task done by csvclean:

- delete every unneeded quote
- recode from XXX charset to UTF-8
- replace X delimiter by a comma
- replace \r\n by \n

This last modification is ok for me as I can then grep the file without problem, but it is not compatible with the RFC (which recommand \r\n).

**Comment by jpmckinney** [comment]
Thanks - if you'd like to start a pull request editing [this file](https://github.com/wireservice/csvkit/blob/master/docs/scripts/csvclean.rst), that'd be much appreciated!

**Comment by CharlesNepote** [comment]
See my pull request: #753 

Hope this can help, I'm not sure that csvclean doesn't clean more than what I wrote. Unfortunately my programming knowledge is poor and I can't check that. Feel free to rewrite/complete what I suggested.
