### ISSUE TITLE
in2csv xls entry of 1m is converted to 00:01:00

### ISSUE THREAD

**Issue by dalcolmo** [wireservice/csvkit#752]
An entry "1m" (text) is interpreted as a datetime of 1 minute, even when using the --no-inference flag. Versions before 1.0 did not do this, and I would like to get "1m" in the output.

**Comment by dalcolmo** [comment]
and a 1 is converted to "True", even with the --no-inference flag set.

[goo.xlsx](https://github.com/wireservice/csvkit/files/727319/goo.xlsx)

**Comment by jpmckinney** [comment]
Requires wireservice/agate-excel#16 to be merged.

**Comment by jpmckinney** [comment]
Merged.
