### ISSUE TITLE
shorthand for --no-inference

### ISSUE THREAD

**Issue by dalcolmo** [wireservice/csvkit#765]
I find my scripts have --no-inference everywhere. I wish the default behaviour would be --no-inference. Since there is no global configuration of the csvkit I know of, the next best thing is to have a short alias for --no-inference, for example "-i", so the scripts become a bit more compact.

**Comment by jpmckinney** [comment]
I'll use `-I`, since we use uppercase for flags like `-H` (`--no-header-row`). Also, `-i` lowercase is taken.
