### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by scottstanfield** [wireservice/csvkit#767]
I apologize for adding three specific feature requests to a single issue, but since they're all related, and there's a corresponding screen shot, I thought it might be best here.

Also, I like the idea of the tool emitting Markdown compatible files, but since it's new and unexpected behavior, I would advocate that one needs a flag to explicitly enable it.

# Screenshot
Top screen `jasmine` is running an older version of `csvlook`. By inspecting the file `/usr/local/bin/version` I think this is csvkit 0.9.1. Fails when trying to use unknown flag ``--no-inference` instead of ignoring the flag.

Bottom screen `belle` doesn't have a version, and it's not clear from inspecting the python source. But it's recent as of yesterday. 

The CSV file in question is 511 rows x 546 cols (a mix of strings, ints, floats and booleans)

![image](https://cloud.githubusercontent.com/assets/280700/22307094/988bf48e-e2f6-11e6-8fb0-fc6cb14e9bb4.png)

# My requests
1. Add `--version`. It'll be hard to report bugs if there's not an easy way to query what version is installed. Also, if there was a reliable `--version` flag, then we could query at shell login and set appropriate wrappers to enable `

2. Make `--no-inference` the default state. So one would use `--inference` to enable it.

3. Inference is *slow*. In the second screenshot, it takes 10 seconds to complete, vs. 1 second disabled. The older version (in `jasmine`) was even faster at 1/2 second.

I love the tool...I probably use `csvlook` 50-100 times *per day*. Across 6 machines (I do a lot with CSV files). 

# My hack solution
Fork `csvkit` and disable inference by default. If I get this working, I'll submit pull request, but it would be a surprise to your new users that _expect_ the inference to be enabled by default. 

Maybe there's an *environment* variable that can control all this?

**Comment by jpmckinney** [comment]
csvkit uses agate in its most recent version to support nearly all its functionality. agate only renders tables in a Markdown-compatible format (see https://github.com/wireservice/agate/issues/626), and there isn't much appetite to support a wide variety of output formats. We acknowledged this backwards-incompatible change across a major version (`0.9.1` to `1.0.0`) respecting semantic versioning. What is the issue with the change in format?

We know that type inference is slow, but we've gone over the default behavior in many issues over the years, and the decision has been that, while it occasionally causes issues, changing the default behavior to no type inference would cause many more issues. Just a quick example, users of `csvsort` expect dates to be sorted in date order, not in lexicographical order. Type inference has been the default for as long as I've worked on `csvkit`.

`csvkit` is not intended for cases where speed is critical. That said, we of course author and accept pull requests for optimizations, but we typically do not pursue performance at the expense of ease of use, code complexity, maintainability, extensibility, etc.

Anyway, for this issue, I'll leave it as adding `--version`. Please open a new issue if you'd like to pursue environment variables for controlling flags. You may be satisfied with creating aliases like `alias ncsvlook='csvlook --no-inference`.

**Comment by scottstanfield** [comment]
Right: the solution for the alias above is good for now. And leaving this in now as a simple request for `--version` stands.

I'll take a closer look at agate. Didn't know that was the underlying engine. 

Thanks for your detailed response and the reasoning behind the decisions.

**Comment by scottstanfield** [comment]
Awesome, thanks!

**Comment by malcook** [comment]
+1 for --version

**Comment by jpmckinney** [comment]
@malcook It's in the unreleased version on GitHub.

**Comment by malcook** [comment]
I see now it is actually in a fork.  Not in master.
Thanks
