### ISSUE TITLE
agate: csvlook: Add an option to allow unnamed columns

### ISSUE THREAD

**Issue by chuanconggao** [wireservice/csvkit#787]
Is it possible to add an option to prevent agate automatically naming unnamed columns. 

For example, I want to preview the following CSV, where the first column does not have name:

|               | 1st Half | 2nd Half | Total |
| ------------- | -------- | -------- | ----- |
| Central Wash. |       52 |       45 |    97 |
| Simon Fraser  |       44 |       41 |    85 |

**Comment by jpmckinney** [comment]
Does naming the column cause a problem?

**Comment by chuanconggao** [comment]
I am using csvlook in a workflow to generate HTML automatically like this:
`csvlook sth.csv | pandoc`

As I cannot control the CSV, there are inevitably empty column names. I want to make sure the rendered HTML also has empty column names instead of automatically generated ones, to keep the appearance consistent.

**Comment by jpmckinney** [comment]
I created an issue on agate: https://github.com/wireservice/agate/issues/668

**Comment by jpmckinney** [comment]
Changing agate isn't likely, so I'm going to mark this duplicate of #814, which should allow you to explicitly rename columns to the empty string.
