### ISSUE TITLE
csvkit tutorial examples: not working

### ISSUE THREAD

**Issue by AbsarF** [wireservice/csvkit#789]
Hi, 
I am a beginner in csvkit..just started 15 mins back..hope somebody can help me..thanks

I am running the official tutorial and I have following problems (incomplete stats by using 'csvstat' command):

1- when i use : "csvcut -c county,acquisition_cost,ship_date data,csv | csvstat"
I only get the incomplete summary stat for :  'county' and 'acquisition_cost' (not as shown in the tutorial)

2- when i use : "csvstat data.csv"
I only get :  'state', 'county', 'fips' --> incomplete summary stats

Also when I run 'csvkit' from Jupyter notebook..the notebook hangs and I have to restart many times.
Anything I am missing here ???
(Using python 3.5.2; Anaconda 1.5.1 on Mac OS X (Sierra)

many thanks

**Comment by jpmckinney** [comment]
You need to be using csvkit >= 1.0.0. Anaconda uses 0.9.1 which is from 2015.
