### ISSUE TITLE
Do not convert [cr][lf] end of line to [lf]

### ISSUE THREAD

**Issue by CharlesNepote** [wireservice/csvkit#792]
RFC 4180 is not really a standard and explicitly "documents the format that seems to be followed by most implementations". But many implementations strictly follow RFC 4180. And it [says that](https://tools.ietf.org/html/rfc4180#page-2):
> 1.  Each record is located on a separate line, delimited by a line break (CRLF).

But every tools of csvkit seem to convert [cr][lf] end of line to [lf] (at least under Linux). It think it shouldn't. Every other conversions of csvkit tools follow RFC 4180 but not the end of line. For example, CSVLint is yelling when we have [lf] end of lines:
> Structural problem: Non-standard Line Breaks on row 1
> 
> Your CSV appears to use LF line-breaks. While this will be fine in most cases, RFC 4180 specifies that CSV files should use CR-LF (a carriage-return and line-feed pair, e.g. \r\n). This may be labelled as "Windows line endings" on some systems.

**Comment by jpmckinney** [comment]
I opened an issue on agate https://github.com/wireservice/agate/issues/669

In the meantime you can do:

    csvformat -M $'\r\n' file.csv

**Comment by CharlesNepote** [comment]
As a workaround I use:

```
csvclean file.csv; csvformat -M $'\r\n' file_out.csv > tmp.csv && mv tmp.csv file_out.csv
```

But it's quite a long line and difficult to explain to the heterogeneous public I'm facing.

Why not add -M to [common arguments](https://csvkit.readthedocs.io/en/749/common_arguments.html)? We could then have `csvclean -M $'\r\n' file.csv` (there could be other usages than following the RFC).

That said, the best solution would be to follow the RFC.

**Comment by jpmckinney** [comment]
After the next release, we'll merge #781 and you'll be able to do:

    csvclean file.csv | csvformat -M $'\r\n'

Anyway, I'm waiting for @onyxfish in wireservice/agate#669 to understand why "\n" was chosen.

**Comment by CharlesNepote** [comment]
#781 is a great news! More coherent with the other tools.

But I will have to change my documentation based on csvclean. I know the "release when ready" motto, but do you have any idea when it will be launched (in days, weeks, months?)? It's important for me because if it's in days I'll wait for to publish my guide.

**Comment by jpmckinney** [comment]
I don't expect it will be in days.

**Comment by CharlesNepote** [comment]
All right, no problem. Thanks!
