### ISSUE TITLE
csvsql creates junk character ï»¿ before first column name

### ISSUE THREAD

**Issue by deepakagrawal** [wireservice/csvkit#794]
Hi,

I am trying to convert bunch of csv files into tables and create a database in mysql. 
I am using following code

csvsql -e latin --db mysql://root:password@127.0.0.1/patExp --insert /path/UCUM.csv

The first columnn name looks like ï»¿RECID

Can you help me out? Is the the problem of csvkit? or mysql?

**Comment by jpmckinney** [comment]
It looks like your CSV starts with a byte order mark (BOM), which is invisible in some text/data editors.

**Comment by jpmckinney** [comment]
Running with `-e utf-8-sig` should eliminate the BOM.
