### ISSUE TITLE
-bash: in2csv: command not found

### ISSUE THREAD

**Issue by DigitalPublishingToolkit** [wireservice/csvkit#796]
When I put this: 
in2csv ne_1033_data.xlsx
I got this return. 
-bash: in2csv: command not found

I tried several things to solve this, but didn't work out. Any suggestions?

**Comment by jpmckinney** [comment]
`in2csv` isn't being added to your shell's `PATH`. What's the output when you install csvkit?

**Comment by felixveysseyre** [comment]
I got the same problem this morning, even if I did not get any error during `csvkit` installation.

I had to manually add the installation folder to my path and it solve the issue.

**Comment by jpmckinney** [comment]
What was the folder/path that you had to add?

**Comment by jpmckinney** [comment]
What did you use to install that version of Python? MacPorts?

**Comment by jpmckinney** [comment]
Closing as it seems sensible to need to add that path. Can re-open if there are follow-up issues.

**Comment by felixveysseyre** [comment]
@jpmckinney This is the default version installed on my system. I usually use MacPorts to install additionnal packages.

**Comment by jpmckinney** [comment]
Hmm, macOS 10.11 doesn't use `/opt/local` for Python. It's possible another MacPorts package you installed also installed Python as a dependency.
