### ISSUE TITLE
The date parameters in csvcut column names.

### ISSUE THREAD

**Issue by ruhagen** [wireservice/csvkit#797]
Hi All,

Could you please clarify is it possible to use  the date parameters in csvcut column names?

For example, I have tried command:

`cat myfile0.csv | csvcut -c  'A$(date +%Y%m -d '2 month ago')','A$(date +%Y%m -d '1 month ago')' > myfile1.csv`

for file like this:

myfile0.csv
```
A1701, A1612
100, 200
```
in order to get file like this:

myfile1.csv
```
A1612, A1701
200, 100
```

But got error: 
> csvcut: error: unrecognized arguments:

How I can solve my issue?

Thank you in advance!

**Comment by jpmckinney** [comment]
It's a problem with your use of bash. You have to use double quotes. Also, `%Y` instead of `%y`.

    cat myfile0.csv | csvcut -c "A$(date +%y%m -d '2 month ago'),A$(date +%y%m -d '1 month ago')" > myfile1.csv

**Comment by ruhagen** [comment]
Hi **jpmckinney**,

Thanks a lot. It worked perfectly.
