### ISSUE TITLE
error using in2csv when piping xlsx stdin 

### ISSUE THREAD

**Issue by alexsmartsky** [wireservice/csvkit#799]
Great library. I tried a lot of excel converters with unreliable results before I came across this solution.

I'm trying to pipe an xlsx file to in2csv and I get the error - 
**"coercing to Unicode: need string or buffer, NoneType found"**

Although I'm using nodeJS to pipe the excel file to in2csv, the same error comes up when you simply 

    cat file.xlsx | in2csv -f xlsx       <--- Error!
    in2csv -f xlsx file.xlsx       <--- works perfectly

I don't have a lot of experience with file manipulation. Am I missing something or is there a bug? 

Thanks, Alex

**Comment by jpmckinney** [comment]
Can you run `incsv` with `-v` and paste the full output?

**Comment by alexsmartsky** [comment]
jpmckinney - that's the best news to read first thing in the morning. Thank you for fixing this.
