### ISSUE TITLE
in2csv new bug in 1.02 converting xlsx

### ISSUE THREAD

**Issue by alexsmartsky** [wireservice/csvkit#802]
It seems there's been a new bug introduced with the 1.02 release last night.

**from_xlsx() got an unexpected keyword argument 'column_types'**

The new error message occurs both when piping or reading xlsx from file (as per eg below)

```
$ in2csv -v -f xlsx n.xlsx 
Traceback (most recent call last):
  File "/usr/local/bin/in2csv", line 11, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'in2csv')()
  File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/in2csv.py", line 153, in launch_new_instance
    utility.run()
  File "/usr/local/lib/python2.7/dist-packages/csvkit/cli.py", line 114, in run
    self.main()
  File "/usr/local/lib/python2.7/dist-packages/csvkit/utilities/in2csv.py", line 138, in main
    table = agate.Table.from_xlsx(self.input_file, **kwargs)
TypeError: from_xlsx() got an unexpected keyword argument 'column_types'
```

**Comment by alexsmartsky** [comment]
I rolled back to 1.01 and manually applied your changes in issue 799. This version works and resolves piped xlsx issue. It's fully functional for my purposes until a fix is released.

**Comment by jpmckinney** [comment]
That issue is due to the commit https://github.com/wireservice/agate-excel/commit/cec58eff2ba9bfddf37214f2390de914e8bd3f3b being missing from agate-excel. When we release csvkit, we'll release all its dependencies at the same time.

**Comment by alexsmartsky** [comment]
Thanks again.
