### ISSUE TITLE
csvlook: eats commas in strings

### ISSUE THREAD

**Issue by henrikq** [wireservice/csvkit#805]
Reproduce:
```
$ printf 'FOO\n"1,2"\n' | csvlook
| FOO |
| --- |
|  12 |
```

Expect:
```
$ printf 'FOO\n"1,2"\n' | csvlook
| FOO |
| --- |
| 1,2 |
```

**Comment by jpmckinney** [comment]
You need to run csvlook with `--no-inference`. It's interpreting "1,2" as a number in which `,` is a group symbol.

**Comment by henrikq** [comment]
Thanks. That said though, Its kinda annoying if you consider those of us that have to deal with data that uses comma as a decimal, which is roughly half the world: 
https://en.wikipedia.org/wiki/Decimal_mark#Countries_using_Arabic_numerals_with_decimal_comma

A --decimal flag would be nice, e.g. 
```
$ printf 'FOO\n"1,2"\n' | csvlook --decimal ","
| FOO |
| --- |
| 1,2 |
```
or something like that.

**Comment by jpmckinney** [comment]
In that case, use the `--locale` flag (not yet released but available on GitHub) like `csvlook --locale fr`
