### ISSUE TITLE
Alpha2 ISO country code for Namibia (NA) is silently discarded

### ISSUE THREAD

**Issue by eric-brechemier** [wireservice/csvkit#806]
This is quite unexpected. Probably related to #49.

Minimal example:

### alpha2.csv

```
name,ISO3166-1-Alpha-2
Namibia,NA
```

### csvstat: `Most common values:    None`

```
$ csvstat alpha2.csv 
  1. "name"

	Type of data:          Text
	Contains null values:  False
	Unique values:         1
	Most common values:    Namibia (1x)

  2. "ISO3166-1-Alpha-2"

	Type of data:          Boolean
	Contains null values:  True (excluded from calculations)
	Unique values:         1
	Most common values:    None (1x)

Row count: 1
```

### csvjoin: `"NA"` is silently replaced with `""`

```
$ csvjoin -c1,1 alpha2.csv alpha2.csv 
name,ISO3166-1-Alpha-2,ISO3166-1-Alpha-22
Namibia,,
```

**Comment by eric-brechemier** [comment]
The issue persists even if the value is quoted:

```
name,ISO3166-1-Alpha-2
Namibia,"NA"
```

**Comment by jpmckinney** [comment]
"NA" was being considered a null value. Previously, only csvsql had a `--blanks` option to turn off this behaviour. With #809 all buffering tools will have it, except `csvstat`.

**Comment by eric-brechemier** [comment]
Thanks!

**Comment by jpmckinney** [comment]
@mvelebit As above, run the command with `--blanks`

**Comment by mvelebit** [comment]
> @mvelebit As above, run the command with `--blanks`

No I mean I've already done it and it worked, I'm just stating how troublesome Namibia is 😄. Nevertheless, thanks for the response
