### ISSUE TITLE
in2csv: leading zeroes dropped in v1.0.1

### ISSUE THREAD

**Issue by dcabo** [wireservice/csvkit#807]
Hi,

I've noticed a change in the output of `in2csv` when upgrading from 0.9.1 to 1.0.1: leading zeroes are being dropped in the ouput, even for fields formatted as text. I'm attaching a small XLSX file that shows the problem: [test.xlsx](https://github.com/wireservice/csvkit/files/841421/test.xlsx).

0.9.1:

```
$ in2csv test.xlsx 
ID subdivisión de datos maestros,Centro gestor string parcial 1,Denominación string parcial 2
CAIB2017,02,Parlament de les Illes Balears
CAIB2017,03,Sindicatura de Comptes de les Illes Balears
```

1.0.1:

```
$ in2csv test.xlsx 
ID subdivisión de datos maestros,Centro gestor string parcial 1,Denominación string parcial 2
CAIB2017,2,Parlament de les Illes Balears
CAIB2017,3,Sindicatura de Comptes de les Illes Balears
```

The release notes include a warning, "the output format of some tools may have changed in small ways", but don't mention explicitely the leading zeroes case, so I'm not sure if you're aware of this.

**Comment by jpmckinney** [comment]
What if you run with `--no-inference`?

**Comment by dcabo** [comment]
I didn't think of trying that, but just did: same behaviour, leading zeroes are dropped.

**Comment by jpmckinney** [comment]
Ah, I think you need to be using the version in GitHub, which fixes a bug that caused `--no-inference` to be ignored for Excel files. You may also need to use the latest releases of agate and agate-excel.

**Comment by dcabo** [comment]
Will try that and let you know, thanks!

**Comment by dcabo** [comment]
Hi again. I can confirm that running the current Github version, with the latest dependencies, plus `--no-inference`, fixes the problem, thanks.

Do you have a planned date for v1.0.2?

**Comment by jpmckinney** [comment]
I think @onyxfish said he can do that soon :)
