### ISSUE TITLE
csvjoin is not treating fips codes as strings

### ISSUE THREAD

**Issue by TylerFisher** [wireservice/csvkit#810]
Hello,

I'm joining four files on FIPS codes. I've forced all the FIPS codes to strings, ensuring there are quotes around them in each file. Yet when I use `csvjoin`, FIPS codes with leading zeroes are stripped of the leading zeroes.

`csvjoin -c FIPS data/ahca.csv data/census.csv data/codes.csv data/elex.csv > data/combined.csv`

output in first line:

```
1001,AL,Autauga,-2410,-890,710,1730,2000,False,-2590,-1060,540,1560,3000,500,-8940,-7420,-5820,-4800,4000,1500,55136.0,52475.0,0.7623512768427162,2.0,0.73436,0.23957,0.02182,0.00426,0,0
```

the first column should be `01001`.

**Comment by onyxfish** [comment]
This actually does make sense, because agate is used to execute the join and its going to automatically type infer the columns. Obviously, there should be a way to make this work. The most obvious thing would be to add ``--no-inference`` support to csvjoin...

**Comment by TylerFisher** [comment]
I figured there was some kind of type inference happening. A `--no-inference` would be perfect (doing that already on a `in2csv` call).

**Comment by jpmckinney** [comment]
Have you tried the version in GitHub? I added --no-inference to csvjoin recently.

**Comment by jpmckinney** [comment]
I'm going to close - but we can re-open if it's not working.
