### ISSUE TITLE
"Merging" CSVs

### ISSUE THREAD

**Issue by RickCogley** [wireservice/csvkit#811]
Hello - I wonder if I can do this with csvkit? 

Assume a list of products...: 

Id,Product
1,Alpha
2,Beta
3,Gamma

... and a list of dates / months:

Id,Year,Month
1,2017,Jan
2,2017,Feb
3,2017,Mar
4,2017,Mar
5,2017,Apr
6,2017,April
7,2017,May
8,2017,Jun

I'd like to output something like this: 

Year,Month,Product
2017,Jan,Alpha
2017,Jan,Beta
2017,Jan,Gamma
2017,Feb,Alpha
2017,Feb,Beta
2017,Feb,Gamma
...

The purpose is, to load a table for sales forecasting. 

It's probably a kind of SQL union that's not so useful in real life, except when you need to multiple one full set by the other full set of data, like in this case. 

Is this possible? Appreciate your assistance, even if it's only to comment on what I might do a deeper search on. 

Sincerely
Rick

**Comment by jpmckinney** [comment]
Have you tied [csvjoin](http://csvkit.readthedocs.io/en/1.0.1/tutorial/3_power_tools.html#csvjoin-merging-related-data)? I think that will do what you need. You can then use `csvcut` to remove any extra columns from `csvjoin`.

**Comment by RickCogley** [comment]
Hi, thanks. Yes, and it did not want to do the "cartesian product" like I need. It seems to require some actual link field between the tables to be joined..

**Comment by jpmckinney** [comment]
Ah, I see. So `Id` is completely irrelevant in the example. No, sorry, no existing tool has that functionality, and csvkit is frozen for new tools (though adding new features to existing tools is ok).

**Comment by RickCogley** [comment]
Hi @jpmckinney, understood & thank you. I can do it with sqlite, adding the CSV files to it, and doing a ``select *``. The default is the cartesian product.
