### ISSUE TITLE
field larger than field limit (131072)

### ISSUE THREAD

**Issue by doekman** [wireservice/csvkit#812]
When running the command `csvsql --db postgresql://postgres@localhost/archi_db_dev --no-create --insert pc_fr.csv --db-schema lookup --table postcode`, I get the error message `field larger than field limit (131072)`.

The schema and csv file are attached in [test.zip](https://github.com/wireservice/csvkit/files/865198/test.zip).

I've analysed the csv file, but all columns are within the limits of the pre-created table. Also, the bug seems a bit random, because yesterday I got the error message on another csv file (postal codes of another province). Yesterday, the bug happened multiple times with the other datafile, today it loads fine. But now the included file doesn't want to load (both when the table is truncated and recreated).

Questions:

1. What is causing this bug? The number 131072 looks like a line number, but it probably isn't, because that line loads correctly.
2. If a field (line/column) can't be loaded, it would be helpful if line and column numbers would be included in the error message.

**Comment by jpmckinney** [comment]
Can you run the same command with `-v` to get the full output, to see where the error is originating from?

**Comment by doekman** [comment]
Hope this helps:

    Traceback (most recent call last):
      File "/usr/local/bin/csvsql", line 11, in <module>
        sys.exit(launch_new_instance())
      File "/usr/local/lib/python3.5/site-packages/csvkit/utilities/csvsql.py", line 160, in launch_new_instance
        utility.main()
      File "/usr/local/lib/python3.5/site-packages/csvkit/utilities/csvsql.py", line 106, in main
        **self.reader_kwargs
      File "/usr/local/lib/python3.5/site-packages/csvkit/table.py", line 236, in from_csv
        for i, row in enumerate(rows):
      File "/usr/local/lib/python3.5/site-packages/csvkit/py3.py", line 22, in __next__
        return next(self.reader)
    _csv.Error: field larger than field limit (131072)

**Comment by jpmckinney** [comment]
Aha, I think you need to use the solution here (csvkit uses agate which uses Python's csv module): http://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072

**Comment by abcfy2** [comment]
I have the same issue when a filed is too long. Is there any way to solve this issue without modify `csvkit` code?

I find there is a common argument `-z MAXFIELDSIZE, --maxfieldsize MAXFIELDSIZE`, but it seems not working on `csvjoin` and `csvcut`:

```
'maxfieldsize' is an invalid keyword argument for this function
```

**Comment by jpmckinney** [comment]
csvcut --maxfieldsize 1000 examples/dummy.csv

Works for me. What's the full command you're running?

**Comment by abcfy2** [comment]
Sorry. I'm using `0.9.1`, and I try to use `1.0.2`, it's OK.

`1.0.2` is slower than `0.9.1`, and will change `0` to `False`, `1` to `True`. So I don't like to use this version.

**Comment by jpmckinney** [comment]
I'm not aware that csvcut is any slower, since it streams. Only the buffering commands are likely to be slower.
