### ISSUE TITLE
Support "create table if not exists"

### ISSUE THREAD

**Issue by jez** [wireservice/csvkit#813]
When importing multiple CSV files into a SQL (which all share the same table schema), it would be great if csvsql used `CREATE TABLE IF NOT EXISTS foo`.

### Current vs. Desired Usage

Consider this shell code, which dynamically generates CSV files (say, by making requests to a JSON API, munging the data, and spitting out a CSV file):

```shell
for thing in $THINGS; do
  # ...
  # process $thing, generate $thing.csv
  # ...

  # Load $thing.csv into SQLite database
  csvsql --db sqlite:///foo.db --insert $thing.csv
done
```

This will currently fail for every loop iteration after the first `$thing`, because it uses this SQL to create the table:

```sql
CREATE TABLE ... (
...
);
```

Ideally, I'd be able to have a flag like `--create-if-not-exists` (substitute the name of your choice here, like `--create`, `--create-force`, `--create-silent`, etc.), which generates this SQL:

```sql
CREATE TABLE IF NOT EXISTS ... (
...
);
```

### Implementation Considerations

It's possible this change would have to be made in accordance with an upstream change to `agate-sql`. If this is not the correct place to report an issue, let me know.

If this is a feature you'd consider, but you don't want to do it yourself, I'd be glad to lend a hand.

**Comment by jpmckinney** [comment]
`--create-if-not-exists` is clear and good. I think we'd just need to add a keyword argument in agate-sql and use `checkfirst=` in the [`sql_table.create()`](https://github.com/wireservice/agate-sql/blob/master/agatesql/table.py#L211) line. Then add the command-line option to csvkit's csvsql tool, add some tests, and update the changelog. If you can do that, it'd be much appreciated :)

**Comment by jpmckinney** [comment]
Closed by #815

**Comment by jest** [comment]
Please bump required version of agate-sql to 0.5.2 (master), as 0.5.1 doesn't have create_if_not_exists.

**Comment by jez** [comment]
Right now the requirements declares that csvkit depends on agate-sql at HEAD, not 0.5.1. Freshly installing csvkit should pull down the correct agate-sql version.

When I was working on this though, there did seem to be some weirdness with how pip handles packages from Git. You might have to pip uninstall and pip install agate-sql to trick pip into upgrading. If anything, I'd call this a pip bug.

Of course, it would be nice to have an 0.5.2 release of agate-sql on pip to depend on directly.

**Comment by jest** [comment]
Well, no, https://github.com/wireservice/csvkit/blob/master/setup.py#L10 specifies `agate-sql>=0.5.1`. So when you install csvkit from git:

```
pip install git+git://github.com/wireservice/csvkit.git
```

it installs fine, with agate-sql 0.5.1 (which is enough according to `setup.py`), but doesn't work. Honestly, I'd rather like to have installation fail, because 0.5.2 is not released, then install agate-sql from git in the same way, and have working installation.

**Comment by jez** [comment]
Oh, I didn't know it was also specified in setup.py! That would have helped
when I was trying to figure out why it was acting up XD

**Comment by jest** [comment]
Now I see `requirements-py3.txt`... Expectations mismatch, I guess :)

**Comment by jpmckinney** [comment]
We'll bump the requirements once the dependencies are actually released :)

There are many cases where old dependencies work fine, except for the one new feature that requires them. I don't think it's preferable to make installing csvkit HEAD more complicated for everyone (who might be writing pull requests, etc.) just to make it simpler for those who want the most bleeding-edge feature.

**Comment by jest** [comment]
I understand that point of view, but at the moment `csvsql` doesn't work at all, because the new option is just a switch and the call to `to_sql` always passes `create_if_not_exists` option...

I know, I'm using unreleased software, but maybe some developer docs could mention such surprises?

**Comment by jpmckinney** [comment]
Sure, can you create an issue? The solution is to install csvkit from git into a virtualenv, and then install its dependencies (in this case just agate-sql) from git after csvkit is installed.

**Comment by jest** [comment]
Sure, #818.
