### ISSUE TITLE
failed to create process. on windows after installing via pip in virtualenv

### ISSUE THREAD

**Issue by adamcunnington** [wireservice/csvkit#816]
Hi there,

I'm on python 3.5.1 and i have installed csvkit using pip inside my virtualenv (pyvenv). It installed succesfully but when I try to use any of the commands such as csvstack, I receive the non-descript error:
"failed to create process."

I suspect this is a python error rather than a csvkit error. I have ensured that both pip and setuptools are fully up to date.

Is this a known issue?

**Comment by adamcunnington** [comment]
Looks like on windows the shebang line must be encased with "".

I.e.: in each of the script\*-script.py files, the line:
#!"c:\path-to-virtual-env\scripts\python.exe"

needs changing to
#!"c:\path-to-virtual-env\scripts\python.exe"

**Comment by jpmckinney** [comment]
The lines you pasted are identical? Anyhow, seems like the solution did not have to do with csvkit.
