### ISSUE TITLE
Add PYTHONIOENCODING to tricks.rst: UTF-8 sequences generated from csvlook cannot be encoded when the output is redirected

### ISSUE THREAD

**Issue by jest** [wireservice/csvkit#817]
I use csvlook to generate the table:

```
$ csvlook some.csv
| SolverTaskId | SolverOrderId | SrcPoiId | DstPoiId |   Weight |  Volume |            LoadDate | Amount | AmountUnit |
| ------------ | ------------- | -------- | -------- | -------- | ------- | ------------------- | ------ | ---------- |
|          243 |       444 587 |   29 077 |   28 951 |   138,90 |  4,040… | 2016-01-08 00:00:00 |        |            |
...
```

Please note (I'm not sure it's correctly encoded in the above output), that after "444" there is a U+00A0 character (NBSP). The output is correctly encoded UTF-8.

When I want to redirect the output to a pipe or a file, the exception is thrown:

```
$ csvlook some.csv >/dev/null
'ascii' codec can't encode character u'\xa0' in position 26: ordinal not in range(128)
```

This clearly looks like #315; however, I'm on a master branch, installed with `pip install git+git://github.com/wireservice/csvkit.git`.

**Comment by jest** [comment]
After digging a bit, I see it is a general problem for Python users. I'm myself not a Python programmer, however I struggled for years with the very same cases in Perl as you do, so I sympathize. :)

Maybe it should be solved once and for all in csvkit by:

1. adding to generic options the one that specifies the output file and output encoding, and when it is passed, open, configure the encoding and set in `CSVKitUtility.output_file`.
2. Letting people know in the docs that if they want to redirect to pipe or otherwise force the encoding, they should set `PYTHONIOENCODING=utf8`.

Both can be done independently.

**Comment by jpmckinney** [comment]
Can you upload the CSV (you may need to upload as ZIP) so that I can try to reproduce the error?

**Comment by jest** [comment]
[test.txt](https://github.com/wireservice/csvkit/files/914552/test.txt)

```
$ csvlook test.txt 
| SolverTaskId | SolverOrderId | SrcPoiId | DstPoiId | Weight | Volume |            LoadDate | Amount | AmountUnit |
| ------------ | ------------- | -------- | -------- | ------ | ------ | ------------------- | ------ | ---------- |
|          243 |       444 587 |   29 077 |   28 951 |  138,9 | 4,040… | 2016-01-08 00:00:00 |        |            |
$ csvlook test.txt | cat
'ascii' codec can't encode character u'\xa0' in position 26: ordinal not in range(128)
| SolverTaskId | SolverOrderId | SrcPoiId | DstPoiId | Weight | Volume |            LoadDate | Amount | AmountUnit |
| ------------ | ------------- | -------- | -------- | ------ | ------ | ------------------- | ------ | ---------- |
$ PYTHONIOENCODING=ascii csvlook test.txt | cat
'ascii' codec can't encode character u'\xa0' in position 26: ordinal not in range(128)
| SolverTaskId | SolverOrderId | SrcPoiId | DstPoiId | Weight | Volume |            LoadDate | Amount | AmountUnit |
| ------------ | ------------- | -------- | -------- | ------ | ------ | ------------------- | ------ | ---------- |
$ PYTHONIOENCODING=utf8 csvlook test.txt | cat
| SolverTaskId | SolverOrderId | SrcPoiId | DstPoiId | Weight | Volume |            LoadDate | Amount | AmountUnit |
| ------------ | ------------- | -------- | -------- | ------ | ------ | ------------------- | ------ | ---------- |
|          243 |       444 587 |   29 077 |   28 951 |  138,9 | 4,040… | 2016-01-08 00:00:00 |        |            |
```

**Comment by jpmckinney** [comment]
I can't reproduce. Your shell environment may have an issue. My possibly relevant output of `printenv` is:

```
LANG=en_CA.UTF-8
LC_CTYPE=en_CA.UTF-8
```

What's your output of `printenv | grep "LANG\|LC"` ?

**Comment by jest** [comment]
It's generally all UTF-8:

```
LC_PAPER=pl_PL.UTF-8
LC_ADDRESS=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_NUMERIC=pl_PL.UTF-8
LC_TELEPHONE=pl_PL.UTF-8
LC_IDENTIFICATION=pl_PL.UTF-8
LANG=en_US.UTF-8
GDM_LANG=en_US
LC_MEASUREMENT=pl_PL.UTF-8
LANGUAGE=en_US
LC_TIME=pl_PL.UTF-8
LC_NAME=pl_PL.UTF-8
```
but it doesn't matter... When stdout is redirected, Python guesses from the environment (unless PYTHONIOENCODING is set) what encoding to use. And when you don't know what it is, you can't send "unsafe" Unicode characters.

That's why I propose outputting to a file: the encoding is deterministic, as it can be set on a writer.

**Comment by jpmckinney** [comment]
Hmm, I just find it unusual that I can't reproduce the error. Using standard command line output redirection is preferable to adding another option to csvkit.

**Comment by jest** [comment]
If you google the error message you will see, how big the problem is. A lot of people stumble upon it, either as programmers (which is less of a problem due to their capabilities), or as users — and then they are in bigger trouble, as they "just run a tool, and it doesn't work".

Within a week I'll try to describe the workaround (PYTHONIOENCODING) in FAQ.

**Comment by jpmckinney** [comment]
Sounds good - I'd be happy to merge that.

**Comment by Fil** [comment]
See https://docs.python.org/2/using/cmdline.html#envvar-PYTHONIOENCODING and https://docs.python.org/3/using/cmdline.html#envvar-PYTHONIOENCODING

**Comment by jpmckinney** [comment]
What version of Python are you running, by the way?

**Comment by jest** [comment]
Stock Ubuntu 2.7.6

**Comment by jpmckinney** [comment]
Can you run `python --version` and paste the output?

**Comment by jest** [comment]
Well... what's the point? I know, what I'm writing...

```
$ python --version
Python 2.7.6
```

**Comment by jpmckinney** [comment]
It's pretty key to being able to reproduce the error :)

**Comment by jest** [comment]
Well, in my opinion you can trust so many search results on this case in the internet.

You can't solve this error occurring to users, because that's not a bug, it's a way Python works.

If you want to simulate the error condition (NOT error reasons), set the env appropriately

```
export PYTHONIOENCODING=ascii
```

On the other hand, it is possible to forcefully convert string to UTF-8 octets and send them to the underlying stream, but that's quite different and requires more testing and the code is not portable between Python 2 and 3.

http://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3

**Comment by jpmckinney** [comment]
So, will you write a pull request?

> Within a week I'll try to describe the workaround (PYTHONIOENCODING) in FAQ.

**Comment by jest** [comment]
Sure :)

**Comment by jest** [comment]
Well, I sat down to write about it, and discovered that the problem occurs only when calling `csvlook`. When I change the command to `csvformat`, there is no encoding error, even on piping the stdout. Is there some difference in how they prepare/encode/print the strings to stdout?

**Comment by jpmckinney** [comment]
Some csvkit tools stream the input like `csvformat`, while others buffer it like `csvlook`. The other buffering tools are listed here, if you want to try with one of those (maybe `csvsort`): http://csvkit.readthedocs.io/en/1.0.1/contributing.html#streaming-versus-buffering
