### ISSUE TITLE
csvlook loads some CSV files wrongly

### ISSUE THREAD

**Issue by halloleo** [wireservice/csvkit#822]
csvlook seems load data wrongly from some CSV files. Using the file `flights.csv` (from the attached archive [flights.zip](https://github.com/wireservice/csvkit/files/912399/flights.zip)) I issue

   csvlook -H flights.csv > flights.md

The resulting file `flights.md` (as well in the archive) does contain in the first column the cells:

    0001-05-29
    0001-05-29
    0001-05-29
    0001-06-05
    0001-07-13
    0001-07-13

None of these values even exists in the original CSV file! Instead I would expect as the first column:

    DEPARTURE: MONDAY 29 MAY
    DEPARTURE: MONDAY 29 MAY
    DEPARTURE: MONDAY 29 MAY
    DEPARTURE: MONDAY 05 JUN
    DEPARTURE: WEDNESDAY 12 JUL   ARRIVAL: THURSDAY 13 JUL
    DEPARTURE: THURSDAY 13 JUL

**Comment by jpmckinney** [comment]
agate's date-time parsing can sometimes be a bit aggressive, but you can use `--no-inference` to disable that.

**Comment by halloleo** [comment]
Thanks for the pointer to `--no-inference`. Now it works perfectly. Question is for me though whether inference should be the *default* behaviour...

**Comment by jpmckinney** [comment]
There have been long conversations about that, and it would be too big of a breaking change to flip the default. (There are also reasons for it being the default.)
