### ISSUE TITLE
Issue with csvjoin

### ISSUE THREAD

**Issue by 7starsone** [wireservice/csvkit#826]
Hello,
i have two csv files
on the header of the files there's the exact column name
I need to join them in a unique csv file where column field from the 1st file matches a column field from the 2nd file, identified by the header column name

eg. on the **1st csv file**

`Name;Code; Supplier ref code;... ` #this is the header

`one; 1; wwwone; ` #these are the values

and on the **2nd csv file**
`Some;Supplier ref code;Thing; ...` #this is the header

`a; wwwone; c ;d` #these are the values

they need to become, joined...
`one; 1; wwwone; a; wwwone; c; d`

If I do
csvjoin -c "Supplier ref code, Supplier ref code" --left one.csv two.csv > final.csv

I get **Column identifier "Supplier ref code" is neither an integer, nor a existing column's name.**

Or I don't understand how to do it...or ?
please help, thanks

**Comment by jpmckinney** [comment]
The column names specified by the `-c` option need to be present in both files. Here, you've specified two columns, and a different one occurs once in each file. You will need to rename your column header.

**Comment by 7starsone** [comment]
no, sorry...as you can see the columns I need with the same name are on each file...unless you mean that the same columns must be on each file and so wouldn't be so useful...

**Comment by jpmckinney** [comment]
One file has a column that starts with a space, the other doesn't. So, they are not identical.

**Comment by 7starsone** [comment]
nothing to do... it doesn't work
I tried
`csvjoin -c "Supplier ref code,Supplier ref code" --left one.csv two.csv > final.csv`
so, without space...

`csvjoin -c "Supplier ref code" --left one.csv two.csv > final.csv`
`csvjoin -c "Supplier ref code" one.csv two.csv > final.csv`

nothing... **Column identifier "Supplier ref code" is neither an integer, nor a existing column's name.**

**Comment by 7starsone** [comment]
ops, you're right...but it doesn't start with a space, it ends with a space lol I checked the file

so, one is "Supplier ref code" and the other is "Supplier ref code "

i will try later...thanks

**Comment by 7starsone** [comment]
is possible in this case to run it anyway...or am i forced to edit the file ?

**Comment by jpmckinney** [comment]
You could have used `--skipinitialspace` if the space were at the start of the field, but you will need to edit the header in your case.
