### ISSUE TITLE
csvformat -T -U3: asks for -P but can be pleased with -Q 

### ISSUE THREAD

**Issue by sfischer13** [wireservice/csvkit#830]
Import of tab-separated data works as expected:
```
echo 'A\tB\tC\n"1"\t2\t""3""' | in2csv -f csv -t -u3  | csvlook

| A   | B | C     |
| --- | - | ----- |
| "1" | 2 | ""3"" |
```
Export with the same settings breaks:
```shell
echo 'A\tB\tC\n"1"\t2\t""3""' | in2csv -f csv -t -u3  | csvformat -T -U3

A	B	C
need to escape, but no escapechar set
```
However, providing a dummy value for -Q makes it work again:
```
echo 'A\tB\tC\n"1"\t2\t""3""' | in2csv -f csv -t -u3  | csvformat -T -U3 -Q X
A	B	C
"1"	2	""3""
```

**Comment by jpmckinney** [comment]
Python's csv library, on which we rely, requires those dummy values in case it needs to use them (it doesn't try first and then determine whether it needed them). The reason you need to be more explicit on output is because csvkit will just make assumptions on input.
