### ISSUE TITLE
'charmap' codec can't encode character '\u0106' in position 182: character maps to <undefined>

### ISSUE THREAD

**Issue by chx** [wireservice/csvkit#831]
Test file at https://gist.github.com/chx/4a8751962b8fe6dca00d8b5aca3ac646 . I tried with all sorts of encoding: `in2csv.exe -f xls -e UTF8`, `-e UTF-8` `-e iso-8859-1` and without `-f` and got nowhere really. I believe it's UTF-8.

**Comment by jpmckinney** [comment]
Hi @chx :) I can't reproduce on my system. Can you provide more of the information requested here? https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug

**Comment by chx** [comment]
I can't reproduce now either --  not with this file neither with the longer version I originally tried with. This is super odd. I did see the error message -- not like I could've made it up myself. Really have no idea what happened there. It's Windows and this was just after install. Perhaps I needed to open a new command window to test in? Anyways: sorry for the noise.
