### ISSUE TITLE
in2csv - SyntaxError

### ISSUE THREAD

**Issue by MortalCatalyst** [wireservice/csvkit#832]
Hi

I am trying to replicate the basic example of converting json to csv in the intro tutorial.

On the command line I have entered this but it returns a syntax error.

```
In [1]: import csvkit

In [2]: in2csv data2.json > data2.csv
  File "<ipython-input-2-706cb9b64e69>", line 1
    in2csv data2.json > data2.csv
               ^
SyntaxError: invalid syntax
```

Why exactly is this?

**Comment by jpmckinney** [comment]
Please provide the information described here: https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug

**Comment by jpmckinney** [comment]
Oh, I just realized: `import csvkit` is something you put in the Python shell, but `in2csv data2.json > data2.csv` is something you need to put in the command-line shell.
