### ISSUE TITLE
in2csv: Add support for input format of 'feather'

### ISSUE THREAD

**Issue by mpettis** [wireservice/csvkit#835]
Feature request: Add support for reading files of format 'feather'.  Here is the repo for it: https://github.com/wesm/feather

Use case: 'feather'  files are an interop format for data files for doing data science between R and Python.  It allows one to preserve column type information within the metadata of the 'feather' file.  However, it is not easy to peek inside of them to see the contents.  As this is where `csvkit` excels as a tool, it would be nice to have support to point `in2csv` at a feather file and get CSV out for quick inspections.

Thank you for this great tool,
Matt

**Comment by jpmckinney** [comment]
I'm unlikely to get to this, but I would accept a pull request :)

**Comment by jpmckinney** [comment]
No other interest expressed since 2017, so closing.
