### ISSUE TITLE
Avoid displaying line numbers

### ISSUE THREAD

**Issue by doganmeh** [wireservice/csvkit#840]
Help says:
```
-l, --linenumbers     Insert a column of line numbers at the front of the
                        output. Useful when piping to grep or as a simple
                        primary key.
```
however, `csvcut -n` shows line numbers anyways. 

I need to get rid of the line numbers so I can pipe to grep and filter column names via regexp. Such as:
`csvcut -n my_file.csv|grep '5G\|05ARE'`

**Comment by jpmckinney** [comment]
`-n` isn't printing line numbers. It's printing column indexes, which can be used as the parameter value for the `--columns` option and others. You can ignore the first few characters of each line with a command like:

    csvcut -n examples/dummy.csv | cut -c6-

**Comment by doganmeh** [comment]
seems from 3 digit to 4, column indices printed with a different format:

```
999: CS9ADE14D
1000: CS9ADM14N
```

this makes it harder to process. Isn't an option to hide indices handy?

**Comment by jpmckinney** [comment]
```
echo "999: CS9ADE14D
1000: CS9ADM14N" | cut -d ' ' -f 2
```

**Comment by doganmeh** [comment]
that alone is not enough since indices up to 100 have leading spaces. i had to chain two cuts as such:

`|cut -d ":" -f 2|cut -d " " -f 2`

if I had a choice though, I would definitely take the option to hide indices. thanks for the response.
