### ISSUE TITLE
csvformat: Set number format

### ISSUE THREAD

**Issue by rawdlite** [wireservice/csvkit#842]
I am using csvsql and csvformat to convert files which I send to my tax consultant. The program she uses (Datev) expects a csv format with encoding ISO-8859-1 and a colon as the decimal point.
This is a format that is (unfortunately) widely in use in my country.
It would be great if there was an option in csvformat to achieve this.

**Comment by jpmckinney** [comment]
For output encoding, csvkit prints to standard output, so you would have to set the encoding of your shell environment, or use `PYTHONIOENCODING` https://csvkit.readthedocs.io/en/1.0.2/tricks.html#python-standard-output-encoding-errors

**Comment by jpmckinney** [comment]
What country is that? I looked through all the decimals here http://www.unicode.org/Public/cldr/31.0.1/core.zip and found only `.`, `,` and `٫` as decimal separators.
