### ISSUE TITLE
csvcut: Express --columns, etc. as column range

### ISSUE THREAD

**Issue by exwhyz** [wireservice/csvkit#843]
Are there any plans to add support for column ranges in csvcut? Currently you have to explicitly specify a list of columns as indicated in the docs. Would be great if an option for a range of columns can be added.

-c COLUMNS, --columns COLUMNS
                        A comma separated list of column indices or names to
                        be extracted. Defaults to all columns.

**Comment by godspeedyou** [comment]
Have you tried it or did you just rely on the docs? I experienced that you can give a range for csvcut and it will work. 
E. g.: `csvcut -c 1-13 data.csv`

**Comment by jpmckinney** [comment]
Indeed. I've updated the `--help` message to describe ranges.
