### ISSUE TITLE
csvcut + csvstat fails

### ISSUE THREAD

**Issue by denzilc** [wireservice/csvkit#844]
I am trying to pipe `csvcut` on some columns to `csvstat` with this command `csvcut -c 31,33,39 data.csv | csvstat` but I get the following error : 

`Row 0 has 11 values, but Table only has 3 columns.`

Unfortunately, I can not upload my CSV file due to data security reasons. I tried repeating the same command on the NPR data linked in the tutorial but it works. I'm wondering if we could debug this without having to upload my CSV file.

**Comment by denzilc** [comment]
Just to add, if I do a `head data.csv | csvstat` it works for me. So, I feel this might be a bug.

**Comment by jpmckinney** [comment]
Can you run both commands with `-v` as described here: https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst

And then share at least the traceback as otherwise there is no way to debug.

**Comment by denzilc** [comment]
Here, you go

`csvcut -c 31,33,39 exp_dataset.csv -v | csvstat -v`

> Traceback (most recent call last):
>   File "/home/denzil/anaconda3/bin/csvstat", line 11, in <module>
>     sys.exit(launch_new_instance())
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/utilities/csvstat.py", line 335, in launch_new_instance
>     utility.run()
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/cli.py", line 114, in run
>     self.main()
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/utilities/csvstat.py", line 137, in main
>     **self.reader_kwargs
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/agate/table/from_csv.py", line 88, in from_csv
>     return Table(rows, column_names, column_types, row_names=row_names)
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/agate/table/__init__.py", line 124, in __init__
>     raise ValueError('Row %i has %i values, but Table only has %i columns.' % (i, len_row, len_column_names))
> ValueError: Row 0 has 11 values, but Table only has 3 columns.

And , `head exp_dataset.csv -v | csvstat -v`

> Traceback (most recent call last):
>   File "/home/denzil/anaconda3/bin/csvstat", line 11, in <module>
>     sys.exit(launch_new_instance())
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/utilities/csvstat.py", line 335, in launch_new_instance
>     utility.run()
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/cli.py", line 114, in run
>     self.main()
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/csvkit/utilities/csvstat.py", line 137, in main
>     **self.reader_kwargs
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/agate/table/from_csv.py", line 88, in from_csv
>     return Table(rows, column_names, column_types, row_names=row_names)
>   File "/home/denzil/anaconda3/lib/python3.5/site-packages/agate/table/__init__.py", line 124, in __init__
>     raise ValueError('Row %i has %i values, but Table only has %i columns.' % (i, len_row, len_column_names))
> ValueError: Row 0 has 214 values, but Table only has 1 columns.

But, `head exp_dataset.csv | csvstat` works.

**Comment by jpmckinney** [comment]
Hmm, I think I need at least one row of data from `csvcut -c 31,33,39 exp_dataset.csv`. That command should output 3 columns, but csvstat thinks it's receiving 11 columns…

(The second one doesn't work because `head` doesn't take a `-v` option — I just meant adding `-v` on csvkit commands.)

**Comment by jpmckinney** [comment]
Actually, does just `csvcut -v -c 31,33,39 data.csv` run without error?

**Comment by denzilc** [comment]
Yes `csvcut -v -c 31,33,39 data.csv` runs without any error. Does that help you understand the issue better?


> (The second one doesn't work because head doesn't take a -v option — I just meant adding -v on csvkit commands.)

Sorry - so stupid of me!

**Comment by jpmckinney** [comment]
I don't think I can reproduce the error without sample data. Can you just manually replace the private data with random strings?

**Comment by jpmckinney** [comment]
@denzilc Try `csvstat --snifflimit 0` in your commands and let me know if it works.

**Comment by denzilc** [comment]
@jpmckinney The `--snifflimit 0` option works.  I'd like to understand why this happens.

**Comment by jpmckinney** [comment]
I wrote a bit about why it works here: https://github.com/wireservice/csvkit/issues/751#issuecomment-310811491

I'll update the documentation so that this is easier to debug.
