### ISSUE TITLE
Add ability to randomize a csv, keeping headers?

### ISSUE THREAD

**Issue by dartdog** [wireservice/csvkit#846]
Feature suggestion...
With many machine learning algorithms and other data exploration getting the Data randomized can be a bit of a chore, you have a great sort option but no way to use that to get the file randomized that I can figure out, love the CSVKIT tool and It think many would find this useful, While I can pretty easily write it in Python, it is not a general solution and I have to pretty much do it each time,, gnu shuffle does not allow keeping the headers,,    of course the answer there is clip the header, randomize the file and rejoin the header,, all kind of clunky there is this https://github.com/pereorga/csvshuf but it won't install on py36..of course I can probably just git install it...

**Comment by jpmckinney** [comment]
I think the solution is to use csvshuf from git (or install multiple versions of Python in order to use whichever Python version it supports) or work with the author of csvshuf to get it working on Python 3.6.
