### ISSUE TITLE
field with 1 for the column, csvlook will turn 1 into 'True'

### ISSUE THREAD

**Issue by kevinwkc** [wireservice/csvkit#849]
field with 1 for the whole column, csvlook will turn 1 into 'True'

ie)
a|1|great
becomes
a|True|great

sorry cannot provide input because it sensitive data

python 3.6.0 :: Anaconda 4.3.1 (64-bit)
csvlook 1.0.2

**Comment by tos-kamiya** [comment]
Hi,

Sorry for interrupting.

I suspect that issue is related to `agate.data_type`'s type inferring function.
It guess a single value 1 be a boolean, not integer, e.g.,

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import agate
>>> t = agate.TypeTester()
>>> t.run([[2]], ['b'])
(<agate.data_types.number.Number object at 0x7fe379920fd0>,)
>>> t.run([[1]], ['b'])
(<agate.data_types.boolean.Boolean object at 0x7fe379920f60>,)
```

**Comment by jpmckinney** [comment]
@kevinwkc Use `--no-inference` to disable type inference.
