### ISSUE TITLE
in2csv: --no-header-row for Excel files

### ISSUE THREAD

**Issue by jsekamane** [wireservice/csvkit#853]
When converting a xls file to csv, using `in2csv` I get a warning that the there are duplicate column names (and the columns are renamed) – despite the fact that i use the `no-header-row` option? This seems to be a bug, or did I misunderstand something?

Command:

    in2csv -I -H test1.xls > test1.csv

Output:

    /usr/local/lib/python3.5/site-packages/agate/utils.py:291: DuplicateColumnWarning: Column name "x" already exists in Table. Column will be renamed to "x_2".

I am using Python 3.5.2

**Comment by jpmckinney** [comment]
`--no-header-row` has no effect on Excel inputs, but it can be added as a new feature.

**Comment by jpmckinney** [comment]
@jsekamane Note that if you use `--no-header-row`, a default header row will be created with columns `a,b,c,d,…`. Is that what you want?

**Comment by jsekamane** [comment]
@jpmckinney Yes.

**Comment by ceemjay** [comment]
Upvote for having an option for Excel files without a header row. All the files I am trying to process with in2csv do not have header rows!

Initially I had assumed that was what -H did - it really needs that option for both in and out.

Anyway thanks for this tool set it is truly great and I hope you make it even better with this addition!!

**Comment by jpmckinney** [comment]
Fixed, but until new versions of agate-excel and csvkit are released, you'll have to install the GitHub version of agate-excel on top of your installation of csvkit.

**Comment by ceemjay** [comment]
Great will give it a go!

Found another funny thing today, some of my XLS files have embedded
newlines in some cells. Can in2csv handle that elegantly (ie delete or
convert to something else) as this completely screws up the CSV?

Clive

---sent from a mobile device

**Comment by jpmckinney** [comment]
csvkit will properly quote the cells containing newlines. There's no feature to replace/remove newlines.
