### ISSUE TITLE
agate-sql: csvsql: Add support for crate

### ISSUE THREAD

**Issue by alitrack** [wireservice/csvkit#857]
from the DDL it created, I am afraid it is for Postgres, not for crate

···
(crate.client.exceptions.ProgrammingError) SQLActionException[SQLParseException:
 line 3:9: no viable alternative at input 'amount DECIMAL'] [SQL: '\nCREATE TABL
E xaa (\n\tamount DECIMAL, \n\t"Brand_name" VARCHAR(20), \n\tbrandname VARCHAR(2
3), \n\tcatname VARCHAR(6), \n\tcustomer_id VARCHAR(10), \n\tquantity DECIMAL, \
n\tpurchase_date DATE, \n\t"Transaction_id" DECIMAL, \n\t"Price" DECIMAL, \n\tfl
ag BOOLEAN, \n\t"Purchase_Year" DECIMAL, \n\t"Purchase_Month" DECIMAL, \n\t"Cat_
id" DECIMAL, \n\t"Brand_id" DECIMAL, \n\t"Product_id" DECIMAL, \n\tgroup_sale BO
OLEAN, \n\tproductname VARCHAR(19), \n\tfloor DECIMAL\n)\n\n']
···

Decimal should be double

varchar(*) should be string

**Comment by jpmckinney** [comment]
Can you provide the command you ran? (see the checklist at https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug when reporting an issue)

**Comment by alitrack** [comment]
* the csvkit command (for example, csvstat -v test.csv)

```
csvsql -v  --db crate://localhost:4200 --insert mtcars.csv
```
* the input file (rename the .csv to .txt for GitHub)
[mtcars.txt](https://github.com/wireservice/csvkit/files/1148847/mtcars.txt)


* the output text (including the traceback)
[issue.txt](https://github.com/wireservice/csvkit/files/1148846/issue.txt)

* the Python version (python --version)

Python 3.6.1

* the operating system and version

Mac OS X 10.12.5 (16F73)

**Comment by jpmckinney** [comment]
Hmm, yes, the challenge has been to find types supported by the widest range of SQL implementations. If you want to have a look, the code to change is in https://github.com/wireservice/agate-sql/blob/master/agatesql/table.py

**Comment by alitrack** [comment]
btw, I tried pandas.to_sql, it is much faster than csvsql

**Comment by jpmckinney** [comment]
Sure - if you're writing Python code, use something like pandas or agate. csvkit is just for the command-line.

**Comment by jpmckinney** [comment]
https://github.com/wireservice/agate-sql/commit/f46bffb9125c7d5b9d0b41628a111f0ee1d8dd16
