### ISSUE TITLE
CSVSQL: Dealing with multiple double quotes

### ISSUE THREAD

**Issue by sagnikbakshi** [wireservice/csvkit#862]
Hi,

I am trying to load a CSV file where certain strings contain double quotes, e.g.:
"abc"de"fghij"klm"n"

Is there a way we can run CSVSQL to consider the above as a single string and upload abc"de"fghij"klm"n to the database?

Thanks.

**Comment by jpmckinney** [comment]
Try with `--quoting 3` to treat the `"` as text.

**Comment by sagnikbakshi** [comment]
Thanks James.
