### ISSUE TITLE
csvsql: Quotes and delimiters within strings

### ISSUE THREAD

**Issue by sagnikbakshi** [wireservice/csvkit#863]
I am trying to run csvsql on a file with the following format:

header1,header2,header3
aaa,bb,ccc
ddd,eee,"this, is "a, sample quote""

Is there any way that I can store "this, is "a, sample quote"" as a single string in the database?

If I run the above using the _--quoting 3_ parameter, I get the following error: Row 1 has 5 values, but Table only has 3 columns (which, obviously, is because csvsql considers the commas within the quotes as delimiters".

If I run csvsql without the _quoting_ parameter, then I get the following: Row 1 has 4 values, but Table only has 3 columns.

Any help to get around this would be appreciated.

Thanks.

**Comment by jpmckinney** [comment]
It's not possible to both ignore quotes and ignore commas within quotes. You will need to manually repair your file by either:

* using doublequotes to escape the quotes within a quoted string

```
header1,header2,header3
aaa,bb,ccc
ddd,eee,"this, is ""a, sample quote"""
```

* setting `--quoting 3 --escapechar \\` and escaping the delimiter

```
header1,header2,header3
aaa,bb,ccc
ddd,eee,"this\, is "a\, sample quote""
```
