### ISSUE TITLE
Errors importing geojson with complex types

### ISSUE THREAD

**Issue by jayvdb** [wireservice/csvkit#871]
A nice collection of more diverse examples of geojson, using other [Geometry objects](https://tools.ietf.org/html/rfc7946#section-3.1), can be found at https://github.com/node-geojson/geojson-flatten/tree/master/test/fixture , showing a few importing issues.

```
$ for file in *.geojson; do echo "$file:"; in2csv --format geojson $file > $file.csv ; done
multigeometry.input.geojson:
multigeometry.output.geojson:
too many values to unpack
multilinestring.input.geojson:
multilinestring.output.geojson:
multipoint.input.geojson:
multipoint.output.geojson:
multipolygon.input.geojson:
multipolygon.output.geojson:
nullgeometry.input.geojson:
'NoneType' object has no attribute 'get'
nullgeometry.output.geojson:
'NoneType' object has no attribute 'get'
point.input.geojson:
'coordinates'
point.output.geojson:
'coordinates'
```

I'm not sure the `nullgeometry` represents a valid syntax, but it probably shouldnt be an Exception.
The emitting of `'coordinates'` is very odd; I hope I dont have any stray print's in my installed version.

**Comment by jpmckinney** [comment]
csvkit can round-trip all those files without error now.
