### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by jayvdb** [wireservice/csvkit#872]
I've found it non trivial to do benchmarking using `timeit` , which isnt the most accurate approach by likely good enough for decisions on this util.  This is my current attempt, which I am certain is wrong as I think I need to restore sys.stdout after each run:

```bash
setup="import csvkit.utilities.csvjson as csvjson; import os, sys; sys.stdout = open(os.devnull, 'w'); sys.argv = ['--no-inference','--lon=longitude','--lat=latitude','--indent=2','--key=id','data.csv']"
statement="csvjson.launch_new_instance()"

python3 -m timeit -s "$setup" "$statement"
```

Would be good if we can make that a little easier.

Also I need to read the CSV in the setup, and avoid the JSON write, as those parts of the process are drowning out the other performance issues.

**Comment by jayvdb** [comment]
I've got semi-reasonable stable-ish timing data out of `timeit` by manually disabling the `dump_json`, with:

```bash
$ filename='examples/test_geo.csv'
$ setup="filename='$filename';from csvkit.utilities.csvjson import CSVJSON; import os, sys, io; devnull = open(os.devnull, 'w'); data = open(filename).read(); sys.argv = ['csvjson']"
$ statement="x = CSVJSON(); x.output_file = devnull; x.args.no_inference = True; x.args.lon = 'longitude'; x.args.lat = 'latitude'; x.args.input_file = filename; x.input_file = io.StringIO(data); x.main()"

$ python3 -m timeit -s "$setup" "$statement"
100 loops, best of 3: 2.96 msec per loop
```

Ideally separating reading and writing from the processing will make that a lot cleaner.

**Comment by jpmckinney** [comment]
Thanks for performing the benchmarking for #867! Closing as I'm not sure there is an issue to resolve.
