### ISSUE TITLE
csvsql with --no-headers uses default column names instead of none.

### ISSUE THREAD

**Issue by gentunian** [wireservice/csvkit#873]
After googling and searching for issues I didn't find anything related so here I am :)

Using `csvsql -H` for inserting rows into a mysql database will try to insert rows with column names such as: `a, b, c, ...`

I really didn't find out why this was assumed instead of just: `INSERT INTO <sometable> VALUES(...)`. Mysql will infer column per position if you provide all arguments.

Is there a way to achieve the above scenario using csvsql?

**Comment by gentunian** [comment]
BTW, Is not that I couldn't make this with other tools, I'm using `awk` to create my column names something like:

`cat foo.csv | awk 'FNR==1 { printf "col1,col2,colN\n" } { print $0 }'`

just wondering if there's some hidden option I'm not able to find.

**Comment by jpmckinney** [comment]
What's the issue with having column names like `a,b,c` instead of `col1,col2,col3`?

We need to support multiple databases, not all of which will set their own default column names, so we make it consistently `a,b,c` in all databases.

**Comment by jpmckinney** [comment]
Closing, as my question was unanswered after more than a month.
