### ISSUE TITLE
csvgrep: Expose any_match parameter to allow matching in any (not all) columns

### ISSUE THREAD

**Issue by godspeedyou** [wireservice/csvkit#874]
I want to grep over all columns.

Following your example at http://csvkit.readthedocs.io/en/1.0.2/tutorial/2_examining_the_data.html

`csvgrep -c 1-13 -m "BUFFALO" data.csv `

only gives me the header row. 

Is this a bug or am I using it in the wrong manner? `csvcut -c 1-13 data.csv` works as expected. `csvgrep -c 2 -m "BUFFALO" data.csv ` also does what is expected.

It would be helpful, if there was a syntax word for just examining all columns instead of having to find out the column count and then specifying it via range syntax.

**Comment by jpmckinney** [comment]
The first instruction means "BUFFALO must match in all columns 1-13". There's an unused parameter `any_match` in the code, to allow the meaning "BUFFALO must many in any column 1-13".

I'll changed the issue title.

**Comment by jpmckinney** [comment]
Closed by #891
