### ISSUE TITLE
How to use csvsql into python program

### ISSUE THREAD

**Issue by rajrohith** [wireservice/csvkit#877]
i need to write python program for create table and load the data into postgresql  by using csv files
i tried  in the below  sample programme but not able to do
import psycopg2
import csvkit

hostname="postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" 
conn = psycopg2.connect(hostname)

csvsql --db conn --insert '/Users//Downloads/DisclosureRollUp.csv'
print(' data loaded succuessfully")

please guide me with sample code.
i appreciate your quick response

Thanks,
Raj

**Comment by jpmckinney** [comment]
Hi Raj, csvkit isn't intended to be used as a library. I recommend [agate-sql](https://github.com/wireservice/agate-sql) (used internally by csvsql) or [pandas](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html).

**Comment by jpmckinney** [comment]
To use csvkit from the commandline, you can run:

```
csvsql --db "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable" --insert '/Users//Downloads/DisclosureRollUp.csv'
```
