### ISSUE TITLE
Line breaks not handled

### ISSUE THREAD

**Issue by donpellegrino** [wireservice/csvkit#879]
Line breaks are not handled correctly.

> $ csvlook -H -v ~/Documents/test.csv 
/apps/python3-env/lib64/python3.5/site-packages/agate/table/from_csv.py:88: RuntimeWarning: Column names not specified. "('a', 'b', 'c')" will be used as names.
| a                                           | b      | c |
| ------------------------------------------- | ------ | - |
| Conference room 1                           |  "John |   |
| Please bring the M. Mathers file for review |        |   |
| -J.L.                                       |        |   |
| ,10/18/2002
                                |        |   |

Input CSV as per http://www.creativyst.com/Doc/Articles/CSV/CSV01.htm:

> Conference room 1, "John,
Please bring the M. Mathers file for review
-J.L.
",10/18/2002

csvlook 1.0.2
Python 3.5.1

**Comment by jpmckinney** [comment]
You need to use `csvlook --skipinitialspace` for that specific CSV.
