### ISSUE TITLE
agate-sql: VARCHAR used when TEXT or BLOB should be for large fields?

### ISSUE THREAD

**Issue by ChrisHardie** [wireservice/csvkit#881]
This may be an issue with an underlying library, but I thought I'd start here.

When generating a MySQL schema from a CSV file with:

`csvsql --dialect mysql --snifflimit 100000 my.csv --tables my_table`

I get a result that includes something like 

```
my_big_content_field VARCHAR(41062),
my_other_big_content_field VARCHAR(23600),
```

and of course if I try to load that CREATE statement in to MySQL, it complains:

`ERROR 1074 (42000) at line 1: Column length too big for column 'my_big_content_field' (max = 21845); use BLOB or TEXT instead`

I don't see any obvious way to force csvsql to switch to using a TEXT column type, so I'm left with manually updating the generated schema before trying to use it. Am I missing something?

**Comment by jpmckinney** [comment]
Fixed in https://github.com/wireservice/agate-sql/commit/e802dbeeb6c9a64462749c03452ef99fe51c0134
