### ISSUE TITLE
Add transpose feature

### ISSUE THREAD

**Issue by godspeedyou** [wireservice/csvkit#883]
As I can see in the docs, there doesn't seem to be a feature to rearrange a csv file, so that it's columns will be transposed as rows and vice versa.

It would be really nifty, if you could add this feature as I don't see any simple work around for this.

**Comment by jpmckinney** [comment]
In the meantime, there is a Homebrew (on macOS) and Linux tool called `csvtool` that can transpose.

**Comment by jpmckinney** [comment]
Delegating to `csvtool` instead of reimplementing in csvkit.
