### ISSUE TITLE
Can't install latest

### ISSUE THREAD

**Issue by sharmarahul** [wireservice/csvkit#884]
I see that latest csvkit is v1.0.2 however when I install n ubuntu as per the docs I get an older version 0.9 which doesn't seem to support the new --skip-lines flag. Is the latest not published? If not is there any docs that tell how to install from git?

**Comment by jpmckinney** [comment]
Are you installing with `apt` or `aptitude`? You need to install with `pip`.

**Comment by hydrosquall** [comment]
@sharmarahul 

`pip install git+git://github.com/wireservice/csvkit.git@1.0.2`

**Comment by jpmckinney** [comment]
No answer to question, and solution with pip provided, so closing.
