### ISSUE TITLE
csvgrep always uses comma delimeter

### ISSUE THREAD

**Issue by jbelloncastro** [wireservice/csvkit#885]
`csvgrep` output result always makes use of the comma `,` delimeter, regardless of the delimeter specified in the command with `-d` option.
The delimeter is correctly interpreted for the input files.

Example:
`scolon_sep`: input file using semicolon separator
`output`: resulting output from csvgrep

    $ csvgrep -d\; -c 1 -m matchvalue scolon_sep > output

`output` file field separator will always be `,`

**Comment by jpmckinney** [comment]
`-d` sets the input delimiter. Pipe the output to `csvformat` if you want to change the delimiter.

`csvgrep -d\; -c 1 -m matchvalue scolon_sep | csvformat -D\; > output`
