### ISSUE TITLE
csvstack with varying headers/columns doesn't merge correctly

### ISSUE THREAD

**Issue by raveslave** [wireservice/csvkit#888]
When trying to stack multiple .csv files, if the header/column contents isn't 1:1 between the files being stacked, it seems that there are two issues

1) Only the first .csv's "header / column names" are actually included in the result.
_expected behaviour: if new column-names occur in some of the imported .csv's, these header names should be added and left empty for already imported rows._

2) If columns aren't in the same horizontal order, the result of data appended to the file will be incorrect, i.e. subsequent .csv's column-data will not match the column of the previous .csv's header position.
_expected behaviour: wouldn't it be nice if the stack would simply place matching columns (regardless of position in the csv's being imported) to existing header -> columns headers in already parsed .csv's
When trying to stack multiple .csv files, if the header/column contents isn't 1:1 between the files being stacked, it seems that there are two issues_

Thoughts?

**Comment by jpmckinney** [comment]
#245 discusses this issue. It still needs to be resolved. (Closing in favor of #245.)
