### ISSUE TITLE
csvlook: Data inference should be off by default

### ISSUE THREAD

**Issue by drchriscole** [wireservice/csvkit#890]
Getting excel mangled data is a common problem e.g. data parsed as a date. I really would prefer not to see the same thing with a powerful tool like csvlook. For example this field '9.3,9.3' was interpreted as '2001-09-03'.

As the name suggests I want to look at the data, I don't want it to be parsed or interpreted. Please can you consider making data inference opt-in rather than opt-out?
Thanks.

**Comment by jpmckinney** [comment]
The choice between opt-in or opt-out has been discussed in many issues, and the resolution has always been that switching to opt-in would cause far worse problems (and would be a major backwards-incompatible change affecting all prior users of csvkit), and therefore leaving as opt-out.

**Comment by drchriscole** [comment]
Except the change was already made between v0.9.1 and now. Previously there was no option to infer data and so for people moving to the new version can cause real problems. As it did for me with the above, I genuinely thought there was a problem with the input file. 

This feature goes against the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), but I get that the decision has been made and going back would cause more problems.

**Comment by jpmckinney** [comment]
The implementation of type inference changed from 0.9.1, so some values which previously weren't considered as dates are now interpreted as dates. I can't remember whether csvlook supported type inference in 0.9.1, but the intention was for all tools to support it consistently – so if it didn't support type inference, that was an inconsistency which would have been astonishing.

**Comment by ppKrauss** [comment]
The use of the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), as @drchriscole introduced, is contextual and microscale. See also [issues #935]( https://github.com/wireservice/csvkit/issues/935).

The argument "for all tools to support it consistently"  is global, is about the "ecosystem consistently": there are many "consistense states" for choice in the global scale. We can change it.

**Comment by jpmckinney** [comment]
Yes, we're all aware of the principle, but changing the default at this point would severely break all systems that assume the current behavior, and the upside of lowering astonishment is far, far smaller than the massive pain and frustration than changing the default will cause.

**Comment by ppKrauss** [comment]
Hi @jpmckinney, any changes will be a  *compatibility impact* for version 1.X.  The issue is only valid for an far future 2.0 version, and synchronously changing all tools... So also reviewing other interesting  situations.

My suggestion is to show "where the impacts?" in a *list of use cases*... Can I help to organize  it?

**Comment by jpmckinney** [comment]
I'm not sure there is the capacity for a 2.0 – but if that situation changes, we can consider this as part of that major upgrade.
