### ISSUE TITLE
csvsort removes "%'" signs from numeric columns

### ISSUE THREAD

**Issue by EdwardJRoss** [wireservice/csvkit#892]
Csvsort strips trailing "%" signs from numeric columns; I would expect these to be preserved. I suspect this is a side effect of the internal type conversion.

Command: `csvsort -v test.csv`

Input File: [test.txt](https://github.com/wireservice/csvkit/files/1364419/test.txt)
```
a
1%
```

Output:
```
a
1
```

csvkit version 1.0.2, Python 3.6.2

**Comment by jpmckinney** [comment]
Please use `--no-inference` to disable the type conversion.
