### ISSUE TITLE
presume I'm a journalist

### ISSUE THREAD

**Issue by kimballjohnson** [wireservice/csvkit#893]
Presume I'm a journalist, 
and I have a mac. 
So I open a terminal and I follow your instructions to 'sudo pip install csvkit'.
when it finishes, I type in 'csvkit'. 
The terminal responds that csvkit cannot be found.

What do I do?

Thanks,
Kimball Johnson

**Comment by esparta** [comment]
Read the [documentation](http://csvkit.readthedocs.io/en/1.0.2/)?

**Comment by jpmckinney** [comment]
Hi @kimballjohnson, csvkit contains multiple commands like csvsort, csvcut, etc. but no command named csvkit. The Tutorial in the documentation is particularly friendly to journalists as it was written by one, and will introduce you to all the commands.
