### ISSUE TITLE
in2csv fails, strange request UTF8

### ISSUE THREAD

**Issue by ppKrauss** [wireservice/csvkit#897]
both standards ODS and XLS have internal encode information... So the error not make sense,

```
in2csv RELATORIO_DTB_BRASIL_MUNICIPIO.ods -f csv
Your file is not "utf8" encoded. Please specify the correct encoding with the -e flag. Use the -v flag to see the complete error.

in2csv RELATORIO_DTB_BRASIL_MUNICIPIO.xls -f csv
Your file is not "utf8" encoded. Please specify the correct encoding with the -e flag. Use the -v flag to see the complete error.
```
The files are at ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/divisao_territorial/2015/dtb_2015.zip

**Comment by jpmckinney** [comment]
You're setting `-f csv`, which instructs in2csv to treat the ODS of XLS file as a CSV file. Just remove `-f csv`. There's no support for ODS yet (see #311).
