### ISSUE TITLE
Change --encoding error text if tool receives input from stdin

### ISSUE THREAD

**Issue by bmispelon** [wireservice/csvkit#898]
Hi,

When trying to process a latin1-encoded file (for example one that contains a single `é` character encoded with `latin1`), it only works by passing the filename to the command but not when piped:

```
$ csvcut -v -e latin1 latin1.csv 
é
$ cat latin1.csv | csvcut -v -e latin1
Traceback (most recent call last):
  File "/path/to/venv/bin/csvcut", line 11, in <module>
    load_entry_point('csvkit==1.0.2', 'console_scripts', 'csvcut')()
  File "/path/to/venv/lib/python3.6/site-packages/csvkit/utilities/csvcut.py", line 50, in launch_new_instance
    utility.run()
  File "/path/to/venv/lib/python3.6/site-packages/csvkit/cli.py", line 114, in run
    self.main()
  File "/path/to/venv/lib/python3.6/site-packages/csvkit/utilities/csvcut.py", line 36, in main
    rows, column_names, column_ids = self.get_rows_and_column_names_and_column_ids(**self.reader_kwargs)
  File "/path/to/venv/lib/python3.6/site-packages/csvkit/cli.py", line 332, in get_rows_and_column_names_and_column_ids
    column_names = next(rows)
  File "/path/to/venv/lib/python3.6/site-packages/agate/csv_py3.py", line 34, in __next__
    row = next(self.reader)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: unexpected end of data
```

This happens with version `1.0.2` of `csvcut` and python 3.6.2 (running on Linux, though I'm not sure that makes any difference).
With python 2.7.14 and the same version of `csvcut`, I get no errors.

**Comment by bmispelon** [comment]
After looking into this a little bit, it seems that this behavior is just how Python 3's `stdin` behaves: it treats its content as text (not bytes) in the encoding of the user's locale (which for me was `utf8`) (see https://docs.python.org/3/library/sys.html#sys.stdin).

It might be possible to fix this by manipulating `stdin.buffer` directly, but this seems brittle (it could break if `sys.stdin` is replaced with a `StringIO` like in the tests).

Another solution could be to give a warning (or an error) when using the `-e` option in a pipe, or at least document that these two usecases aren't compatible.

**Comment by jpmckinney** [comment]
Yeah, Python's not great in that respect. We document this solution here (can also occur on output piping): http://csvkit.readthedocs.io/en/1.0.2/tricks.html#python-standard-output-encoding-errors

Changing issue name to be about `-e` feedback.

**Comment by bmispelon** [comment]
Thanks, that's lovely! ✨
