### ISSUE TITLE
csvstack [Errno 24] Too many open files (reopen)

### ISSUE THREAD

**Issue by codingforfun** [wireservice/csvkit#899]
CSV stack isn't capable of stacking a large number of files because it exceeds the allowed number of open file descriptors. 
This has already been reported here: https://github.com/wireservice/csvkit/issues/475

The proposed solution of using `ulimit` to increase the number of open file descriptors is a _very poor mans_ solution for the following reasons. This should get fixed seriously. 
+ Users without privileges on most systems aren't allowed to change the limits.
+ The code actually already tries to close the files, but it doesn't seam to work properly. (See: https://github.com/wireservice/csvkit/issues/178 and [here](https://github.com/wireservice/csvkit/blob/1.0.2/csvkit/utilities/csvstack.py#L91).)
+ `csvstack` by design is a streaming utility and thus in theory should be capable of processing any arbitrary number of files. Limiting the number of files able to process just because there are too many open file descriptors is a pity somehow from the technical point of view. 

```
 [user@host]$ csvstack --filenames -n ts $(find datadir -name '*.csv')  -v
Traceback (most recent call last):
  File "/usr/bin/csvstack", line 11, in <module>
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/csvstack.py", line 96, in launch_new_instance
  File "/usr/lib/python2.7/site-packages/csvkit/cli.py", line 114, in run
  File "/usr/lib/python2.7/site-packages/csvkit/utilities/csvstack.py", line 35, in main
  File "/usr/lib/python2.7/site-packages/csvkit/cli.py", line 36, in __getattr__
IOError: [Errno 24] Too many open files: './85/20161123_130514.csv'
```
CentOS 7 Linux 3.10.0-514.26.2.el7.x86_64
CSVKit version 1.0.2

**Comment by jpmckinney** [comment]
I reopened #475 instead.
