### ISSUE TITLE
csvgrep does not return results if more than one column is specified

### ISSUE THREAD

**Issue by halloleo** [wireservice/csvkit#903]
Say you use a csv file `tips.csv` (test file from the `pandas` package) which starts like

    total_bill,tip,sex,smoker,day,time,size
    16.99,1.01,Female,No,Sun,Dinner,2
    10.34,1.66,Male,No,Sun,Dinner,3
    21.01,3.5,Male,No,Sun,Dinner,3
    23.68,3.31,Male,No,Sun,Dinner,2
    24.59,3.61,Female,No,Sun,Dinner,4
    25.29,4.71,Male,No,Sun,Dinner,4

With this if you issue on the command line

   $ csvgrep -c tip -m 3.31 tips.csv 

you get as expected 

    total_bill,tip,sex,smoker,day,time,size
    23.68,3.31,Male,No,Sun,Dinner,2

but if you search through more columns,e.g.:

   $ csvgrep -c tip,sex -m 3.31 tips.csv 

you get  no data row back:

    total_bill,tip,sex,smoker,day,time,size

This is wrong. csvgrep should return the same data row
`23.68,3.31,Male,No,Sun,Dinner,2`. The same happens when specifying
the columns by index (`-c 2` works, but e.g. `-c 1,2` does not).

Additionally it would be great to have an easy way to tell csvgrep to search all columns.

**Comment by jpmckinney** [comment]
#891 adds the functionality you described. By default, *all* listed columns must match the search string. That PR made it so that *any* listed column must match the search string.

**Comment by halloleo** [comment]
Confirmed. Works brilliantly. Thanks.

**Comment by earlyhumans** [comment]
What if you wanted to csvgrep without actually having to perform a csvsql query? That could look like:
csvgrep -c tip,sex -m 3.31,Male tips.csv  
(or some version using quotes)

Currently, this doesn't appear to work, but would be nice.

**Comment by jpmckinney** [comment]
@earlyhumans This is part of csvkit. See the docs for the `-a` (`--any-match`) option.

**Comment by jpmckinney** [comment]
If you're requesting a different feature than discussed in this issue, please open a new issue.

**Comment by davewhiiite** [comment]
Nevermind. By chaining multiple csvgreps together I can filter down (ex: csvgrep -c tip -m 3.31 tips.csv | csvgrep -c sex -m Male), and it takes less time than a csvsql query. Also, thanks for for showing me the very useful -a feature!
