### ISSUE TITLE
csvformat: fails with complex quoting

### ISSUE THREAD

**Issue by Mesibov** [wireservice/csvkit#908]
$ echo 'foo bar,"xxx zzz","mum, dad","address is ""The Croft"", Singleton"' | csvformat -T
    foo bar     xxx zzz     mum, dad    "address is ""The Croft"", Singleton"

Output expected:

    foo bar     xxx zzz     mum, dad    address is "The Croft", Singleton

**Comment by jpmckinney** [comment]
Python CSV will not write an unescaped quote character. It will always try to surround it in a quoted string, or use an escape character. Some CSV implementations may consider the extra quote characters optional, but the above output is not an error or a bug.

https://docs.python.org/3/library/csv.html

**Comment by jpmckinney** [comment]
But, you can avoid having quotechars entirely with:

```
echo 'foo bar,"xxx zzz","mum, dad","address is ""The Croft"", Singleton"' | csvformat -T -U 3 -Q ""
```

as in the example at the bottom of https://github.com/wireservice/csvkit/blob/master/docs/scripts/csvformat.rst#examples
