### ISSUE TITLE
in2csv: Error output from csv conversion from xlsx

### ISSUE THREAD

**Issue by a-hiroyuki** [wireservice/csvkit#909]
When converting a file of xlsx format into a CSV file, the following error occurred.
Although conversion itself can be done without problems, it will be possible that the error will not be resolved.
Please teach.

Command:
$ in2csv test.xlsx > test.csv

Output:
$ in2csv test.xlsx > test.csv
/usr/lib/python2.7/site-packages/agate/utils.py:275: UnnamedColumnWarning: Column 4 has no name. Using "e".
/usr/lib/python2.7/site-packages/agate/utils.py:275: UnnamedColumnWarning: Column 5 has no name. Using "f".
/usr/lib/python2.7/site-packages/agate/utils.py:275: UnnamedColumnWarning: Column 6 has no name. Using "g".
$ cat test.csv
test1,test2,test3,test4,e,f,g
,test5,test6,test7,test8,test9,
,,test10,test11,test12,test13,test14

Python version:
$ python --version
Python 2.7.5
$ python3 --version
Python 3.4.5
$ pip --version
pip 9.0.1 from /home/anzii/.local/lib/python3.4/site-packages (python 3.4)

OS version:
Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Comment by jpmckinney** [comment]
It's just warning you that there are unnamed columns, for which it is generating default column names. It's not an error.

**Comment by a-hiroyuki** [comment]
@jpmckinney Thank you. The problem was solved.
The top row must be matched with the last row of the bottom row
It's a specification that automatically adds characters.

**Comment by stevekm** [comment]
This results in malformed output, column headers are being added to empty cells.

**Comment by jpmckinney** [comment]
If you don't want it, run:

    in2csv --no-header-row examples/test.xlsx | tail -n +2
