### ISSUE TITLE
agate: csvlook erroring with unsupported operand error

### ISSUE THREAD

**Issue by zorab47** [wireservice/csvkit#916]
Executing csvlook on this file gives an unsupported operand error, however, other CSV tools can open file without error.

```sh
$ csvlook test.csv.log
unsupported operand type(s) for -: 'int' and 'str'

$ csvlook --version
csvlook 1.0.2
```

Attached is the CSV causing the problem (renamed to `.log` to allow the upload). What additional information can I provide?

[test.csv.log](https://github.com/wireservice/csvkit/files/1593792/test.csv.log)

**Comment by jpmckinney** [comment]
I'ved opened a PR to fix this in agate. It's caused by one cell in the CSV having "NaN".

https://github.com/wireservice/agate/pull/709
