### ISSUE TITLE
pip install on mac 10.11 fails to copy scripts to /usr/local/bin

### ISSUE THREAD

**Issue by resistor4u** [wireservice/csvkit#918]
all the suggestions in the docs on installing with mac (e.g., with pip, sudo pip, --ignore-installed...) failed to put scripts (e.g., in2csv) into my /usr/local/bin. however, if i install with `git clone` and build and install locally, the process acts as expected. it's an inconvenience to manually install the scripts to /usr/local/bin if a user goes through the documented route using `pip`, but there's no problem if building locally. i haven't tested the `brew install csvkit` alternative because the recipe requires python3 and i'm not eager to mess around with modifying it.

**Comment by jpmckinney** [comment]
Hmm, it's possible the scripts are getting installed somewhere not in your path. What's the output of:

    mdfind csvcut | grep 'csvcut$'

**Comment by resistor4u** [comment]
I uninstalled the pip version and installed via the `git clone` method; the output is `/usr/local/bin/csvcut`.

**Comment by jpmckinney** [comment]
Hmm, I'm not sure why pip wouldn't install the bin files.

**Comment by resistor4u** [comment]
i uninstalled pip, brew pip, and the the various config and env variables like PIP_TARGET, and i'll reinstall and see what happens when trying to pip install csvkit again.

**Comment by resistor4u** [comment]
installing with `pip install`, `sudo pip install`, and `sudo -H pip install` continued not installing to `/usr/local/bin`. i was able to fix this by putting ~/.pydistutils.cfg (per https://apple.stackexchange.com/a/223163) then running `sudo pip install`, but this probably isn't ideal. closing issue.
