### ISSUE TITLE
Sort file by header alphabetically

### ISSUE THREAD

**Issue by godspeedyou** [wireservice/csvkit#919]
Is csvkit supporting sorting the columns of a csv file? I can only find the option to sort the rows by a specific column, but no way to reorder the columns of a csv file.

E.g. I have:
```
a,h,u,j,m,k,l
1,3,5,7,9,0,12
```

and I want it to be:

```
a,h,j,k,l,m,u
1,3,7,0,12,9,5
```

At the moment I would use the following:
csvtool transpose myfile.csv | csvsort -c 0 | csvtool transpose
This is very time consuming, since csvsort has to rename all entries in the first column, when there are duplicates.

**Comment by jpmckinney** [comment]
You can get the comma-separated column indices of the sorted header names with:

csvcut -n file.csv | sort -k 2 | cut -c 2-3 | xargs | tr ' ' ','
You can then feed that output into:

csvcut -c out,put file.csv
