### ISSUE TITLE
Unable to quote fixed length conversion to quoted

### ISSUE THREAD

**Issue by digitalrinaldo** [wireservice/csvkit#920]
I have a fixed length csv file with no headers. I prvide a schema file.  I would like to have the output fields be wrapped with quotes.  Is there a way to do this?

in2csv -f fixed -q '"' -s schema.csv ../../data

The above is not expected to work since the docs say -q is for  the input.

**Comment by jpmckinney** [comment]
You can get the comma-separated column indices of the sorted header names with:

    csvcut -n file.csv | sort -k 2 | cut -c 2-3 | xargs | tr ' ' ','

You can then feed that output into:

   csvcut -c out,put file.csv

**Comment by jpmckinney** [comment]
Pipe the output to csvformat and use the -U and -Q options https://csvkit.readthedocs.io/en/1.0.2/scripts/csvformat.html
