### ISSUE TITLE
in2csv: "ImportWarning: can't resolve package from __spec__ or __package__"

### ISSUE THREAD

**Issue by vkostyuk** [wireservice/csvkit#923]
After installing `csvkit` using `pip` (under 4.14.9-2-MANJARO Linux with Python 3.6.4), and running in2csv, I got a bunch of warnings like these:

<pre><code>$ in2csv
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
... [about 20 of the same omitted]
/usr/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
usage: in2csv [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
              [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-L LOCALE]
              [-S] [--blanks] [--date-format DATE_FORMAT]
              [--datetime-format DATETIME_FORMAT] [-H] [-K SKIP_LINES] [-v]
              [-l] [--zero] [-V] [-f FILETYPE] [-s SCHEMA] [-k KEY] [-n]
              [--sheet SHEET] [--write-sheets WRITE_SHEETS] [-y SNIFF_LIMIT]
              [-I]
              [FILE]
</pre></code>

The script works (when provided a file), but generates these warnings every time.

Environment:
<pre><code>$ pip freeze
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.2
appdirs==1.4.3
awscli==1.14.26
Babel==2.5.3
Beaker==1.8.1
beautifulsoup4==4.6.0
bigml==4.14.0
bigmler==3.16.0
bleach==2.1.1
botocore==1.8.32
catfish==1.4.2
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.9
csvkit==1.0.2
cycler==0.10.0
dbfread==2.0.7
decorator==4.2.1
docopt==0.6.2
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
future==0.16.0
gufw==17.10.0
html5lib==1.0b10
idna==2.6
ipykernel==4.6.1
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==6.0.0
isodate==0.6.0
jdcal==1.3
jedi==0.11.1
Jinja2==2.10
jmespath==0.9.3
joblib==0.11
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.3.3
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.1.0
jupyter-latex-envs==1.4.0
jupyter-nbextensions-configurator==0.2.8
keyutils==0.5
leather==0.3.3
lightdm-gtk-greeter-settings==1.2.2
louis==3.4.0
lxml==4.1.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.1.0
menulibre==2.1.3
mistune==0.8.3
mugshot==0.3.2
nbconvert==5.3.1
nbformat==4.4.0
notebook==5.2.2
npyscreen==4.10.5
numpy==1.13.3
olefile==0.44
openpyxl==2.5.0
packaging==16.8
pacman-mirrors==4.7.0
pandas==0.21.0
pandocfilters==1.4.2
parsedatetime==2.4
parso==0.1.1
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
prettytable==0.7.2
prompt-toolkit==1.0.15
psutil==5.4.1
ptyprocess==0.5.2
pyasn1==0.4.2
pycairo==1.15.4
Pygments==2.2.0
pygobject==3.26.1
pyparsing==2.2.0
python-dateutil==2.6.1
python-distutils-extra==2.39
python-sane==2.8.3
python-slugify==1.2.4
pytimeparse==1.1.7
pytz==2017.3
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.3
reportlab==3.4.0
requests==2.18.4
requests-toolbelt==0.8.0
rsa==3.4.2
ruamel.yaml==0.15.35
s3transfer==0.1.12
scikit-learn==0.19.1
scipy==1.0.0
simplegeneric==0.8.1
six==1.11.0
skll==1.5
SQLAlchemy==1.2.2
team==1.0
terminado==0.8.1
testpath==0.3.1
tornado==4.5.2
traitlets==4.3.2
udiskie==1.7.3
Unidecode==1.0.22
urllib3==1.22
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==2.0.0
xlrd==1.1.0
</pre></code>

**Comment by jpmckinney** [comment]
I can't reproduce on 3.6.4 after installing with `pip install csvkit`.

**Comment by vkostyuk** [comment]
Hm. I reinstalled the package and dependencies with using `--ignore-installed`. Didn't help. Googling produces https://bugs.python.org/issue25791, but I'm not sure how this issue arises in csvkit. Any ideas?

**Comment by jpmckinney** [comment]
I think I need to see the traceback for the warning. If warnings are made into errors (exceptions), a traceback should be printed, e.g.

    python -W error path/to/in2csv

I use pyenv, so to find the path to `in2csv` I ran: `find ~/.pyenv -name in2csv`

**Comment by vkostyuk** [comment]
`python -W error /usr/bin/in2csv` produces exactly the same output as just `in2csv` (i.e., same warnings, no traceback). Interestingly, `python -W ignore /usr/bin/in2csv` produces the same output too!

**Comment by jpmckinney** [comment]
Hmm, try also adding `--verbose` after `in2csv` ?

**Comment by vkostyuk** [comment]
Tried, didn't help: exactly the same output.

**Comment by jpmckinney** [comment]
Hmm, you may need to clone the csvkit repository and add some code like in this [StackOverflow answer](https://stackoverflow.com/questions/22373927/get-traceback-of-warnings) to get the traceback.

**Comment by jpmckinney** [comment]
Oh, check the contents of `/usr/bin/in2csv`. If it doesn't look like the following, you may need to find the path to the `in2csv` file that is ultimately run:

```python
# EASY-INSTALL-ENTRY-SCRIPT: 'csvkit','console_scripts','in2csv'
__requires__ = 'csvkit'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('csvkit', 'console_scripts', 'in2csv')()
    )
```

**Comment by vkostyuk** [comment]
I tried running just the import statements from `in2csv.py` and got the same warnings. Then, I narrowed it down to two imports in particular:
<pre><code>import agateexcel  # noqa 
import openpyxl </pre></code>
Running in python console, I got the traceback:
<pre><code>$ python -W error
Python 3.6.4 (default, Dec 23 2017, 19:07:07) 
[GCC 7.2.1 20171128] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openpyxl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/openpyxl/__init__.py", line 26, in <module>
    from openpyxl.compat.numbers import NUMPY, PANDAS
  File "/usr/lib/python3.6/site-packages/openpyxl/compat/__init__.py", line 5, in <module>
    from .strings import (
  File "/usr/lib/python3.6/site-packages/openpyxl/compat/strings.py", line 10, in <module>
    from .numbers import NUMERIC_TYPES
  File "/usr/lib/python3.6/site-packages/openpyxl/compat/numbers.py", line 28, in <module>
    import pandas
  File "/usr/lib/python3.6/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/usr/lib/python3.6/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/tslib.pyx", line 1, in init pandas._libs.tslib
  File "pandas/_libs/tslibs/timedeltas.pyx", line 3, in init pandas._libs.tslibs.timedeltas
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__</pre></code>
Any ideas?

**Comment by jpmckinney** [comment]
Hmm, I see that openpyxl imports pandas if available, and the warnings seem to be caused by pandas, as mentioned in this issue: https://github.com/cython/cython/issues/1720

So, I don't think csvkit can do anything about it. You can create a virtual environment in which only csvkit is installed, without pandas, to avoid the warnings. Or wait for pandas/Cython to fix the warnings.

**Comment by vkostyuk** [comment]
Thanks for looking into it, @jpmckinney. I don't have Cython installed; maybe some of the relevant packages I have were compiled with Cython? (Most I've installed with pip, but a few of the major ones are from the Manjaro/Arch Linux repositories.) Any thoughts on this are appreciated: as you can imagine, these warnings make working with in2csv rather annoying.

**Comment by jpmckinney** [comment]
The traceback shows the warning coming from pandas, but csvkit doesn't require pandas (even indirectly). So, if you can set up a virtual environment without pandas, then you should have fewer warnings.

**Comment by maludwig** [comment]
I started getting this, and uninstalling lxml ended up solving the problem:

pip uninstall lxml

**Comment by Masterxilo** [comment]
I had the same issue and used `in2csv` as follows to fix it:

```
function in2csvNOWARN {
	python3 -W ignore /usr/local/bin/in2csv "$@"
}

in2csvNOWARN my-parameters-...
```

**Comment by chrstphrchvz** [comment]
> I started getting this, and uninstalling lxml ended up solving the problem:
> 
> pip uninstall lxml

agate is required by csvkit, and according to its [requirements-py2.txt](https://github.com/wireservice/agate/blob/master/requirements-py2.txt) and [requirements-py3.txt](https://github.com/wireservice/agate/blob/master/requirements-py3.txt), agate requires lxml. So isn't lxml needed?

**Comment by Masterxilo** [comment]
Probably as long your are not doing something with the xml functionality it
can be absent.

Am Di., 1. Jan. 2019, 08:34 hat Christopher Chavez <notifications@github.com>
geschrieben:
