### ISSUE TITLE
NULL byte in line

### ISSUE THREAD

**Issue by dracoIntelligentSystem** [wireservice/csvkit#927]
csvkit aborts it's execution  (in printing lines) when in a column appears a Null byte.
Also using -C option to exclude the column that contains the NULL byte does not work

**Comment by jpmckinney** [comment]
Can you provide a sample file to test with?

**Comment by dracoIntelligentSystem** [comment]
Dear James,
given the following command: csvcut -c 1 -e utf-16 10000tweets.csv
I get the following output (command line):
... (value)
... (value)
... (value)
... (value)
line contains NULL byte

and stop. guilty lines are n.: 3 and 7

Best regards,
Alessandro

**Comment by jpmckinney** [comment]
If you run with `-v` option you see the error is "_csv.Error: line contains NULL byte" which is from Python's csv reader, which agate uses (which csvkit uses). I think the appropriate solution is to first remove or escape the null bytes from the input, then use csvkit tools.

**Comment by calebeaires** [comment]
Hey @jpmckinney, thanks to the amazing tool!

When using csvclean, the solution I have found is to first `sed -i '' -e 's/\x00//g' file.csv`  but it will be useful if we could pass a parameter to the csvkit so this is done as the processes goes on.

**Comment by jpmckinney** [comment]
Hmm, the issue is that, for every input, CSV will need to read it entirely to remove NULL bytes, then let Python's csv reader read the new input. We can maybe stream input to Python's csv reader, but I'm not sure how much work that will be to refactor.

**Comment by mores** [comment]
Has there been any progress on fixing this issue ?
I am also trying to: csvsql -e latin1 -i mysql data.csv
result is: line contains NULL byte

**Comment by jpmckinney** [comment]
I think you can delete the NULL bytes in a pre-processing step with:

```bash
tr -d '\0' < file_with_null_bytes
```

**Comment by Michael-Gauthier** [comment]
The solution to remove NULL bytes that you proposed @jpmckinney did not work for me, but this did:

`tr < file-with-nulls -d '\000' > file-without-nulls`

After processing my files with that command I'm now able to use `csvcut` properly.
