### ISSUE TITLE
Concat two columns?

### ISSUE THREAD

**Issue by CharlesNepote** [wireservice/csvkit#930]
I would like to make one column from two columns. I didn't find anything in the documentation ("concat" nor "concatenate").

I tried without success:
``csvsql --query "select concat(DEP,COM) as DEPCOM;" this.csv > out.csv``

Probably I missed something...
I think it's a very basic usage which should be documented somewhere.

**Comment by CharlesNepote** [comment]
``csvsql --query "select (DEP||COM) as DEPCOM;" this.csv > out.csv`` is ok for strings but failed with strings like "02","001": it produces "21" instead of "02001"... I tried to use CAST but without success. I'm still lost...

Concatenation should be an easy job isn't it?

**Comment by CharlesNepote** [comment]
Found a safe way in perl, but quite long:
```perl
perl -MText::CSV::Encoded -lne '$c=Text::CSV::Encoded->new({encoding=>utf8}); $c->parse($_);@f=$c->fields();print (@f[0].@f[1].",".@f[2].",".@f[3])' file.csv```

Dreaming of a simple: `csvconcat -c 1,3 file.csv > out.csv`

**Comment by jpmckinney** [comment]
The values are being interpreted as numbers instead of strings. Add `--no-inference`, e.g.:

    echo '"02","001"' | csvsql --no-header-row --no-inference --query 'SELECT a||b FROM stdin'
