### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by curtmerrill** [wireservice/csvkit#932]
On the "[Arguments common to all tools](https://csvkit.readthedocs.io/en/1.0.2/common_arguments.html)" page, there appears to be an error for the `SKIP_LINES` option.

The documentation says `-L SKIP_LINES`, but the short flag is `-K`.

**Comment by jpmckinney** [comment]
This is fixed in the latest docs, though 1.0.3 isn't released yet https://csvkit.readthedocs.io/en/latest/common_arguments.html
