### ISSUE TITLE
Faster queries for PostgreSQL csvsql

### ISSUE THREAD

**Issue by ppKrauss** [wireservice/csvkit#933]
As say in the [`csvsql` documentation](http://csvkit.readthedocs.io/en/1.0.2/scripts/csvsql.html)

> ... use CSVSQL to “directly” query ... 
> Please note that this will create an in-memory SQL database, so **it won’t be very fast**

I have been speeding up this kind of procedure by use of [`FOREIGN TABLE`](https://www.postgresql.org/docs/current/static/sql-createforeigntable.html). It is **faster and more reliable** for big data. Example:

```sql
	CREATE EXTENSION IF NOT EXISTS file_fdw;
	DROP SERVER IF EXISTS csv_files CASCADE;
	CREATE SERVER csv_files FOREIGN DATA WRAPPER file_fdw;
        CREATE FOREIGN TABLE mytemp (col1 text, col2 text, col3 int) 
        SERVER csv_files OPTIONS (filename '/tmp/file.csv', format 'csv', header 'true');
```
So you can do a direct query (over CSV)  as `SELECT col3+1, col2 FROM mytemp` by PostgreSQL engine, it is faster tham do by COPY in a temporary table &mdash;  it is like a "direct `grep` by SQL".

-----

PS: some internal automation with *PLpgSQL* function may simplify the Python implementation, eg. 
```sql
EXECUTE format(
  'CREATE FOREIGN TABLE %s (%s) SERVER csv_files OPTIONS (filename %L, format %L, delimiter %L, header %L)',
  table_name, table_fields, file_name, file_format, file_delimiter, file_useHeader
);
```

**Comment by jpmckinney** [comment]
Thanks for the tip!

However, we try not to have too much database-specific code, as it will make maintenance a nightmare, so we can't integrate this into csvkit.
