### ISSUE TITLE
Date must be preserved as text

### ISSUE THREAD

**Issue by ppKrauss** [wireservice/csvkit#935]
I am using *csvsql 1.0.2* with something as
```sh
cat myDataset.csv  | \
csvsql --insert --tables t --db  postgresql://postgres:postgres@localhost:5432/sandbox   
```
where `myDataset.csv` have column `c1` with non-ISO dates, that  must be interpreted as strings,
```
c1,c2
03/02/2018 10:21:42,etc.
03/02/2018 18:03:52,etc.
05/02/2018 20:11:20,etc.
```
 but  `csvsql`  enforced  c01 to be interpreted as *timestamp without time zone*. A big mistake, generating future dates,
```
select c1 from quest1resps ;
    c1    
---------------------
 2018-03-02 10:21:42
 2018-03-02 18:03:52
 2018-05-02 20:11:20
 ```
It is not reliable. Any "magic" interpretation must be added only when an option is flagged: **default behaviour must be the most reliable**, not the "most magic".

**Comment by jpmckinney** [comment]
Use `--no-inference` to turn off interpretation. 

We won't change the default for [reasons expressed earlier](https://github.com/wireservice/csvkit/issues/890#issuecomment-332055598).

**Comment by nealmcb** [comment]
I'm getting `csvstat: error: unrecognized arguments: --no-inference` with version 1.0.2.  What version was this introduced in?

**Comment by jpmckinney** [comment]
csvstat doesn't implement --no-inference: https://csvkit.readthedocs.io/en/1.0.3/scripts/csvstat.html

**Comment by halloleo** [comment]
But wouln’t it make sense that `csvstat` honors `--no-inferences`? When you want to get an overview over a CSV inference can mess things up...

**Comment by jpmckinney** [comment]
Most of what `csvstat` does is based on the types that it guesses. What are you trying to do with csvstat, where leaving everything as strings is fine?

**Comment by nealmcb** [comment]
I have strings of the form "1-1-19" and "1-1-20". I want e.g. counts of those as unique strings. They are interpreted as dates which adds massive confusion.  I'd love to have both implicit inference for numbers, and no fancy guessing of "implicit dates" since the latter is so wide-ranging and convoluted in the international public mind.

**Comment by jpmckinney** [comment]
Thanks for clarifying! I created a new issue: #965
