### ISSUE TITLE
_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__

### ISSUE THREAD

**Issue by imtiazu** [wireservice/csvkit#937]
Hey guys,

Running in Windows 10.
All was working fine until I installed Pandas this week for some other stuff. Now when I just run in2csv from the windows command line I get a tonne of the below messages. Any idea? Thanks

(I know I haven't supplied an input or output file, but simply executing in2csv generates all the messages when it never used to)

C:\Users\USERNAME>in2csv
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
c:\users\USERNAME\appdata\local\programs\python\python36-32\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
usage: in2csv [-h] [-d DELIMITER] [-t] [-q QUOTECHAR] [-u {0,1,2,3}] [-b]
              [-p ESCAPECHAR] [-z FIELD_SIZE_LIMIT] [-e ENCODING] [-L LOCALE]
              [-S] [--blanks] [--date-format DATE_FORMAT]
              [--datetime-format DATETIME_FORMAT] [-H] [-K SKIP_LINES] [-v]
              [-l] [--zero] [-V] [-f FILETYPE] [-s SCHEMA] [-k KEY] [-n]
              [--sheet SHEET] [--write-sheets WRITE_SHEETS] [-y SNIFF_LIMIT]
              [-I]
              [FILE]
in2csv: error: You must specify a format when providing data via STDIN (pipe).

**Comment by jpmckinney** [comment]
See https://github.com/wireservice/csvkit/issues/923#issuecomment-361131607

I recommend creating a virtual environment for csvkit, and without pandas.

Otherwise, pandas will cause those warnings.

**Comment by zaherhf** [comment]
I receive this error after uninstalling pandas and cython. Any ideas?
