### ISSUE TITLE
csvformat: --out-quoting 2 requires type inference

### ISSUE THREAD

**Issue by CharlesNepote** [wireservice/csvkit#938]
``echo "A,B,1,2018" | csvformat -U 2``
is giving:
``"A","B","1","2018"``

-U 2 stands for "2 = Quote Non-numeric". Does it mean that it should produce:
``"A","B",1,2018``

```bash
$ csvformat -V
csvformat 1.0.2
```

**Comment by jpmckinney** [comment]
#1089 was quite a complex solution. #1068 was simpler, but changed csvformat from a streaming to a buffering tool.

If people actually use `csvformat -U2`, then we can try to simplify #1089.

**Comment by furgo16** [comment]
@jpmckinney for what is worth, this is the main functionality I installed csvkit in the first place for. I was a bit confused that it did not work, until I found this issue. I assumed the use case was common, but perhaps it's simply my perception:

1. Export a CSV file with mixed text and number columns from Google sheets => the export does not add any quotes at all
2. Try to add quotes to the text columns with `csvformat -U2` => Fail. It adds quotes to all columns

`csvstat`'s type inference did work and reports the columns with the right text or number format.

**Comment by jpmckinney** [comment]
Why do you need to use `-U2`? Are you working with tools that can't do type inference well?

**Comment by furgo16** [comment]
I was copying part of the data in the CSV file to paste it into a variable in a Python script, which required quotes around the text columns.

**Comment by jpmckinney** [comment]
I've now implemented this in line with #1068. but such that it only reads all data into memory when `-U2` is used. 95dc26dde97ddb2b28947f8b8353d8eace675a71
