### ISSUE TITLE
csvsql strftime %y failed

### ISSUE THREAD

**Issue by pinsardfr** [wireservice/csvkit#940]
Hi,
I suspect an issue on "%y" in strftime format parameter.

Here is a minimal example using csvkit 1.0.2 with Python 3.6.4 :: Anaconda custom (64-bit)

$ cat a.csv
datec
 Wed Mar  7 10:09:17 CET 2018

This following command output is the one expected :
 $ csvsql --query "select strftime('%Y%m%d',datec) from a" a.csv
"strftime('%Y%m%d',datec)"
20180307

while this one contains no value : 
$ csvsql --query "select strftime('%y%m%d',datec) from a" a.csv
"strftime('%y%m%d',datec)"

**Comment by jpmckinney** [comment]
`%y` isn't part of SQLite: https://sqlite.org/lang_datefunc.html
