### ISSUE TITLE
csvlook: Change truncation character for floats

### ISSUE THREAD

**Issue by csghone** [wireservice/csvkit#941]
`max-column-width` does not work on columns interpreted as `float`.

eg:
```
echo "2.132456,156548.54646 2.132456,156548.54646" | xargs -n1 |csvlook --max-column-width 10
| 2.132456 | 156548.... |
| -------- | ---------- |
|   2.132… | 156,548... |
```

Expected behavior (or Workaround):
```
echo "2.132456,156548.54646 2.132456,156548.54646" | xargs -n1 |csvlook -I --max-column-width 100
| 2.132456 | 156548.54646 |
| -------- | ------------ |
| 2.132456 | 156548.54646 |
```

**Comment by jpmckinney** [comment]
Are you saying that the suggested behavior is to ignore `--max-column-width` for float columns?

**Comment by csghone** [comment]
Sorry. My mistake.
Actually wanted to avoid the ellipsis character generated due to truncation - is there a way to specify a custom truncation character character? I think agate has one, but csvkit doesn't.

Do you prefer to close this ticket and create a new one?

**Comment by jpmckinney** [comment]
I renamed the issue. We can implement this by exposing the `max_precision` parameter of agate's `print_table` as a command-line argument.
