### ISSUE TITLE
"fill down" tool

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#943]
Hi all,
often with CSV files it's necessary to o a fill down process. Do you know some tool to do it??

Thank you

P.S. it's also a sort of gentle csvkit feature request

**Comment by jpmckinney** [comment]
Does fill down mean: "Read a CSV from top to bottom, and if a cell is empty, copy the cell above"?

**Comment by aborruso** [comment]
Hi @jpmckinney , yes.

Thank you very much.

**Comment by jpmckinney** [comment]
This feature doesn't fit naturally in any of the existing tools, and new tools are not being added. So, closing.
