### ISSUE TITLE
csvsql mysql dependency not Python 3 compat

### ISSUE THREAD

**Issue by RogerWebb** [wireservice/csvkit#950]
When executing a csvsql command against a mysql database, a screen is displayed indicating that a mysql backend must be installed.  Running the suggested command "pip install MySQL-python" fails with the following error:

ModuleNotFoundError: No module named 'ConfigParser'

It appears the suggested dependency is not Python 3 compatible.  Is there a work-around that is?  Regardless, the suggested dependency cannot be installed.

**Comment by RogerWebb** [comment]
I'm able to work with agate-sql by using the "pymysql.install_as_MySQLdb()" call prior to doing db work in the script.  If there were a check for the presence of pymysql when MySQLdb isn't found, with this tossed in there, it could be an easy fix.

**Comment by jpmckinney** [comment]
I think install mysql-connector-python instead.
