### ISSUE TITLE
csvstat --names ignores the --skip-lines option

### ISSUE THREAD

**Issue by ericla413** [wireservice/csvkit#951]
csvstat --names ignores the --skip-lines option. It always returns the names from the first row. The regular csvstat features do respect --skip-lines.

For example:

> $ cat a.csv
> a,b,c
> d,e,f,g
> 1,2,3,4
> $ csvstat --names a.csv
>   1: a
>   2: b
>   3: c
> $ csvstat --skip-lines 1 --names a.csv
>   1: a
>   2: b
>   3: c

(Thanks for the great set of csv tools.)

**Comment by jpmckinney** [comment]
Fixed in HEAD, thanks for reporting!
