### ISSUE TITLE
UPDATE query: is it possible to do it with csvsql

### ISSUE THREAD

**Issue by aborruso** [wireservice/csvkit#952]
Hi,
is it possible to run something like

    csvsql --query "UPDATE table SET field='aaaa' WHERE search_condition"

Thank you

**Comment by jpmckinney** [comment]
Yes, but you need to provide either `--db` or a file, as otherwise csvsql has no idea what file or database to query.

**Comment by aborruso** [comment]
Hi @jpmckinney , I have tried

    csvsql  --query "UPDATE input SET periodo='aa' WHERE anno='2018'" input.csv

and I have had `'NoneType' object has no attribute 'keys'`.

This is my file

```
anno,periodo
2018,a
2018,a
```

Thank you

**Comment by jpmckinney** [comment]
Can you provide the input.csv (or a sample)?

**Comment by jpmckinney** [comment]
See the steps here https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug to report an issue.

**Comment by jpmckinney** [comment]
Ah, sorry, I read too quickly.

**Comment by jpmckinney** [comment]
Fixed in HEAD - this was a bug!

**Comment by johnathanz** [comment]
Hi @jpmckinney. I'm trying to update rows in the attached csv that when dwl = 'np', I update the value to 0.
[input.csv](https://github.com/wireservice/csvkit/files/13402365/input.csv)

I used: `csvsql --query "update input set dwl = '0' where dwl = 'np'" input.csv`

No error from the terminal, but nothing is changed in the file either.

Any idea what I'm doing wrong?

Thanks!
