### ISSUE TITLE
in2csv: [Errno 22] Invalid argument on large JSON file

### ISSUE THREAD

**Issue by alewkinr** [wireservice/csvkit#959]
Hi there!
I've tried to use this awesome tool today, but got an error with no explanation why that had happen, so I'm here.

I got it while was trying to convert *.json to *.csv. Average weight of the file is 3,5GB.
My command line looks like that: 
`sudo in2csv mln_profiles.json > data.csv`

macOS HighSierra
csvkit v. latest

Thanks in advance!

**Comment by addahlbe** [comment]
Ever figure this one out, running into the same issue. Appears to be due to the size of my CSV. May just write a script to convert the large csv into a bunch of smaller ones, run the query, then join them.

**Comment by jpmckinney** [comment]
Can you provide more detail as described in https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug ? Thanks!

**Comment by jpmckinney** [comment]
Closing in favor of #957
