### ISSUE TITLE
csvsort does not honor quoting requests

### ISSUE THREAD

**Issue by fgregg** [wireservice/csvkit#961]
## Minimal quoting, option 0
```bash
> echo -e "a,b\n4,2\n1,4" | csvsort -u 0
a,b
1,4
4,2
```

## All quoting, option 1
```bash
> echo -e "a,b\n4,2\n1,4" | csvsort -u 1
a,b
1,4
4,2
```
expected:

```bash
"a","b"
"1","4"
"4","2"
```

## Quote non-numeric, option 2
```bash
> echo -e "a,b\n4,2\nfoo,bar" | csvsort -u 2
could not convert string to float: 'a'
```

expected
```bash
"a","b"
4,2
"foo","bar"
```

## Quote None, option 3
```bash
echo -e "a,b\n4,2\n\"foo\",\"bar\"" | csvsort -u 3
a,b
"""foo""","""bar"""
4,2
```

expected
```bash
a,b
4,2
foo,bar
```

Options 1, 2, 3 do not seem to be working.

**Comment by jpmckinney** [comment]
I think you're confusing input format and output format? -u is for input. `-U` (only available on csvformat) is for output.

**Comment by jpmckinney** [comment]
e.g. `echo -e "a,b\n4,2\n1,4" | csvsort | csvformat -U 1`

**Comment by fgregg** [comment]
I see, thanks.
