### ISSUE TITLE
Remove empty columns

### ISSUE THREAD

**Issue by ybiyani** [wireservice/csvkit#962]
How do I remove an empty column from the csv file?

**Comment by jpmckinney** [comment]
If you know which column is empty, use [`csvcut`](https://csvkit.readthedocs.io/en/1.0.3/scripts/csvcut.html)/

**Comment by Accio** [comment]
What about if I do not know ahead which column is empty? Thanks

**Comment by jpmckinney** [comment]
@Accio There is no command for that. You can determine which columns are empty with csvstat.

**Comment by Accio** [comment]
@jpmckinney Thanks. Your information helps.

**Comment by jpmckinney** [comment]
FYI csvclean will report empty columns in version 2. Done as part of #426
