### ISSUE TITLE
in2csv: Newline characters inside cells in other formats are preserved unescaped as new lines

### ISSUE THREAD

**Issue by NathanLawrence** [wireservice/csvkit#963]
This is perhaps an unusual edge case, but I've run into it today: When you're making a CSV from another format with in2csv, if a cell has a new line in it, this will be reproduced in the final CSV, with no flags or options in the CLI to escape them. 

For many CSV interpreters, this is no problem, but others, including some fairly prominent ones for R and Python, will choke on this. 

Is this something that might be worth fixing?

**Comment by NathanLawrence** [comment]
I assumed both R and Python would, yet something very odd seems to be happening, and neither seems to be doing so. I'm starting to wonder if they're some very specific kind of return that isn't being caught or handled by either language's libraries. I'll do some testing and check back.

**Comment by jpmckinney** [comment]
@NathanLawrence Closing due to no news, but I can re-open if you update the issue.

**Comment by artkpv** [comment]
Thanks for effort to build csvkit. 

Would be great to have those new line chars escaped if they appear in fields. Here is a use case I have.

1. Use this file 
[sample.zip](https://github.com/wireservice/csvkit/files/5061899/sample.zip)
2. Run `in2csv sample.xls > result.csv`
3. Run python csv reader: 
```import csv
with open('result.csv') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
    for row in spamreader:
        print(', '.join(row))
```
Result:
```
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o
, , , , , , , , , , , , , , 
Дата, Номер, , Время, ЦБ, Срок (дней), Ставка, %, Расход (шт.)
(сумма займа), Сумма %, 
руб., Приход (шт.)
(сумма займа), Сумма %, 
руб., Место сделки, Дата соверш., Поставка (план), Поставка (факт)
```

PS. Python csv reader has '\n' hardcoded. https://docs.python.org/3/library/csv.html#csv.Dialect.lineterminator

**Comment by jpmckinney** [comment]
What is the difference in the result that you are expecting?

**Comment by artkpv** [comment]
Expect it to be one line:
```
Дата,Номер,,Время,ЦБ,Срок (дней),"Ставка, %","Расход (шт.) \n (сумма займа)","Сумма %, \n руб.","Приход (шт.) \n (сумма займа)","Сумма %, \n руб.",Место сделки,Дата соверш.,Поставка (план),Поставка (факт)
```

**Comment by jpmckinney** [comment]
Hmm, but then you are changing the data. You are changing each literal newline character into a backslash character and an `n` character. CSVKit tries not to change the data. If you need that, maybe use a tool like `sed` or `awk`.

**Comment by artkpv** [comment]
Yes, that changes the data. Still the issue remains. `sed` or similar needs to differentiate from row newline and cell newline then. So it will need to parse csv somehow. Or parse xls file. Not so easy. Also, I thought about using some other newline char. NULL char (0x0)?

**Comment by jpmckinney** [comment]
Ah, yes, of course. Why do you need to escape the newline characters within cells? Most CSV readers will read that data correctly, since the newline characters are inside a quoted value.
