### ISSUE TITLE
UnnamedColumnWarning in2csv

### ISSUE THREAD

**Issue by giovanma** [wireservice/csvkit#967]
I would like to know if it was possible to add an option to in2csv so that if my input xls file has the first row empty, the csv created by in2csv DOESN'T automatically create a header row with a,b,c,d,... labels.

**Comment by jpmckinney** [comment]
What if you skip the row with `--skip-lines 1`?

**Comment by giovanma** [comment]
Unfortunately that does not work for 2 reasons:
1) I am invoking in2csv within a code which may create xls files (used as input by in2csv) with the first row which could be empty or not empty, so in case the first row was not empty I would lose some info 
2) even if I structured the code to always generate xls files with the first row empty, in2csv with --skip-lines 1 appends headers in the first row starting from the first empty column: e.g. suppose row 1 was empty and row 2 was 1 2 3, the csv file generated would have in row 1 the following: 1,2,3,d,e,f,...

if there is another way to solve this issue It'd be great,

thanks

**Comment by jpmckinney** [comment]
I think the solution to your two problems is to use `--no-header-row` and pipe to `tail +2` like:

    echo "4,5,6" | in2csv -f csv --no-header-row | tail +2
