### ISSUE TITLE
NA gets converted to empty string

### ISSUE THREAD

**Issue by terek** [wireservice/csvkit#968]
$ cat test.csv
```
Continent,Country
NA,USA
EU,GB
```

$ in2csv -f csv test.csv 
```
Continent,Country
,USA
EU,GB
```

NA should not be interpreted as "not available".

**Comment by jpmckinney** [comment]
Use `--no-inference`. https://csvkit.readthedocs.io/en/1.0.3/tricks.html#csv-data-interpretation
