### ISSUE TITLE
csvstat/csv2sql doesn't like 'yesterday' on the 2nd line of any csv file

### ISSUE THREAD

**Issue by uqrtj** [wireservice/csvkit#970]
$ cat bug_example.csv 
"Id","Description"
"1","csv2sql doesn't like 'yesterday' on the 2nd line"
$ csvstat bug_example.csv 
date value out of range
$

**Comment by jrc** [comment]
same here. 

```
$ cat > cat foo.csv
body_text
The startup launched its product last month
^D
$ csvstat foo.csv 
year is out of range
$ csvstat --version
csvstat 1.0.3

```

**Comment by jpmckinney** [comment]
I opened an issue to fix this upstream: https://github.com/wireservice/agate/pull/720
