### ISSUE TITLE
Could not find a version that satisfies the requirement openpyxl==2.2.0-b1 (from csvkit==0.9.1)

### ISSUE THREAD

**Issue by rongshen** [wireservice/csvkit#972]
Hello,

Starting from this morning 7/31/2018, suddenly our pip installation script failed on the following error:

`10:50:50 Collecting openpyxl==2.2.0-b1 (from csvkit==0.9.1)
10:50:50   Could not find a version that satisfies the requirement openpyxl==2.2.0-b1 (from csvkit==0.9.1) (from versions: 1.1.0, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.2.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.6.1, 1.6.2, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.4, 2.4.5, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4)
10:50:50 No matching distribution found for openpyxl==2.2.0-b1 (from csvkit==0.9.1)`

Does anyone if there is anything has changed on csvkit side?

Thank you!

**Comment by cmcarthur** [comment]
I'm seeing the same issue maintaining older versions of software that depend on csvkit 0.9.1. As far as I can tell, openpyxl 2.2.0-b1 was removed from pypi.

**Comment by rongshen** [comment]
@cmcarthur Thank you!
Do you happen to know any work around of this without having to upgrade the version?

**Comment by RealSalmon** [comment]
We started seeing this today as well with older software that requires csvkit 0.9.1. Thanks for any help and for csvkit!

**Comment by Themanwithoutaplan** [comment]
All old betas and alphas of openpyxl were removed from PyPI and should **never** have been used as dependencies.

**Comment by rdmurphy** [comment]
Can confirm we're hitting this now too. Have an older package that really shouldn't bump all the way to `csvkit` v1, so we're in a tight spot.

**Comment by rdmurphy** [comment]
I don't recommend anyone to [use this fork](https://github.com/texastribune/csvkit/tree/0.9.2), but I was able to hotfix it by switching csvkit to require `openpyxl==2.2.0` instead, just to get an update to our project out the door. May be worth releasing an update to the `0.9.x` branch to make this change live?

**Comment by cmcarthur** [comment]
I've opened a fix PR here: https://github.com/wireservice/csvkit/pull/973

**Comment by jpmckinney** [comment]
I created a 0.9 branch. I can make a 0.9.2 release, but if anyone can test the branch first, that'd be great :)

**Comment by jpmckinney** [comment]
FWIW, 2.2.0 was not released at the time of 0.9.1's release, and 2.2.0-b1 was the only available release to address an encoding issue #391. Also, the same openpyxl maintainer who is now saying that b1 shouldn't have been a dependency recommended pinning to it in https://bitbucket.org/openpyxl/openpyxl/issues/433/load_workbook-excelpy-does-not-accept 🤷‍♂️

**Comment by isralopez** [comment]
Hi Guys, I'm having same issue, I see you're working on it, but for now, It's safe to make an install from 0.9 branch to have it running??

**Comment by jpmckinney** [comment]
0.9.2 is now available, with a corrected version of openpyxl https://pypi.org/project/csvkit/0.9.2/
