### ISSUE TITLE
Consider csvkit configuration file to set default arguments 

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/csvkit#974]
e.g. many people want `--no-inference` to be the default. The configuration file would be used to set this as the default. We can add an `--inference` flag to override the configuration file.

**Comment by jpmckinney** [comment]
Another example is changing the default sniff limit #986

**Comment by dannysepler** [comment]
i opened this pull request https://github.com/wireservice/csvkit/pull/1140, and in reviewing past pull requests found this issue and #986! i'm definitely vested in this, as someone who uses csvkit on large CSVs and wants to help speed it up!

**Comment by jpmckinney** [comment]
Closing as I opened the issue and it has not generated much interest.
