### ISSUE TITLE
csvlook complains of encoding issues where in2csv does not

### ISSUE THREAD

**Issue by gheeshuggah** [wireservice/csvkit#981]
Running csvkit 1.0.3
I have PYTHONENCODING=utf8 in the environmental variable list
I also have run it with `PYTHONIOENCODING=utf8 csvlook file.xlsx`
either way when I run the command I get:

```
Your file is not "utf-8" encoded. Please specify the correct encoding with the -e flag or with the PYTHONIOENCODING environment vari
able. Use the -v flag to see the complete error.
```

This is not the case for `in2csv` (which used to throw that error at me).

`in2csv PaynesPrairieParking.xlsx > PaynesPrairieParking.csv`

I've attached the .xlsx for testing:
[PaynesPrairieParking.xlsx](https://github.com/wireservice/csvkit/files/2283418/PaynesPrairieParking.xlsx)

**Comment by HMoen** [comment]
Adding the **PYTHONENCODING** variable with value **utf8** in the environmental variable list worked for me. Make sure to reload your variables or close the terminal window and re-open. Thanks for the tip!

**Comment by gheeshuggah** [comment]
I cannot reproduce this issue anymore. Must have been an issue with my system. Closing
