### ISSUE TITLE
How to suppress ImportWarning: can't resolve package from __spec__  or __package__, falling back on __name__ and __path__

### ISSUE THREAD

**Issue by luzpaz** [wireservice/csvkit#982]
Python 3.7.0
in2csv 1.0.3

Each time I run `in2csv`i get the following output warning: 
```
ImportWarning: can't resolve package from __spec__
 or __package__, falling back on __name__ and __path__
```

Is there a way I can suppress this ?

**Comment by jpmckinney** [comment]
I can't reproduce, e.g.:

    echo "a,b" | in2csv -f csv

**Comment by luzpaz** [comment]
@jpmckinney what version of py3 are you using ?

**Comment by luzpaz** [comment]
> echo "a,b" | in2csv -f csv

I see it after running the above.

**Comment by jpmckinney** [comment]
When searching the web, it seems some projects encountered this issue because of their use of importlib, but csvkit and agate don't use importlib, so it must be an issue with dependencies. Please try `pip install --upgrade --force-reinstall csvkit`

**Comment by jpmckinney** [comment]
Do you mean this comment? https://github.com/wireservice/csvkit/issues/788#issuecomment-355393329

**Comment by dannguyen** [comment]
That's the one, thank you!

**Comment by jpmckinney** [comment]
FYI this is now fixed in the leather dependency. You can `pip install --upgrade leather`
