### ISSUE TITLE
Improve dialect sniffing

### ISSUE THREAD

**Issue by akkartik** [wireservice/csvkit#986]
Back in June 2017, @petersonjr pointed out some test cases that cause csvkit/agate to misinterpret the dialect of files: https://github.com/wireservice/csvkit/issues/751#issuecomment-310803282

The reasonable workaround @jpmckinney pointed out was to configure `--snifflimit 0` at the commandline. While this helps, I'd like to point out a couple of things:

a) Those test cases work fine without the override to the `Sniffer` class introduced in https://github.com/wireservice/agate/commit/3b9ceea131ba143cc72b6d1a9f7871d059188b52

b) I dug into [the default Sniffer in the Python standard library](https://github.com/python/cpython/blob/3.7/Lib/csv.py#L218). It's not very robust; it uses regular expressions for parsing each line, which means that it gets confused by say commas inside quoted strings.

c) While agate has a reasonable default `sniff_limit` of 0, the commandline argument parsing in csvkit overrides it to `None`, which has the effect of reading the entire file. As the size of the input file grows, it becomes increasingly likely that it'll encounter stuff that the Python Sniffer can't handle.

These observations indicate a few places in the stack where a change may be beneficial. I'm not sure if any of them is a good idea -- I may well be missing context as an outsider -- but thought I'd try to start a discussion. Is there a testsuite for the custom Sniffer in agate? Is it an option to default `--snifflimit` to something smaller, say 1024? (Obviously changing the Python standard library is a bigger task. [The maintainer for the csv module is also not active anymore.](https://devguide.python.org/experts))

**Comment by jpmckinney** [comment]
There are some sniffing tests in agate:

https://github.com/wireservice/agate/blob/master/tests/test_py2.py
https://github.com/wireservice/agate/blob/master/tests/test_py3.py

csvkit sets the sniff limit to `None` to maintain the same behavior as earlier versions.

It would be reasonable to allow users to change this default, which is the subject of #974.

What other changes were you considering?

**Comment by akkartik** [comment]
Perhaps I'm being ideological, but my worldview is to optimize for the very first experience of a newcomer who may not know much about Python package boundaries, but who does have a non-trivial dataset they'd like to browse. In this scenario they won't have a configuration file yet either.

Sniffing is a heuristic introduced to reduce work in some situations. Freezing the default heuristic for all time in the name of backwards compatibility seems restrictive.

Fundamentally, sniffing exists to save people the trouble of telling you the delimiters. But if you guess wrong, they now have to tell you the delimiters *and* you've now given them a misleading error message to wade through[1] before they realize they have to do that. And as I hope my previous comment persuaded you, the Python standard library's heuristics are not great at the moment.

If any of this is persuasive I can contribute patches. If it isn't I'll show myself out, no hard feelings :) I appreciate all the work that has gone into this project, and I'll continue using it (albeit intermediated through a private fork).

[1] The one that brought me here was the `Row 0 has 11 values, but Table only has 3 columns` mentioned in the earlier issue I linked to. Except my table is perfectly well-formed, no ragged rows.

**Comment by jpmckinney** [comment]
Sure, we can start a 2.0 branch if you contribute a patch.

**Comment by GjjvdBurg** [comment]
Hi all, I realize this is an old issue but I thought you might be interested in our [CleverCSV](https://github.com/alan-turing-institute/CleverCSV) package. It provides a drop-in replacement for the Python csv module but offers improved dialect detection.

**Comment by jpmckinney** [comment]
@GjjvdBurg Thanks for sharing!

**Comment by jpmckinney** [comment]
I consider this closed by #1140
