### ISSUE TITLE
csvcut: Special case if only -C is provided for CSVs with ragged rows

### ISSUE THREAD

**Issue by michaelmior** [wireservice/csvkit#992]
input.csv
```
foo,bar
foo,bar,baz
foo
```
```
$ csvcut -H -C 1 input.csv
bar
bar
""
```

I expected the second line to be `bar,baz` since all I asked for was to remove the first column. Similarly, I expected the third line to be empty since there was only one column in the input file which was removed. I can see why in many cases the output above may be desired, but that seems like more of a job for csvclean.

**Comment by jpmckinney** [comment]
The third line is an empty cell (`""` is interpreted as empty by CSV parsers). If you don't want empty rows, use `--delete-empty-rows`. I did notice a bug in using `--delete-empty-rows` on short rows, which I've fixed for the next release.

As for `bar,baz`: csvkit's tools are designed to operate on more-or-less "good" data, and it includes tools for fixing bad data like csvclean. csvcut needs the first row to have as many columns as the rest of the data (explained below). I added a note to the docs about this. In short: use `csvclean` first.

Changing csvcut to support long rows would require some significant changes. csvcut supports setting both a whitelist (`-c`) and a blacklist (`-C`) at the same time, e.g. `-c 10-20 -C 15` to get the 10th to 20th columns but exclude the 15th. Its implementation essentially builds a new whitelist from the given `-c` and `-C` columns. To have the behavior you describe, csvcut would have to make a special case if only `-C` is provided.

**Comment by michaelmior** [comment]
That's fair. I wasn't really working with a CSV file, but a file with a bunch of comma separated lines some of which were quoted and I wanted a way to easily handle the quotes. Sounds like this is outside the scope of csvkit.

**Comment by jpmckinney** [comment]
If you're not working with CSV, you might just want to use `cut`, e.g.:

```
echo "foo,bar
bzz,zzz,yyy" | cut -d , -f 2-3
```

You can't use a blacklist like `-C`, but you can instead whitelist all the other fields.

**Comment by michaelmior** [comment]
As I mentioned, I'm dealing with some fields which are quoted which was the whole reason for wanting to use `csvcut`.

**Comment by jpmckinney** [comment]
Closing as the input data for this feature request was not a CSV, per https://github.com/wireservice/csvkit/issues/992#issuecomment-436857524
