### ISSUE TITLE
csv2excel?

### ISSUE THREAD

**Issue by AlJohri** [wireservice/csvkit#994]
I was wondering if the opposite of in2csv was available. I want to convert a CSV to an excel spreadsheet. thanks!

**Comment by AlJohri** [comment]
might be part of the `csvformat` command?

**Comment by jpmckinney** [comment]
Sorry, we only support CSV and JSON as output formats. However, there are other tools like https://gitlab.com/DerLinkshaender/csv2xlsx for CSV-to-Excel.
