### ISSUE TITLE
Convert csv to xml

### ISSUE THREAD

**Issue by ruv** [wireservice/csvkit#995]
What about a tool to convert a generic CSV to XML? As an addition to [JSON output](https://csvkit.readthedocs.io/en/1.0.3/tutorial/4_going_elsewhere.html#csvjson-going-online).

An XML output example:
```xml
<resultset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <row>
    <col1>value-a</col1>
    <col2>value-b</col2>
  </row>
  <row>
    <col1 xsi:nil="true"/>
    <col2>value-d</col2>
  </row>
</resultset>
```
The root element name and the element name for the rows might be specified in the command line (by default `resultset` and `row` can be used). The column names are used to output the elements contained value. Hence, these column names should be either conformed to [NCName](https://stackoverflow.com/questions/1631396/what-is-an-xsncname-type-and-when-should-it-be-used) (and error should be produces otherwise) or auto-converted to NCName-safe form.

**Comment by ruv** [comment]
Just if somebody looks for some solution — an XQuery processor can be used to convert JSON into XML.
For example, using Saxon (`saxonhe-xquery` command line tool), the following shell function (or a corresponding shell script) can be defined:

```shell
function csvjson2xml_file () {
  local decl='declare namespace map="http://www.w3.org/2005/xpath-functions/map";'
  local input="json-doc('$1')"
  local query=' ! element resultset { for $m in ?* return element row { map:keys($m) ! element { . } { $m ?(.) } } }'
  saxonhe-xquery -qs:"$decl $input $query" \!indent=yes
}

function csv2xml () {
  csvjson "$@" | csvjson2xml_file /dev/stdin
}
```

A usage example:
```shell
csv2xml example.csv | less -Sn
```

**Comment by jpmckinney** [comment]
Sorry, we only support CSV and JSON as output formats. However, there are tools like [flatten-tool](https://flatten-tool.readthedocs.io/en/latest/) which can 'unflatten' data from CSV to XML.

**Comment by ruv** [comment]
@jpmckinney, thanks for the link. 

Just a review if somebody wants to try Flatten-tool to convert CSV into XML.

1. It is not a general purpose tool, in [case of CSV to XML](https://flatten-tool.readthedocs.io/en/latest/usage-iati/#convert-a-spreadsheet-to-xml) it confines to IATI format.
2. It can't convert just a single CSV file (or even stdin), it only works with a directory that contains CSV files, and it unions them into one list.
3. It generates XML in ASCII encoding (not UTF-8), with references to the characters beyond ASCII.
4. XML root element is always `iati-activities`.
5. It can't work with a CSV file without the header (i.e. it can't auto-generate column names).
6. 100 MiB libraries by dependencies looks like really overkill for such simple task, but its main purpose is Excel spreadsheets.

**Comment by jpmckinney** [comment]
Thanks for sharing your review!

[Flat file extractor (ffe)](http://ff-extractor.sourceforge.net) looks promising, though you need to define the structure of the input and output.

**Comment by ruv** [comment]
Yes, I used **ffe**. It has also the following issues:

1. It does not do any escaping (since **ffe** by itself does not know anything about XML). So, you need to convert the input CSV file into XML-safely text by means of replacing `&` and `<` characters into the references.

2. It cannot handle CSV files that contain line break in the values (i.e. multi-line value). Although it is not stated explicitly in the documentation, a one [citation](http://ff-extractor.sourceforge.net/ffe.html#Record): "A record specifies one type of **input line** or binary block in a file".
