### ISSUE TITLE
Pitch for a -U flag for csvsort  (again?)

### ISSUE THREAD

**Issue by tlongers** [wireservice/csvkit#996]
Thanks for creating this excellent, indispensable toolkit.  I'd like to reprise briefly issue #448 and attempt a case for building `sort -u` or equivalent into `csvsort`.  Here goes...

Here's issue #488's example of a pipeline to get unique values from a column, excluding the column header:

`csvcut -c 4 myfile.csv | sed 1d | sort | uniq`

Sometimes, I need to  re-add the column header after this processing. In a `csvkit` workflow this can be important. For example, if you want to process the resulting list with `csvgrep` to remove blanks you need a column heading or it fails. So, this can mean adding an  `awk` step or similar: 

`csvcut -c 4 myfile.csv | sed 1d | sort | uniq | awk 'BEGIN{print "column_heading"};{print}'|csvgrep -c 1 -i -r "^$"`

To cut this extra processing, an intuitive add in to `csvsort` would be a `-U` flag:

`csvsort -c 4 -U myfile.csv | csvgrep -c 1 -i -r "^$"`

Anyhow, that's my case. Thanks for listening, and of course no offence taken if my proposal is neither desirable nor a priority. Thanks again.

**Comment by jpmckinney** [comment]
Hmm, this would normally be a separate tool, e.g. `csvuniq`, which has been discussed in other issues, as it isn't conceptually a sub-task of sorting. However, csvkit no longer adds new tools to keep a stable maintenance burden. You might be able to do what you want through csvsql, e.g.:

```
echo "a
foo
foo
bar
bar" | csvsql --query "SELECT a FROM stdin GROUP BY a"
```

**Comment by tlongers** [comment]
Thanks for help and tour through various approaches to the same issue using different pieces of the toolkit: useful and much appreciated. I'll close this issue now.

**Comment by AlexeySalmin** [comment]
A real pity that neither csvuniq nor csvsort --unique can be added.

It's a pain to cut and then add back the header row each time. Not because I can't do it, but because this shell-pipe is not something I can easily share with my colleagues and recommend it as a standard approach.

**Comment by jpmckinney** [comment]
csvkit's docs link to qsv, which offers a sort unique command/option: https://github.com/jqnatividad/qsv
