### ISSUE TITLE
"csvstat --count" ignores command line options (for example, -z)

### ISSUE THREAD

**Issue by buriy** [wireservice/csvkit#999]
That's not ok. For example:
```
$ csvstat --count -z 10000000 -y 0 data/news/2014/2014-10-oko-planet.su.csv
CSV contains fields longer than maximum length of 131072 characters. Try raising the maximum with the field_size_limit parameter, or try setting quoting=csv.QUOTE_NONE.
```

**Comment by jpmckinney** [comment]
Can you provide the information requested here, so that I can debug? https://github.com/wireservice/csvkit/blob/master/CONTRIBUTING.rst#report-a-bug

**Comment by buriy** [comment]
Sorry, the instruction looks very complicated and unfriendly. What is "csvkit tool"?
$ csvkit -v
No such command
$ csvtool -v
csvtool: unknown option '-v'.
Maybe you could provide a shell script which would collect all that stuff you need?
I think my package version is 1.0.3 .
Input file: 
[csvbug-999.txt](https://github.com/wireservice/csvkit/files/2605466/csvbug-999.txt)

**Comment by jpmckinney** [comment]
A csvkit tool is anything like `csvstat`, `csvcut`, etc.

I've made a commit with the fix.
